// Package common/jsbridge/ws
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: ws.Dial
export function Dial(url, onMessage, onOpen, onClose, onError) {
  return $rt.ws.Dial(url, onMessage, onOpen, onClose, onError);
}

// jsbridge: ws.Send
export function Send(conn, msg) {
  return $rt.ws.Send(conn, msg);
}

// jsbridge: ws.Close
export function Close(conn) {
  $rt.ws.Close(conn);
}

// jsbridge: ws.ReadyState
export function ReadyState(conn) {
  return $rt.ws.ReadyState(conn);
}

