// Package common/jsbridge/bc
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: bc.Open
export function Open(name, onMessage) {
  return $rt.bc.Open(name, onMessage);
}

// jsbridge: bc.Send
export function Send(bc, msg) {
  $rt.bc.Send(bc, msg);
}

// jsbridge: bc.Close
export function Close(bc) {
  $rt.bc.Close(bc);
}

