// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orlynits/v1/service.proto

package orlynitsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is used for requests/responses with no data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_orlynits_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_orlynits_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_orlynits_v1_service_proto_rawDescGZIP(), []int{0}
}

// ReadyResponse reports bitcoind readiness
type ReadyResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ready               bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "starting", "syncing", "ready", "stopped"
	SyncProgressPercent int32                  `protobuf:"varint,3,opt,name=sync_progress_percent,json=syncProgressPercent,proto3" json:"sync_progress_percent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_orlynits_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlynits_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_orlynits_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadyResponse) GetSyncProgressPercent() int32 {
	if x != nil {
		return x.SyncProgressPercent
	}
	return 0
}

// BlockchainInfoResponse reports basic chain state
type BlockchainInfoResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Chain                string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"` // "main", "test", "signet", "regtest"
	Blocks               int64                  `protobuf:"varint,2,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Headers              int64                  `protobuf:"varint,3,opt,name=headers,proto3" json:"headers,omitempty"`
	VerificationProgress float64                `protobuf:"fixed64,4,opt,name=verification_progress,json=verificationProgress,proto3" json:"verification_progress,omitempty"`
	InitialBlockDownload bool                   `protobuf:"varint,5,opt,name=initial_block_download,json=initialBlockDownload,proto3" json:"initial_block_download,omitempty"`
	Pruned               bool                   `protobuf:"varint,6,opt,name=pruned,proto3" json:"pruned,omitempty"`
	PruneHeight          int64                  `protobuf:"varint,7,opt,name=prune_height,json=pruneHeight,proto3" json:"prune_height,omitempty"`
	SizeOnDisk           int64                  `protobuf:"varint,8,opt,name=size_on_disk,json=sizeOnDisk,proto3" json:"size_on_disk,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BlockchainInfoResponse) Reset() {
	*x = BlockchainInfoResponse{}
	mi := &file_orlynits_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainInfoResponse) ProtoMessage() {}

func (x *BlockchainInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlynits_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainInfoResponse.ProtoReflect.Descriptor instead.
func (*BlockchainInfoResponse) Descriptor() ([]byte, []int) {
	return file_orlynits_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *BlockchainInfoResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *BlockchainInfoResponse) GetBlocks() int64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *BlockchainInfoResponse) GetHeaders() int64 {
	if x != nil {
		return x.Headers
	}
	return 0
}

func (x *BlockchainInfoResponse) GetVerificationProgress() float64 {
	if x != nil {
		return x.VerificationProgress
	}
	return 0
}

func (x *BlockchainInfoResponse) GetInitialBlockDownload() bool {
	if x != nil {
		return x.InitialBlockDownload
	}
	return false
}

func (x *BlockchainInfoResponse) GetPruned() bool {
	if x != nil {
		return x.Pruned
	}
	return false
}

func (x *BlockchainInfoResponse) GetPruneHeight() int64 {
	if x != nil {
		return x.PruneHeight
	}
	return 0
}

func (x *BlockchainInfoResponse) GetSizeOnDisk() int64 {
	if x != nil {
		return x.SizeOnDisk
	}
	return 0
}

// EstimateFeeRequest specifies the confirmation target
type EstimateFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfTarget    int32                  `protobuf:"varint,1,opt,name=conf_target,json=confTarget,proto3" json:"conf_target,omitempty"` // target number of blocks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFeeRequest) Reset() {
	*x = EstimateFeeRequest{}
	mi := &file_orlynits_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFeeRequest) ProtoMessage() {}

func (x *EstimateFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlynits_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFeeRequest.ProtoReflect.Descriptor instead.
func (*EstimateFeeRequest) Descriptor() ([]byte, []int) {
	return file_orlynits_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *EstimateFeeRequest) GetConfTarget() int32 {
	if x != nil {
		return x.ConfTarget
	}
	return 0
}

// EstimateFeeResponse returns the estimated fee rate
type EstimateFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeRate       float64                `protobuf:"fixed64,1,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"` // BTC/kvB
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFeeResponse) Reset() {
	*x = EstimateFeeResponse{}
	mi := &file_orlynits_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFeeResponse) ProtoMessage() {}

func (x *EstimateFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlynits_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFeeResponse.ProtoReflect.Descriptor instead.
func (*EstimateFeeResponse) Descriptor() ([]byte, []int) {
	return file_orlynits_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *EstimateFeeResponse) GetFeeRate() float64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *EstimateFeeResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_orlynits_v1_service_proto protoreflect.FileDescriptor

const file_orlynits_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19orlynits/v1/service.proto\x12\vorlynits.v1\"\a\n" +
	"\x05Empty\"q\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15sync_progress_percent\x18\x03 \x01(\x05R\x13syncProgressPercent\"\xa8\x02\n" +
	"\x16BlockchainInfoResponse\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x16\n" +
	"\x06blocks\x18\x02 \x01(\x03R\x06blocks\x12\x18\n" +
	"\aheaders\x18\x03 \x01(\x03R\aheaders\x123\n" +
	"\x15verification_progress\x18\x04 \x01(\x01R\x14verificationProgress\x124\n" +
	"\x16initial_block_download\x18\x05 \x01(\bR\x14initialBlockDownload\x12\x16\n" +
	"\x06pruned\x18\x06 \x01(\bR\x06pruned\x12!\n" +
	"\fprune_height\x18\a \x01(\x03R\vpruneHeight\x12 \n" +
	"\fsize_on_disk\x18\b \x01(\x03R\n" +
	"sizeOnDisk\"5\n" +
	"\x12EstimateFeeRequest\x12\x1f\n" +
	"\vconf_target\x18\x01 \x01(\x05R\n" +
	"confTarget\"H\n" +
	"\x13EstimateFeeResponse\x12\x19\n" +
	"\bfee_rate\x18\x01 \x01(\x01R\afeeRate\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\xe6\x01\n" +
	"\vNitsService\x127\n" +
	"\x05Ready\x12\x12.orlynits.v1.Empty\x1a\x1a.orlynits.v1.ReadyResponse\x12L\n" +
	"\x11GetBlockchainInfo\x12\x12.orlynits.v1.Empty\x1a#.orlynits.v1.BlockchainInfoResponse\x12P\n" +
	"\vEstimateFee\x12\x1f.orlynits.v1.EstimateFeeRequest\x1a .orlynits.v1.EstimateFeeResponseB5Z3git.smesh.lol/orly/pkg/proto/orlynits/v1;orlynitsv1b\x06proto3"

var (
	file_orlynits_v1_service_proto_rawDescOnce sync.Once
	file_orlynits_v1_service_proto_rawDescData []byte
)

func file_orlynits_v1_service_proto_rawDescGZIP() []byte {
	file_orlynits_v1_service_proto_rawDescOnce.Do(func() {
		file_orlynits_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orlynits_v1_service_proto_rawDesc), len(file_orlynits_v1_service_proto_rawDesc)))
	})
	return file_orlynits_v1_service_proto_rawDescData
}

var file_orlynits_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orlynits_v1_service_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: orlynits.v1.Empty
	(*ReadyResponse)(nil),          // 1: orlynits.v1.ReadyResponse
	(*BlockchainInfoResponse)(nil), // 2: orlynits.v1.BlockchainInfoResponse
	(*EstimateFeeRequest)(nil),     // 3: orlynits.v1.EstimateFeeRequest
	(*EstimateFeeResponse)(nil),    // 4: orlynits.v1.EstimateFeeResponse
}
var file_orlynits_v1_service_proto_depIdxs = []int32{
	0, // 0: orlynits.v1.NitsService.Ready:input_type -> orlynits.v1.Empty
	0, // 1: orlynits.v1.NitsService.GetBlockchainInfo:input_type -> orlynits.v1.Empty
	3, // 2: orlynits.v1.NitsService.EstimateFee:input_type -> orlynits.v1.EstimateFeeRequest
	1, // 3: orlynits.v1.NitsService.Ready:output_type -> orlynits.v1.ReadyResponse
	2, // 4: orlynits.v1.NitsService.GetBlockchainInfo:output_type -> orlynits.v1.BlockchainInfoResponse
	4, // 5: orlynits.v1.NitsService.EstimateFee:output_type -> orlynits.v1.EstimateFeeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orlynits_v1_service_proto_init() }
func file_orlynits_v1_service_proto_init() {
	if File_orlynits_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orlynits_v1_service_proto_rawDesc), len(file_orlynits_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orlynits_v1_service_proto_goTypes,
		DependencyIndexes: file_orlynits_v1_service_proto_depIdxs,
		MessageInfos:      file_orlynits_v1_service_proto_msgTypes,
	}.Build()
	File_orlynits_v1_service_proto = out.File
	file_orlynits_v1_service_proto_goTypes = nil
	file_orlynits_v1_service_proto_depIdxs = nil
}
