// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orlyacl/v1/acl.proto

package orlyaclv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_orlyacl_v1_acl_proto protoreflect.FileDescriptor

const file_orlyacl_v1_acl_proto_rawDesc = "" +
	"\n" +
	"\x14orlyacl/v1/acl.proto\x12\n" +
	"orlyacl.v1\x1a\x16orlyacl/v1/types.proto2\xc5\x1d\n" +
	"\n" +
	"ACLService\x12Q\n" +
	"\x0eGetAccessLevel\x12\x1e.orlyacl.v1.AccessLevelRequest\x1a\x1f.orlyacl.v1.AccessLevelResponse\x12N\n" +
	"\vCheckPolicy\x12\x1e.orlyacl.v1.PolicyCheckRequest\x1a\x1f.orlyacl.v1.PolicyCheckResponse\x12<\n" +
	"\n" +
	"GetACLInfo\x12\x11.orlyacl.v1.Empty\x1a\x1b.orlyacl.v1.ACLInfoResponse\x126\n" +
	"\aGetMode\x12\x11.orlyacl.v1.Empty\x1a\x18.orlyacl.v1.ModeResponse\x125\n" +
	"\x05Ready\x12\x11.orlyacl.v1.Empty\x1a\x19.orlyacl.v1.ReadyResponse\x12W\n" +
	"\x10GetThrottleDelay\x12 .orlyacl.v1.ThrottleDelayRequest\x1a!.orlyacl.v1.ThrottleDelayResponse\x12<\n" +
	"\tAddFollow\x12\x1c.orlyacl.v1.AddFollowRequest\x1a\x11.orlyacl.v1.Empty\x12L\n" +
	"\x12GetFollowedPubkeys\x12\x11.orlyacl.v1.Empty\x1a#.orlyacl.v1.FollowedPubkeysResponse\x12D\n" +
	"\x0eGetAdminRelays\x12\x11.orlyacl.v1.Empty\x1a\x1f.orlyacl.v1.AdminRelaysResponse\x12<\n" +
	"\tBanPubkey\x12\x1c.orlyacl.v1.BanPubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12;\n" +
	"\vUnbanPubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12M\n" +
	"\x11ListBannedPubkeys\x12\x11.orlyacl.v1.Empty\x1a%.orlyacl.v1.ListBannedPubkeysResponse\x12@\n" +
	"\vAllowPubkey\x12\x1e.orlyacl.v1.AllowPubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12>\n" +
	"\x0eDisallowPubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12O\n" +
	"\x12ListAllowedPubkeys\x12\x11.orlyacl.v1.Empty\x1a&.orlyacl.v1.ListAllowedPubkeysResponse\x12:\n" +
	"\bBanEvent\x12\x1b.orlyacl.v1.BanEventRequest\x1a\x11.orlyacl.v1.Empty\x129\n" +
	"\n" +
	"UnbanEvent\x12\x18.orlyacl.v1.EventRequest\x1a\x11.orlyacl.v1.Empty\x12K\n" +
	"\x10ListBannedEvents\x12\x11.orlyacl.v1.Empty\x1a$.orlyacl.v1.ListBannedEventsResponse\x12<\n" +
	"\n" +
	"AllowEvent\x12\x1b.orlyacl.v1.BanEventRequest\x1a\x11.orlyacl.v1.Empty\x12<\n" +
	"\rDisallowEvent\x12\x18.orlyacl.v1.EventRequest\x1a\x11.orlyacl.v1.Empty\x12M\n" +
	"\x11ListAllowedEvents\x12\x11.orlyacl.v1.Empty\x1a%.orlyacl.v1.ListAllowedEventsResponse\x128\n" +
	"\aBlockIP\x12\x1a.orlyacl.v1.BlockIPRequest\x1a\x11.orlyacl.v1.Empty\x125\n" +
	"\tUnblockIP\x12\x15.orlyacl.v1.IPRequest\x1a\x11.orlyacl.v1.Empty\x12G\n" +
	"\x0eListBlockedIPs\x12\x11.orlyacl.v1.Empty\x1a\".orlyacl.v1.ListBlockedIPsResponse\x12<\n" +
	"\tAllowKind\x12\x1c.orlyacl.v1.AllowKindRequest\x1a\x11.orlyacl.v1.Empty\x12:\n" +
	"\fDisallowKind\x12\x17.orlyacl.v1.KindRequest\x1a\x11.orlyacl.v1.Empty\x12K\n" +
	"\x10ListAllowedKinds\x12\x11.orlyacl.v1.Empty\x1a$.orlyacl.v1.ListAllowedKindsResponse\x12J\n" +
	"\x10UpdatePeerAdmins\x12#.orlyacl.v1.UpdatePeerAdminsRequest\x1a\x11.orlyacl.v1.Empty\x12@\n" +
	"\vTrustPubkey\x12\x1e.orlyacl.v1.TrustPubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12=\n" +
	"\rUntrustPubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12O\n" +
	"\x12ListTrustedPubkeys\x12\x11.orlyacl.v1.Empty\x1a&.orlyacl.v1.ListTrustedPubkeysResponse\x12H\n" +
	"\x0fBlacklistPubkey\x12\".orlyacl.v1.BlacklistPubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12A\n" +
	"\x11UnblacklistPubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12W\n" +
	"\x16ListBlacklistedPubkeys\x12\x11.orlyacl.v1.Empty\x1a*.orlyacl.v1.ListBlacklistedPubkeysResponse\x12:\n" +
	"\bMarkSpam\x12\x1b.orlyacl.v1.MarkSpamRequest\x1a\x11.orlyacl.v1.Empty\x129\n" +
	"\n" +
	"UnmarkSpam\x12\x18.orlyacl.v1.EventRequest\x1a\x11.orlyacl.v1.Empty\x12G\n" +
	"\x0eListSpamEvents\x12\x11.orlyacl.v1.Empty\x1a\".orlyacl.v1.ListSpamEventsResponse\x12W\n" +
	"\x0eRateLimitCheck\x12!.orlyacl.v1.RateLimitCheckRequest\x1a\".orlyacl.v1.RateLimitCheckResponse\x12G\n" +
	"\x12ProcessConfigEvent\x12\x1e.orlyacl.v1.ConfigEventRequest\x1a\x11.orlyacl.v1.Empty\x12B\n" +
	"\x11GetCuratingConfig\x12\x11.orlyacl.v1.Empty\x1a\x1a.orlyacl.v1.CuratingConfig\x12C\n" +
	"\x14IsCuratingConfigured\x12\x11.orlyacl.v1.Empty\x1a\x18.orlyacl.v1.BoolResponse\x12a\n" +
	"\x15ListUnclassifiedUsers\x12\x1d.orlyacl.v1.PaginationRequest\x1a).orlyacl.v1.ListUnclassifiedUsersResponse\x12`\n" +
	"\x12GetEventsForPubkey\x12%.orlyacl.v1.GetEventsForPubkeyRequest\x1a#.orlyacl.v1.EventsForPubkeyResponse\x12b\n" +
	"\x15DeleteEventsForPubkey\x12(.orlyacl.v1.DeleteEventsForPubkeyRequest\x1a\x1f.orlyacl.v1.DeleteCountResponse\x12C\n" +
	"\x0eScanAllPubkeys\x12\x11.orlyacl.v1.Empty\x1a\x1e.orlyacl.v1.ScanResultResponse\x12B\n" +
	"\x0fSubscribePubkey\x12\x1c.orlyacl.v1.SubscribeRequest\x1a\x11.orlyacl.v1.Empty\x12A\n" +
	"\x11UnsubscribePubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x11.orlyacl.v1.Empty\x12C\n" +
	"\fIsSubscribed\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x18.orlyacl.v1.BoolResponse\x12N\n" +
	"\x0fGetSubscription\x12\x19.orlyacl.v1.PubkeyRequest\x1a .orlyacl.v1.SubscriptionResponse\x12>\n" +
	"\n" +
	"ClaimAlias\x12\x1d.orlyacl.v1.ClaimAliasRequest\x1a\x11.orlyacl.v1.Empty\x12H\n" +
	"\x10GetAliasByPubkey\x12\x19.orlyacl.v1.PubkeyRequest\x1a\x19.orlyacl.v1.AliasResponse\x12H\n" +
	"\x10GetPubkeyByAlias\x12\x18.orlyacl.v1.AliasRequest\x1a\x1a.orlyacl.v1.PubkeyResponse\x12B\n" +
	"\fIsAliasTaken\x12\x18.orlyacl.v1.AliasRequest\x1a\x18.orlyacl.v1.BoolResponseB.Z,next.orly.dev/pkg/proto/orlyacl/v1;orlyaclv1b\x06proto3"

var file_orlyacl_v1_acl_proto_goTypes = []any{
	(*AccessLevelRequest)(nil),             // 0: orlyacl.v1.AccessLevelRequest
	(*PolicyCheckRequest)(nil),             // 1: orlyacl.v1.PolicyCheckRequest
	(*Empty)(nil),                          // 2: orlyacl.v1.Empty
	(*ThrottleDelayRequest)(nil),           // 3: orlyacl.v1.ThrottleDelayRequest
	(*AddFollowRequest)(nil),               // 4: orlyacl.v1.AddFollowRequest
	(*BanPubkeyRequest)(nil),               // 5: orlyacl.v1.BanPubkeyRequest
	(*PubkeyRequest)(nil),                  // 6: orlyacl.v1.PubkeyRequest
	(*AllowPubkeyRequest)(nil),             // 7: orlyacl.v1.AllowPubkeyRequest
	(*BanEventRequest)(nil),                // 8: orlyacl.v1.BanEventRequest
	(*EventRequest)(nil),                   // 9: orlyacl.v1.EventRequest
	(*BlockIPRequest)(nil),                 // 10: orlyacl.v1.BlockIPRequest
	(*IPRequest)(nil),                      // 11: orlyacl.v1.IPRequest
	(*AllowKindRequest)(nil),               // 12: orlyacl.v1.AllowKindRequest
	(*KindRequest)(nil),                    // 13: orlyacl.v1.KindRequest
	(*UpdatePeerAdminsRequest)(nil),        // 14: orlyacl.v1.UpdatePeerAdminsRequest
	(*TrustPubkeyRequest)(nil),             // 15: orlyacl.v1.TrustPubkeyRequest
	(*BlacklistPubkeyRequest)(nil),         // 16: orlyacl.v1.BlacklistPubkeyRequest
	(*MarkSpamRequest)(nil),                // 17: orlyacl.v1.MarkSpamRequest
	(*RateLimitCheckRequest)(nil),          // 18: orlyacl.v1.RateLimitCheckRequest
	(*ConfigEventRequest)(nil),             // 19: orlyacl.v1.ConfigEventRequest
	(*PaginationRequest)(nil),              // 20: orlyacl.v1.PaginationRequest
	(*GetEventsForPubkeyRequest)(nil),      // 21: orlyacl.v1.GetEventsForPubkeyRequest
	(*DeleteEventsForPubkeyRequest)(nil),   // 22: orlyacl.v1.DeleteEventsForPubkeyRequest
	(*SubscribeRequest)(nil),               // 23: orlyacl.v1.SubscribeRequest
	(*ClaimAliasRequest)(nil),              // 24: orlyacl.v1.ClaimAliasRequest
	(*AliasRequest)(nil),                   // 25: orlyacl.v1.AliasRequest
	(*AccessLevelResponse)(nil),            // 26: orlyacl.v1.AccessLevelResponse
	(*PolicyCheckResponse)(nil),            // 27: orlyacl.v1.PolicyCheckResponse
	(*ACLInfoResponse)(nil),                // 28: orlyacl.v1.ACLInfoResponse
	(*ModeResponse)(nil),                   // 29: orlyacl.v1.ModeResponse
	(*ReadyResponse)(nil),                  // 30: orlyacl.v1.ReadyResponse
	(*ThrottleDelayResponse)(nil),          // 31: orlyacl.v1.ThrottleDelayResponse
	(*FollowedPubkeysResponse)(nil),        // 32: orlyacl.v1.FollowedPubkeysResponse
	(*AdminRelaysResponse)(nil),            // 33: orlyacl.v1.AdminRelaysResponse
	(*ListBannedPubkeysResponse)(nil),      // 34: orlyacl.v1.ListBannedPubkeysResponse
	(*ListAllowedPubkeysResponse)(nil),     // 35: orlyacl.v1.ListAllowedPubkeysResponse
	(*ListBannedEventsResponse)(nil),       // 36: orlyacl.v1.ListBannedEventsResponse
	(*ListAllowedEventsResponse)(nil),      // 37: orlyacl.v1.ListAllowedEventsResponse
	(*ListBlockedIPsResponse)(nil),         // 38: orlyacl.v1.ListBlockedIPsResponse
	(*ListAllowedKindsResponse)(nil),       // 39: orlyacl.v1.ListAllowedKindsResponse
	(*ListTrustedPubkeysResponse)(nil),     // 40: orlyacl.v1.ListTrustedPubkeysResponse
	(*ListBlacklistedPubkeysResponse)(nil), // 41: orlyacl.v1.ListBlacklistedPubkeysResponse
	(*ListSpamEventsResponse)(nil),         // 42: orlyacl.v1.ListSpamEventsResponse
	(*RateLimitCheckResponse)(nil),         // 43: orlyacl.v1.RateLimitCheckResponse
	(*CuratingConfig)(nil),                 // 44: orlyacl.v1.CuratingConfig
	(*BoolResponse)(nil),                   // 45: orlyacl.v1.BoolResponse
	(*ListUnclassifiedUsersResponse)(nil),  // 46: orlyacl.v1.ListUnclassifiedUsersResponse
	(*EventsForPubkeyResponse)(nil),        // 47: orlyacl.v1.EventsForPubkeyResponse
	(*DeleteCountResponse)(nil),            // 48: orlyacl.v1.DeleteCountResponse
	(*ScanResultResponse)(nil),             // 49: orlyacl.v1.ScanResultResponse
	(*SubscriptionResponse)(nil),           // 50: orlyacl.v1.SubscriptionResponse
	(*AliasResponse)(nil),                  // 51: orlyacl.v1.AliasResponse
	(*PubkeyResponse)(nil),                 // 52: orlyacl.v1.PubkeyResponse
}
var file_orlyacl_v1_acl_proto_depIdxs = []int32{
	0,  // 0: orlyacl.v1.ACLService.GetAccessLevel:input_type -> orlyacl.v1.AccessLevelRequest
	1,  // 1: orlyacl.v1.ACLService.CheckPolicy:input_type -> orlyacl.v1.PolicyCheckRequest
	2,  // 2: orlyacl.v1.ACLService.GetACLInfo:input_type -> orlyacl.v1.Empty
	2,  // 3: orlyacl.v1.ACLService.GetMode:input_type -> orlyacl.v1.Empty
	2,  // 4: orlyacl.v1.ACLService.Ready:input_type -> orlyacl.v1.Empty
	3,  // 5: orlyacl.v1.ACLService.GetThrottleDelay:input_type -> orlyacl.v1.ThrottleDelayRequest
	4,  // 6: orlyacl.v1.ACLService.AddFollow:input_type -> orlyacl.v1.AddFollowRequest
	2,  // 7: orlyacl.v1.ACLService.GetFollowedPubkeys:input_type -> orlyacl.v1.Empty
	2,  // 8: orlyacl.v1.ACLService.GetAdminRelays:input_type -> orlyacl.v1.Empty
	5,  // 9: orlyacl.v1.ACLService.BanPubkey:input_type -> orlyacl.v1.BanPubkeyRequest
	6,  // 10: orlyacl.v1.ACLService.UnbanPubkey:input_type -> orlyacl.v1.PubkeyRequest
	2,  // 11: orlyacl.v1.ACLService.ListBannedPubkeys:input_type -> orlyacl.v1.Empty
	7,  // 12: orlyacl.v1.ACLService.AllowPubkey:input_type -> orlyacl.v1.AllowPubkeyRequest
	6,  // 13: orlyacl.v1.ACLService.DisallowPubkey:input_type -> orlyacl.v1.PubkeyRequest
	2,  // 14: orlyacl.v1.ACLService.ListAllowedPubkeys:input_type -> orlyacl.v1.Empty
	8,  // 15: orlyacl.v1.ACLService.BanEvent:input_type -> orlyacl.v1.BanEventRequest
	9,  // 16: orlyacl.v1.ACLService.UnbanEvent:input_type -> orlyacl.v1.EventRequest
	2,  // 17: orlyacl.v1.ACLService.ListBannedEvents:input_type -> orlyacl.v1.Empty
	8,  // 18: orlyacl.v1.ACLService.AllowEvent:input_type -> orlyacl.v1.BanEventRequest
	9,  // 19: orlyacl.v1.ACLService.DisallowEvent:input_type -> orlyacl.v1.EventRequest
	2,  // 20: orlyacl.v1.ACLService.ListAllowedEvents:input_type -> orlyacl.v1.Empty
	10, // 21: orlyacl.v1.ACLService.BlockIP:input_type -> orlyacl.v1.BlockIPRequest
	11, // 22: orlyacl.v1.ACLService.UnblockIP:input_type -> orlyacl.v1.IPRequest
	2,  // 23: orlyacl.v1.ACLService.ListBlockedIPs:input_type -> orlyacl.v1.Empty
	12, // 24: orlyacl.v1.ACLService.AllowKind:input_type -> orlyacl.v1.AllowKindRequest
	13, // 25: orlyacl.v1.ACLService.DisallowKind:input_type -> orlyacl.v1.KindRequest
	2,  // 26: orlyacl.v1.ACLService.ListAllowedKinds:input_type -> orlyacl.v1.Empty
	14, // 27: orlyacl.v1.ACLService.UpdatePeerAdmins:input_type -> orlyacl.v1.UpdatePeerAdminsRequest
	15, // 28: orlyacl.v1.ACLService.TrustPubkey:input_type -> orlyacl.v1.TrustPubkeyRequest
	6,  // 29: orlyacl.v1.ACLService.UntrustPubkey:input_type -> orlyacl.v1.PubkeyRequest
	2,  // 30: orlyacl.v1.ACLService.ListTrustedPubkeys:input_type -> orlyacl.v1.Empty
	16, // 31: orlyacl.v1.ACLService.BlacklistPubkey:input_type -> orlyacl.v1.BlacklistPubkeyRequest
	6,  // 32: orlyacl.v1.ACLService.UnblacklistPubkey:input_type -> orlyacl.v1.PubkeyRequest
	2,  // 33: orlyacl.v1.ACLService.ListBlacklistedPubkeys:input_type -> orlyacl.v1.Empty
	17, // 34: orlyacl.v1.ACLService.MarkSpam:input_type -> orlyacl.v1.MarkSpamRequest
	9,  // 35: orlyacl.v1.ACLService.UnmarkSpam:input_type -> orlyacl.v1.EventRequest
	2,  // 36: orlyacl.v1.ACLService.ListSpamEvents:input_type -> orlyacl.v1.Empty
	18, // 37: orlyacl.v1.ACLService.RateLimitCheck:input_type -> orlyacl.v1.RateLimitCheckRequest
	19, // 38: orlyacl.v1.ACLService.ProcessConfigEvent:input_type -> orlyacl.v1.ConfigEventRequest
	2,  // 39: orlyacl.v1.ACLService.GetCuratingConfig:input_type -> orlyacl.v1.Empty
	2,  // 40: orlyacl.v1.ACLService.IsCuratingConfigured:input_type -> orlyacl.v1.Empty
	20, // 41: orlyacl.v1.ACLService.ListUnclassifiedUsers:input_type -> orlyacl.v1.PaginationRequest
	21, // 42: orlyacl.v1.ACLService.GetEventsForPubkey:input_type -> orlyacl.v1.GetEventsForPubkeyRequest
	22, // 43: orlyacl.v1.ACLService.DeleteEventsForPubkey:input_type -> orlyacl.v1.DeleteEventsForPubkeyRequest
	2,  // 44: orlyacl.v1.ACLService.ScanAllPubkeys:input_type -> orlyacl.v1.Empty
	23, // 45: orlyacl.v1.ACLService.SubscribePubkey:input_type -> orlyacl.v1.SubscribeRequest
	6,  // 46: orlyacl.v1.ACLService.UnsubscribePubkey:input_type -> orlyacl.v1.PubkeyRequest
	6,  // 47: orlyacl.v1.ACLService.IsSubscribed:input_type -> orlyacl.v1.PubkeyRequest
	6,  // 48: orlyacl.v1.ACLService.GetSubscription:input_type -> orlyacl.v1.PubkeyRequest
	24, // 49: orlyacl.v1.ACLService.ClaimAlias:input_type -> orlyacl.v1.ClaimAliasRequest
	6,  // 50: orlyacl.v1.ACLService.GetAliasByPubkey:input_type -> orlyacl.v1.PubkeyRequest
	25, // 51: orlyacl.v1.ACLService.GetPubkeyByAlias:input_type -> orlyacl.v1.AliasRequest
	25, // 52: orlyacl.v1.ACLService.IsAliasTaken:input_type -> orlyacl.v1.AliasRequest
	26, // 53: orlyacl.v1.ACLService.GetAccessLevel:output_type -> orlyacl.v1.AccessLevelResponse
	27, // 54: orlyacl.v1.ACLService.CheckPolicy:output_type -> orlyacl.v1.PolicyCheckResponse
	28, // 55: orlyacl.v1.ACLService.GetACLInfo:output_type -> orlyacl.v1.ACLInfoResponse
	29, // 56: orlyacl.v1.ACLService.GetMode:output_type -> orlyacl.v1.ModeResponse
	30, // 57: orlyacl.v1.ACLService.Ready:output_type -> orlyacl.v1.ReadyResponse
	31, // 58: orlyacl.v1.ACLService.GetThrottleDelay:output_type -> orlyacl.v1.ThrottleDelayResponse
	2,  // 59: orlyacl.v1.ACLService.AddFollow:output_type -> orlyacl.v1.Empty
	32, // 60: orlyacl.v1.ACLService.GetFollowedPubkeys:output_type -> orlyacl.v1.FollowedPubkeysResponse
	33, // 61: orlyacl.v1.ACLService.GetAdminRelays:output_type -> orlyacl.v1.AdminRelaysResponse
	2,  // 62: orlyacl.v1.ACLService.BanPubkey:output_type -> orlyacl.v1.Empty
	2,  // 63: orlyacl.v1.ACLService.UnbanPubkey:output_type -> orlyacl.v1.Empty
	34, // 64: orlyacl.v1.ACLService.ListBannedPubkeys:output_type -> orlyacl.v1.ListBannedPubkeysResponse
	2,  // 65: orlyacl.v1.ACLService.AllowPubkey:output_type -> orlyacl.v1.Empty
	2,  // 66: orlyacl.v1.ACLService.DisallowPubkey:output_type -> orlyacl.v1.Empty
	35, // 67: orlyacl.v1.ACLService.ListAllowedPubkeys:output_type -> orlyacl.v1.ListAllowedPubkeysResponse
	2,  // 68: orlyacl.v1.ACLService.BanEvent:output_type -> orlyacl.v1.Empty
	2,  // 69: orlyacl.v1.ACLService.UnbanEvent:output_type -> orlyacl.v1.Empty
	36, // 70: orlyacl.v1.ACLService.ListBannedEvents:output_type -> orlyacl.v1.ListBannedEventsResponse
	2,  // 71: orlyacl.v1.ACLService.AllowEvent:output_type -> orlyacl.v1.Empty
	2,  // 72: orlyacl.v1.ACLService.DisallowEvent:output_type -> orlyacl.v1.Empty
	37, // 73: orlyacl.v1.ACLService.ListAllowedEvents:output_type -> orlyacl.v1.ListAllowedEventsResponse
	2,  // 74: orlyacl.v1.ACLService.BlockIP:output_type -> orlyacl.v1.Empty
	2,  // 75: orlyacl.v1.ACLService.UnblockIP:output_type -> orlyacl.v1.Empty
	38, // 76: orlyacl.v1.ACLService.ListBlockedIPs:output_type -> orlyacl.v1.ListBlockedIPsResponse
	2,  // 77: orlyacl.v1.ACLService.AllowKind:output_type -> orlyacl.v1.Empty
	2,  // 78: orlyacl.v1.ACLService.DisallowKind:output_type -> orlyacl.v1.Empty
	39, // 79: orlyacl.v1.ACLService.ListAllowedKinds:output_type -> orlyacl.v1.ListAllowedKindsResponse
	2,  // 80: orlyacl.v1.ACLService.UpdatePeerAdmins:output_type -> orlyacl.v1.Empty
	2,  // 81: orlyacl.v1.ACLService.TrustPubkey:output_type -> orlyacl.v1.Empty
	2,  // 82: orlyacl.v1.ACLService.UntrustPubkey:output_type -> orlyacl.v1.Empty
	40, // 83: orlyacl.v1.ACLService.ListTrustedPubkeys:output_type -> orlyacl.v1.ListTrustedPubkeysResponse
	2,  // 84: orlyacl.v1.ACLService.BlacklistPubkey:output_type -> orlyacl.v1.Empty
	2,  // 85: orlyacl.v1.ACLService.UnblacklistPubkey:output_type -> orlyacl.v1.Empty
	41, // 86: orlyacl.v1.ACLService.ListBlacklistedPubkeys:output_type -> orlyacl.v1.ListBlacklistedPubkeysResponse
	2,  // 87: orlyacl.v1.ACLService.MarkSpam:output_type -> orlyacl.v1.Empty
	2,  // 88: orlyacl.v1.ACLService.UnmarkSpam:output_type -> orlyacl.v1.Empty
	42, // 89: orlyacl.v1.ACLService.ListSpamEvents:output_type -> orlyacl.v1.ListSpamEventsResponse
	43, // 90: orlyacl.v1.ACLService.RateLimitCheck:output_type -> orlyacl.v1.RateLimitCheckResponse
	2,  // 91: orlyacl.v1.ACLService.ProcessConfigEvent:output_type -> orlyacl.v1.Empty
	44, // 92: orlyacl.v1.ACLService.GetCuratingConfig:output_type -> orlyacl.v1.CuratingConfig
	45, // 93: orlyacl.v1.ACLService.IsCuratingConfigured:output_type -> orlyacl.v1.BoolResponse
	46, // 94: orlyacl.v1.ACLService.ListUnclassifiedUsers:output_type -> orlyacl.v1.ListUnclassifiedUsersResponse
	47, // 95: orlyacl.v1.ACLService.GetEventsForPubkey:output_type -> orlyacl.v1.EventsForPubkeyResponse
	48, // 96: orlyacl.v1.ACLService.DeleteEventsForPubkey:output_type -> orlyacl.v1.DeleteCountResponse
	49, // 97: orlyacl.v1.ACLService.ScanAllPubkeys:output_type -> orlyacl.v1.ScanResultResponse
	2,  // 98: orlyacl.v1.ACLService.SubscribePubkey:output_type -> orlyacl.v1.Empty
	2,  // 99: orlyacl.v1.ACLService.UnsubscribePubkey:output_type -> orlyacl.v1.Empty
	45, // 100: orlyacl.v1.ACLService.IsSubscribed:output_type -> orlyacl.v1.BoolResponse
	50, // 101: orlyacl.v1.ACLService.GetSubscription:output_type -> orlyacl.v1.SubscriptionResponse
	2,  // 102: orlyacl.v1.ACLService.ClaimAlias:output_type -> orlyacl.v1.Empty
	51, // 103: orlyacl.v1.ACLService.GetAliasByPubkey:output_type -> orlyacl.v1.AliasResponse
	52, // 104: orlyacl.v1.ACLService.GetPubkeyByAlias:output_type -> orlyacl.v1.PubkeyResponse
	45, // 105: orlyacl.v1.ACLService.IsAliasTaken:output_type -> orlyacl.v1.BoolResponse
	53, // [53:106] is the sub-list for method output_type
	0,  // [0:53] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_orlyacl_v1_acl_proto_init() }
func file_orlyacl_v1_acl_proto_init() {
	if File_orlyacl_v1_acl_proto != nil {
		return
	}
	file_orlyacl_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orlyacl_v1_acl_proto_rawDesc), len(file_orlyacl_v1_acl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orlyacl_v1_acl_proto_goTypes,
		DependencyIndexes: file_orlyacl_v1_acl_proto_depIdxs,
	}.Build()
	File_orlyacl_v1_acl_proto = out.File
	file_orlyacl_v1_acl_proto_goTypes = nil
	file_orlyacl_v1_acl_proto_depIdxs = nil
}
