// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: orlyacl/v1/acl.proto

package orlyaclv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ACLService_GetAccessLevel_FullMethodName         = "/orlyacl.v1.ACLService/GetAccessLevel"
	ACLService_CheckPolicy_FullMethodName            = "/orlyacl.v1.ACLService/CheckPolicy"
	ACLService_GetACLInfo_FullMethodName             = "/orlyacl.v1.ACLService/GetACLInfo"
	ACLService_GetMode_FullMethodName                = "/orlyacl.v1.ACLService/GetMode"
	ACLService_Ready_FullMethodName                  = "/orlyacl.v1.ACLService/Ready"
	ACLService_GetThrottleDelay_FullMethodName       = "/orlyacl.v1.ACLService/GetThrottleDelay"
	ACLService_AddFollow_FullMethodName              = "/orlyacl.v1.ACLService/AddFollow"
	ACLService_GetFollowedPubkeys_FullMethodName     = "/orlyacl.v1.ACLService/GetFollowedPubkeys"
	ACLService_GetAdminRelays_FullMethodName         = "/orlyacl.v1.ACLService/GetAdminRelays"
	ACLService_BanPubkey_FullMethodName              = "/orlyacl.v1.ACLService/BanPubkey"
	ACLService_UnbanPubkey_FullMethodName            = "/orlyacl.v1.ACLService/UnbanPubkey"
	ACLService_ListBannedPubkeys_FullMethodName      = "/orlyacl.v1.ACLService/ListBannedPubkeys"
	ACLService_AllowPubkey_FullMethodName            = "/orlyacl.v1.ACLService/AllowPubkey"
	ACLService_DisallowPubkey_FullMethodName         = "/orlyacl.v1.ACLService/DisallowPubkey"
	ACLService_ListAllowedPubkeys_FullMethodName     = "/orlyacl.v1.ACLService/ListAllowedPubkeys"
	ACLService_BanEvent_FullMethodName               = "/orlyacl.v1.ACLService/BanEvent"
	ACLService_UnbanEvent_FullMethodName             = "/orlyacl.v1.ACLService/UnbanEvent"
	ACLService_ListBannedEvents_FullMethodName       = "/orlyacl.v1.ACLService/ListBannedEvents"
	ACLService_AllowEvent_FullMethodName             = "/orlyacl.v1.ACLService/AllowEvent"
	ACLService_DisallowEvent_FullMethodName          = "/orlyacl.v1.ACLService/DisallowEvent"
	ACLService_ListAllowedEvents_FullMethodName      = "/orlyacl.v1.ACLService/ListAllowedEvents"
	ACLService_BlockIP_FullMethodName                = "/orlyacl.v1.ACLService/BlockIP"
	ACLService_UnblockIP_FullMethodName              = "/orlyacl.v1.ACLService/UnblockIP"
	ACLService_ListBlockedIPs_FullMethodName         = "/orlyacl.v1.ACLService/ListBlockedIPs"
	ACLService_AllowKind_FullMethodName              = "/orlyacl.v1.ACLService/AllowKind"
	ACLService_DisallowKind_FullMethodName           = "/orlyacl.v1.ACLService/DisallowKind"
	ACLService_ListAllowedKinds_FullMethodName       = "/orlyacl.v1.ACLService/ListAllowedKinds"
	ACLService_UpdatePeerAdmins_FullMethodName       = "/orlyacl.v1.ACLService/UpdatePeerAdmins"
	ACLService_TrustPubkey_FullMethodName            = "/orlyacl.v1.ACLService/TrustPubkey"
	ACLService_UntrustPubkey_FullMethodName          = "/orlyacl.v1.ACLService/UntrustPubkey"
	ACLService_ListTrustedPubkeys_FullMethodName     = "/orlyacl.v1.ACLService/ListTrustedPubkeys"
	ACLService_BlacklistPubkey_FullMethodName        = "/orlyacl.v1.ACLService/BlacklistPubkey"
	ACLService_UnblacklistPubkey_FullMethodName      = "/orlyacl.v1.ACLService/UnblacklistPubkey"
	ACLService_ListBlacklistedPubkeys_FullMethodName = "/orlyacl.v1.ACLService/ListBlacklistedPubkeys"
	ACLService_MarkSpam_FullMethodName               = "/orlyacl.v1.ACLService/MarkSpam"
	ACLService_UnmarkSpam_FullMethodName             = "/orlyacl.v1.ACLService/UnmarkSpam"
	ACLService_ListSpamEvents_FullMethodName         = "/orlyacl.v1.ACLService/ListSpamEvents"
	ACLService_RateLimitCheck_FullMethodName         = "/orlyacl.v1.ACLService/RateLimitCheck"
	ACLService_ProcessConfigEvent_FullMethodName     = "/orlyacl.v1.ACLService/ProcessConfigEvent"
	ACLService_GetCuratingConfig_FullMethodName      = "/orlyacl.v1.ACLService/GetCuratingConfig"
	ACLService_IsCuratingConfigured_FullMethodName   = "/orlyacl.v1.ACLService/IsCuratingConfigured"
	ACLService_ListUnclassifiedUsers_FullMethodName  = "/orlyacl.v1.ACLService/ListUnclassifiedUsers"
	ACLService_GetEventsForPubkey_FullMethodName     = "/orlyacl.v1.ACLService/GetEventsForPubkey"
	ACLService_DeleteEventsForPubkey_FullMethodName  = "/orlyacl.v1.ACLService/DeleteEventsForPubkey"
	ACLService_ScanAllPubkeys_FullMethodName         = "/orlyacl.v1.ACLService/ScanAllPubkeys"
	ACLService_SubscribePubkey_FullMethodName        = "/orlyacl.v1.ACLService/SubscribePubkey"
	ACLService_UnsubscribePubkey_FullMethodName      = "/orlyacl.v1.ACLService/UnsubscribePubkey"
	ACLService_IsSubscribed_FullMethodName           = "/orlyacl.v1.ACLService/IsSubscribed"
	ACLService_GetSubscription_FullMethodName        = "/orlyacl.v1.ACLService/GetSubscription"
	ACLService_ClaimAlias_FullMethodName             = "/orlyacl.v1.ACLService/ClaimAlias"
	ACLService_GetAliasByPubkey_FullMethodName       = "/orlyacl.v1.ACLService/GetAliasByPubkey"
	ACLService_GetPubkeyByAlias_FullMethodName       = "/orlyacl.v1.ACLService/GetPubkeyByAlias"
	ACLService_IsAliasTaken_FullMethodName           = "/orlyacl.v1.ACLService/IsAliasTaken"
)

// ACLServiceClient is the client API for ACLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ACLService provides access control operations for the Nostr relay
type ACLServiceClient interface {
	// GetAccessLevel returns the access level for a pubkey from an IP address
	GetAccessLevel(ctx context.Context, in *AccessLevelRequest, opts ...grpc.CallOption) (*AccessLevelResponse, error)
	// CheckPolicy checks if an event passes policy checks
	CheckPolicy(ctx context.Context, in *PolicyCheckRequest, opts ...grpc.CallOption) (*PolicyCheckResponse, error)
	// GetACLInfo returns information about the active ACL mode
	GetACLInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ACLInfoResponse, error)
	// GetMode returns the current ACL mode (none/follows/managed/curating)
	GetMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModeResponse, error)
	// Ready checks if the ACL service is ready
	Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReadyResponse, error)
	// GetThrottleDelay returns the progressive throttle delay for a pubkey
	GetThrottleDelay(ctx context.Context, in *ThrottleDelayRequest, opts ...grpc.CallOption) (*ThrottleDelayResponse, error)
	// AddFollow adds a pubkey to the followed list
	AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetFollowedPubkeys returns all followed pubkeys
	GetFollowedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FollowedPubkeysResponse, error)
	// GetAdminRelays returns the relay URLs from admin kind 10002 events
	GetAdminRelays(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminRelaysResponse, error)
	// BanPubkey adds a pubkey to the ban list
	BanPubkey(ctx context.Context, in *BanPubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnbanPubkey removes a pubkey from the ban list
	UnbanPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListBannedPubkeys returns all banned pubkeys
	ListBannedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBannedPubkeysResponse, error)
	// AllowPubkey adds a pubkey to the allow list
	AllowPubkey(ctx context.Context, in *AllowPubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// DisallowPubkey removes a pubkey from the allow list
	DisallowPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListAllowedPubkeys returns all explicitly allowed pubkeys
	ListAllowedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedPubkeysResponse, error)
	// BanEvent adds an event to the ban list
	BanEvent(ctx context.Context, in *BanEventRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnbanEvent removes an event from the ban list
	UnbanEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListBannedEvents returns all banned events
	ListBannedEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBannedEventsResponse, error)
	// AllowEvent adds an event to the allow list
	AllowEvent(ctx context.Context, in *BanEventRequest, opts ...grpc.CallOption) (*Empty, error)
	// DisallowEvent removes an event from the allow list
	DisallowEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListAllowedEvents returns all explicitly allowed events
	ListAllowedEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedEventsResponse, error)
	// BlockIP adds an IP to the block list
	BlockIP(ctx context.Context, in *BlockIPRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnblockIP removes an IP from the block list
	UnblockIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListBlockedIPs returns all blocked IPs
	ListBlockedIPs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBlockedIPsResponse, error)
	// AllowKind adds a kind to the allow list
	AllowKind(ctx context.Context, in *AllowKindRequest, opts ...grpc.CallOption) (*Empty, error)
	// DisallowKind removes a kind from the allow list
	DisallowKind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListAllowedKinds returns all allowed kinds
	ListAllowedKinds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedKindsResponse, error)
	// UpdatePeerAdmins updates the peer relay identity pubkeys
	UpdatePeerAdmins(ctx context.Context, in *UpdatePeerAdminsRequest, opts ...grpc.CallOption) (*Empty, error)
	// TrustPubkey adds a pubkey to the trusted list
	TrustPubkey(ctx context.Context, in *TrustPubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// UntrustPubkey removes a pubkey from the trusted list
	UntrustPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListTrustedPubkeys returns all trusted pubkeys
	ListTrustedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTrustedPubkeysResponse, error)
	// BlacklistPubkey adds a pubkey to the blacklist
	BlacklistPubkey(ctx context.Context, in *BlacklistPubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnblacklistPubkey removes a pubkey from the blacklist
	UnblacklistPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListBlacklistedPubkeys returns all blacklisted pubkeys
	ListBlacklistedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBlacklistedPubkeysResponse, error)
	// MarkSpam marks an event as spam
	MarkSpam(ctx context.Context, in *MarkSpamRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnmarkSpam removes the spam flag from an event
	UnmarkSpam(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListSpamEvents returns all spam-flagged events
	ListSpamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSpamEventsResponse, error)
	// RateLimitCheck checks if a pubkey/IP can publish (rate limiting)
	RateLimitCheck(ctx context.Context, in *RateLimitCheckRequest, opts ...grpc.CallOption) (*RateLimitCheckResponse, error)
	// ProcessConfigEvent processes a curating config event (kind 30078)
	ProcessConfigEvent(ctx context.Context, in *ConfigEventRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetCuratingConfig returns the current curating configuration
	GetCuratingConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CuratingConfig, error)
	// IsCuratingConfigured checks if curating mode is configured
	IsCuratingConfigured(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolResponse, error)
	// ListUnclassifiedUsers returns users who are not trusted or blacklisted
	ListUnclassifiedUsers(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListUnclassifiedUsersResponse, error)
	// GetEventsForPubkey returns events for a specific pubkey
	GetEventsForPubkey(ctx context.Context, in *GetEventsForPubkeyRequest, opts ...grpc.CallOption) (*EventsForPubkeyResponse, error)
	// DeleteEventsForPubkey deletes all events for a pubkey
	DeleteEventsForPubkey(ctx context.Context, in *DeleteEventsForPubkeyRequest, opts ...grpc.CallOption) (*DeleteCountResponse, error)
	// ScanAllPubkeys scans and indexes all pubkeys in the database
	ScanAllPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScanResultResponse, error)
	// SubscribePubkey activates a subscription for a pubkey
	SubscribePubkey(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*Empty, error)
	// UnsubscribePubkey removes a subscription
	UnsubscribePubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error)
	// IsSubscribed checks if a pubkey has an active subscription
	IsSubscribed(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// GetSubscription returns subscription details for a pubkey
	GetSubscription(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	// ClaimAlias claims an email alias for a pubkey
	ClaimAlias(ctx context.Context, in *ClaimAliasRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetAliasByPubkey returns the alias for a pubkey
	GetAliasByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*AliasResponse, error)
	// GetPubkeyByAlias returns the pubkey for an alias
	GetPubkeyByAlias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*PubkeyResponse, error)
	// IsAliasTaken checks if an alias is already claimed
	IsAliasTaken(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*BoolResponse, error)
}

type aCLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewACLServiceClient(cc grpc.ClientConnInterface) ACLServiceClient {
	return &aCLServiceClient{cc}
}

func (c *aCLServiceClient) GetAccessLevel(ctx context.Context, in *AccessLevelRequest, opts ...grpc.CallOption) (*AccessLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessLevelResponse)
	err := c.cc.Invoke(ctx, ACLService_GetAccessLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) CheckPolicy(ctx context.Context, in *PolicyCheckRequest, opts ...grpc.CallOption) (*PolicyCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyCheckResponse)
	err := c.cc.Invoke(ctx, ACLService_CheckPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetACLInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ACLInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLInfoResponse)
	err := c.cc.Invoke(ctx, ACLService_GetACLInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeResponse)
	err := c.cc.Invoke(ctx, ACLService_GetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, ACLService_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetThrottleDelay(ctx context.Context, in *ThrottleDelayRequest, opts ...grpc.CallOption) (*ThrottleDelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThrottleDelayResponse)
	err := c.cc.Invoke(ctx, ACLService_GetThrottleDelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_AddFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetFollowedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FollowedPubkeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowedPubkeysResponse)
	err := c.cc.Invoke(ctx, ACLService_GetFollowedPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetAdminRelays(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AdminRelaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRelaysResponse)
	err := c.cc.Invoke(ctx, ACLService_GetAdminRelays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) BanPubkey(ctx context.Context, in *BanPubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_BanPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnbanPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnbanPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListBannedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBannedPubkeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBannedPubkeysResponse)
	err := c.cc.Invoke(ctx, ACLService_ListBannedPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) AllowPubkey(ctx context.Context, in *AllowPubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_AllowPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) DisallowPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_DisallowPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListAllowedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedPubkeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllowedPubkeysResponse)
	err := c.cc.Invoke(ctx, ACLService_ListAllowedPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) BanEvent(ctx context.Context, in *BanEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_BanEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnbanEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnbanEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListBannedEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBannedEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBannedEventsResponse)
	err := c.cc.Invoke(ctx, ACLService_ListBannedEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) AllowEvent(ctx context.Context, in *BanEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_AllowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) DisallowEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_DisallowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListAllowedEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllowedEventsResponse)
	err := c.cc.Invoke(ctx, ACLService_ListAllowedEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) BlockIP(ctx context.Context, in *BlockIPRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_BlockIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnblockIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnblockIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListBlockedIPs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBlockedIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedIPsResponse)
	err := c.cc.Invoke(ctx, ACLService_ListBlockedIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) AllowKind(ctx context.Context, in *AllowKindRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_AllowKind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) DisallowKind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_DisallowKind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListAllowedKinds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllowedKindsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllowedKindsResponse)
	err := c.cc.Invoke(ctx, ACLService_ListAllowedKinds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UpdatePeerAdmins(ctx context.Context, in *UpdatePeerAdminsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UpdatePeerAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) TrustPubkey(ctx context.Context, in *TrustPubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_TrustPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UntrustPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UntrustPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListTrustedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTrustedPubkeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrustedPubkeysResponse)
	err := c.cc.Invoke(ctx, ACLService_ListTrustedPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) BlacklistPubkey(ctx context.Context, in *BlacklistPubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_BlacklistPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnblacklistPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnblacklistPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListBlacklistedPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListBlacklistedPubkeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistedPubkeysResponse)
	err := c.cc.Invoke(ctx, ACLService_ListBlacklistedPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) MarkSpam(ctx context.Context, in *MarkSpamRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_MarkSpam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnmarkSpam(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnmarkSpam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListSpamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSpamEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpamEventsResponse)
	err := c.cc.Invoke(ctx, ACLService_ListSpamEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) RateLimitCheck(ctx context.Context, in *RateLimitCheckRequest, opts ...grpc.CallOption) (*RateLimitCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitCheckResponse)
	err := c.cc.Invoke(ctx, ACLService_RateLimitCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ProcessConfigEvent(ctx context.Context, in *ConfigEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_ProcessConfigEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetCuratingConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CuratingConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CuratingConfig)
	err := c.cc.Invoke(ctx, ACLService_GetCuratingConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) IsCuratingConfigured(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ACLService_IsCuratingConfigured_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ListUnclassifiedUsers(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ListUnclassifiedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUnclassifiedUsersResponse)
	err := c.cc.Invoke(ctx, ACLService_ListUnclassifiedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetEventsForPubkey(ctx context.Context, in *GetEventsForPubkeyRequest, opts ...grpc.CallOption) (*EventsForPubkeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsForPubkeyResponse)
	err := c.cc.Invoke(ctx, ACLService_GetEventsForPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) DeleteEventsForPubkey(ctx context.Context, in *DeleteEventsForPubkeyRequest, opts ...grpc.CallOption) (*DeleteCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCountResponse)
	err := c.cc.Invoke(ctx, ACLService_DeleteEventsForPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ScanAllPubkeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScanResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResultResponse)
	err := c.cc.Invoke(ctx, ACLService_ScanAllPubkeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) SubscribePubkey(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_SubscribePubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) UnsubscribePubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_UnsubscribePubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) IsSubscribed(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ACLService_IsSubscribed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetSubscription(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, ACLService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) ClaimAlias(ctx context.Context, in *ClaimAliasRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ACLService_ClaimAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetAliasByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*AliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliasResponse)
	err := c.cc.Invoke(ctx, ACLService_GetAliasByPubkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) GetPubkeyByAlias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*PubkeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PubkeyResponse)
	err := c.cc.Invoke(ctx, ACLService_GetPubkeyByAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCLServiceClient) IsAliasTaken(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ACLService_IsAliasTaken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACLServiceServer is the server API for ACLService service.
// All implementations must embed UnimplementedACLServiceServer
// for forward compatibility.
//
// ACLService provides access control operations for the Nostr relay
type ACLServiceServer interface {
	// GetAccessLevel returns the access level for a pubkey from an IP address
	GetAccessLevel(context.Context, *AccessLevelRequest) (*AccessLevelResponse, error)
	// CheckPolicy checks if an event passes policy checks
	CheckPolicy(context.Context, *PolicyCheckRequest) (*PolicyCheckResponse, error)
	// GetACLInfo returns information about the active ACL mode
	GetACLInfo(context.Context, *Empty) (*ACLInfoResponse, error)
	// GetMode returns the current ACL mode (none/follows/managed/curating)
	GetMode(context.Context, *Empty) (*ModeResponse, error)
	// Ready checks if the ACL service is ready
	Ready(context.Context, *Empty) (*ReadyResponse, error)
	// GetThrottleDelay returns the progressive throttle delay for a pubkey
	GetThrottleDelay(context.Context, *ThrottleDelayRequest) (*ThrottleDelayResponse, error)
	// AddFollow adds a pubkey to the followed list
	AddFollow(context.Context, *AddFollowRequest) (*Empty, error)
	// GetFollowedPubkeys returns all followed pubkeys
	GetFollowedPubkeys(context.Context, *Empty) (*FollowedPubkeysResponse, error)
	// GetAdminRelays returns the relay URLs from admin kind 10002 events
	GetAdminRelays(context.Context, *Empty) (*AdminRelaysResponse, error)
	// BanPubkey adds a pubkey to the ban list
	BanPubkey(context.Context, *BanPubkeyRequest) (*Empty, error)
	// UnbanPubkey removes a pubkey from the ban list
	UnbanPubkey(context.Context, *PubkeyRequest) (*Empty, error)
	// ListBannedPubkeys returns all banned pubkeys
	ListBannedPubkeys(context.Context, *Empty) (*ListBannedPubkeysResponse, error)
	// AllowPubkey adds a pubkey to the allow list
	AllowPubkey(context.Context, *AllowPubkeyRequest) (*Empty, error)
	// DisallowPubkey removes a pubkey from the allow list
	DisallowPubkey(context.Context, *PubkeyRequest) (*Empty, error)
	// ListAllowedPubkeys returns all explicitly allowed pubkeys
	ListAllowedPubkeys(context.Context, *Empty) (*ListAllowedPubkeysResponse, error)
	// BanEvent adds an event to the ban list
	BanEvent(context.Context, *BanEventRequest) (*Empty, error)
	// UnbanEvent removes an event from the ban list
	UnbanEvent(context.Context, *EventRequest) (*Empty, error)
	// ListBannedEvents returns all banned events
	ListBannedEvents(context.Context, *Empty) (*ListBannedEventsResponse, error)
	// AllowEvent adds an event to the allow list
	AllowEvent(context.Context, *BanEventRequest) (*Empty, error)
	// DisallowEvent removes an event from the allow list
	DisallowEvent(context.Context, *EventRequest) (*Empty, error)
	// ListAllowedEvents returns all explicitly allowed events
	ListAllowedEvents(context.Context, *Empty) (*ListAllowedEventsResponse, error)
	// BlockIP adds an IP to the block list
	BlockIP(context.Context, *BlockIPRequest) (*Empty, error)
	// UnblockIP removes an IP from the block list
	UnblockIP(context.Context, *IPRequest) (*Empty, error)
	// ListBlockedIPs returns all blocked IPs
	ListBlockedIPs(context.Context, *Empty) (*ListBlockedIPsResponse, error)
	// AllowKind adds a kind to the allow list
	AllowKind(context.Context, *AllowKindRequest) (*Empty, error)
	// DisallowKind removes a kind from the allow list
	DisallowKind(context.Context, *KindRequest) (*Empty, error)
	// ListAllowedKinds returns all allowed kinds
	ListAllowedKinds(context.Context, *Empty) (*ListAllowedKindsResponse, error)
	// UpdatePeerAdmins updates the peer relay identity pubkeys
	UpdatePeerAdmins(context.Context, *UpdatePeerAdminsRequest) (*Empty, error)
	// TrustPubkey adds a pubkey to the trusted list
	TrustPubkey(context.Context, *TrustPubkeyRequest) (*Empty, error)
	// UntrustPubkey removes a pubkey from the trusted list
	UntrustPubkey(context.Context, *PubkeyRequest) (*Empty, error)
	// ListTrustedPubkeys returns all trusted pubkeys
	ListTrustedPubkeys(context.Context, *Empty) (*ListTrustedPubkeysResponse, error)
	// BlacklistPubkey adds a pubkey to the blacklist
	BlacklistPubkey(context.Context, *BlacklistPubkeyRequest) (*Empty, error)
	// UnblacklistPubkey removes a pubkey from the blacklist
	UnblacklistPubkey(context.Context, *PubkeyRequest) (*Empty, error)
	// ListBlacklistedPubkeys returns all blacklisted pubkeys
	ListBlacklistedPubkeys(context.Context, *Empty) (*ListBlacklistedPubkeysResponse, error)
	// MarkSpam marks an event as spam
	MarkSpam(context.Context, *MarkSpamRequest) (*Empty, error)
	// UnmarkSpam removes the spam flag from an event
	UnmarkSpam(context.Context, *EventRequest) (*Empty, error)
	// ListSpamEvents returns all spam-flagged events
	ListSpamEvents(context.Context, *Empty) (*ListSpamEventsResponse, error)
	// RateLimitCheck checks if a pubkey/IP can publish (rate limiting)
	RateLimitCheck(context.Context, *RateLimitCheckRequest) (*RateLimitCheckResponse, error)
	// ProcessConfigEvent processes a curating config event (kind 30078)
	ProcessConfigEvent(context.Context, *ConfigEventRequest) (*Empty, error)
	// GetCuratingConfig returns the current curating configuration
	GetCuratingConfig(context.Context, *Empty) (*CuratingConfig, error)
	// IsCuratingConfigured checks if curating mode is configured
	IsCuratingConfigured(context.Context, *Empty) (*BoolResponse, error)
	// ListUnclassifiedUsers returns users who are not trusted or blacklisted
	ListUnclassifiedUsers(context.Context, *PaginationRequest) (*ListUnclassifiedUsersResponse, error)
	// GetEventsForPubkey returns events for a specific pubkey
	GetEventsForPubkey(context.Context, *GetEventsForPubkeyRequest) (*EventsForPubkeyResponse, error)
	// DeleteEventsForPubkey deletes all events for a pubkey
	DeleteEventsForPubkey(context.Context, *DeleteEventsForPubkeyRequest) (*DeleteCountResponse, error)
	// ScanAllPubkeys scans and indexes all pubkeys in the database
	ScanAllPubkeys(context.Context, *Empty) (*ScanResultResponse, error)
	// SubscribePubkey activates a subscription for a pubkey
	SubscribePubkey(context.Context, *SubscribeRequest) (*Empty, error)
	// UnsubscribePubkey removes a subscription
	UnsubscribePubkey(context.Context, *PubkeyRequest) (*Empty, error)
	// IsSubscribed checks if a pubkey has an active subscription
	IsSubscribed(context.Context, *PubkeyRequest) (*BoolResponse, error)
	// GetSubscription returns subscription details for a pubkey
	GetSubscription(context.Context, *PubkeyRequest) (*SubscriptionResponse, error)
	// ClaimAlias claims an email alias for a pubkey
	ClaimAlias(context.Context, *ClaimAliasRequest) (*Empty, error)
	// GetAliasByPubkey returns the alias for a pubkey
	GetAliasByPubkey(context.Context, *PubkeyRequest) (*AliasResponse, error)
	// GetPubkeyByAlias returns the pubkey for an alias
	GetPubkeyByAlias(context.Context, *AliasRequest) (*PubkeyResponse, error)
	// IsAliasTaken checks if an alias is already claimed
	IsAliasTaken(context.Context, *AliasRequest) (*BoolResponse, error)
	mustEmbedUnimplementedACLServiceServer()
}

// UnimplementedACLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedACLServiceServer struct{}

func (UnimplementedACLServiceServer) GetAccessLevel(context.Context, *AccessLevelRequest) (*AccessLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccessLevel not implemented")
}
func (UnimplementedACLServiceServer) CheckPolicy(context.Context, *PolicyCheckRequest) (*PolicyCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPolicy not implemented")
}
func (UnimplementedACLServiceServer) GetACLInfo(context.Context, *Empty) (*ACLInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetACLInfo not implemented")
}
func (UnimplementedACLServiceServer) GetMode(context.Context, *Empty) (*ModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMode not implemented")
}
func (UnimplementedACLServiceServer) Ready(context.Context, *Empty) (*ReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedACLServiceServer) GetThrottleDelay(context.Context, *ThrottleDelayRequest) (*ThrottleDelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThrottleDelay not implemented")
}
func (UnimplementedACLServiceServer) AddFollow(context.Context, *AddFollowRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFollow not implemented")
}
func (UnimplementedACLServiceServer) GetFollowedPubkeys(context.Context, *Empty) (*FollowedPubkeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowedPubkeys not implemented")
}
func (UnimplementedACLServiceServer) GetAdminRelays(context.Context, *Empty) (*AdminRelaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminRelays not implemented")
}
func (UnimplementedACLServiceServer) BanPubkey(context.Context, *BanPubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BanPubkey not implemented")
}
func (UnimplementedACLServiceServer) UnbanPubkey(context.Context, *PubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanPubkey not implemented")
}
func (UnimplementedACLServiceServer) ListBannedPubkeys(context.Context, *Empty) (*ListBannedPubkeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBannedPubkeys not implemented")
}
func (UnimplementedACLServiceServer) AllowPubkey(context.Context, *AllowPubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AllowPubkey not implemented")
}
func (UnimplementedACLServiceServer) DisallowPubkey(context.Context, *PubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DisallowPubkey not implemented")
}
func (UnimplementedACLServiceServer) ListAllowedPubkeys(context.Context, *Empty) (*ListAllowedPubkeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllowedPubkeys not implemented")
}
func (UnimplementedACLServiceServer) BanEvent(context.Context, *BanEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BanEvent not implemented")
}
func (UnimplementedACLServiceServer) UnbanEvent(context.Context, *EventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanEvent not implemented")
}
func (UnimplementedACLServiceServer) ListBannedEvents(context.Context, *Empty) (*ListBannedEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBannedEvents not implemented")
}
func (UnimplementedACLServiceServer) AllowEvent(context.Context, *BanEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AllowEvent not implemented")
}
func (UnimplementedACLServiceServer) DisallowEvent(context.Context, *EventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DisallowEvent not implemented")
}
func (UnimplementedACLServiceServer) ListAllowedEvents(context.Context, *Empty) (*ListAllowedEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllowedEvents not implemented")
}
func (UnimplementedACLServiceServer) BlockIP(context.Context, *BlockIPRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockIP not implemented")
}
func (UnimplementedACLServiceServer) UnblockIP(context.Context, *IPRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockIP not implemented")
}
func (UnimplementedACLServiceServer) ListBlockedIPs(context.Context, *Empty) (*ListBlockedIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockedIPs not implemented")
}
func (UnimplementedACLServiceServer) AllowKind(context.Context, *AllowKindRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AllowKind not implemented")
}
func (UnimplementedACLServiceServer) DisallowKind(context.Context, *KindRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DisallowKind not implemented")
}
func (UnimplementedACLServiceServer) ListAllowedKinds(context.Context, *Empty) (*ListAllowedKindsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllowedKinds not implemented")
}
func (UnimplementedACLServiceServer) UpdatePeerAdmins(context.Context, *UpdatePeerAdminsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePeerAdmins not implemented")
}
func (UnimplementedACLServiceServer) TrustPubkey(context.Context, *TrustPubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TrustPubkey not implemented")
}
func (UnimplementedACLServiceServer) UntrustPubkey(context.Context, *PubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UntrustPubkey not implemented")
}
func (UnimplementedACLServiceServer) ListTrustedPubkeys(context.Context, *Empty) (*ListTrustedPubkeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrustedPubkeys not implemented")
}
func (UnimplementedACLServiceServer) BlacklistPubkey(context.Context, *BlacklistPubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BlacklistPubkey not implemented")
}
func (UnimplementedACLServiceServer) UnblacklistPubkey(context.Context, *PubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblacklistPubkey not implemented")
}
func (UnimplementedACLServiceServer) ListBlacklistedPubkeys(context.Context, *Empty) (*ListBlacklistedPubkeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlacklistedPubkeys not implemented")
}
func (UnimplementedACLServiceServer) MarkSpam(context.Context, *MarkSpamRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkSpam not implemented")
}
func (UnimplementedACLServiceServer) UnmarkSpam(context.Context, *EventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmarkSpam not implemented")
}
func (UnimplementedACLServiceServer) ListSpamEvents(context.Context, *Empty) (*ListSpamEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpamEvents not implemented")
}
func (UnimplementedACLServiceServer) RateLimitCheck(context.Context, *RateLimitCheckRequest) (*RateLimitCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateLimitCheck not implemented")
}
func (UnimplementedACLServiceServer) ProcessConfigEvent(context.Context, *ConfigEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessConfigEvent not implemented")
}
func (UnimplementedACLServiceServer) GetCuratingConfig(context.Context, *Empty) (*CuratingConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCuratingConfig not implemented")
}
func (UnimplementedACLServiceServer) IsCuratingConfigured(context.Context, *Empty) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsCuratingConfigured not implemented")
}
func (UnimplementedACLServiceServer) ListUnclassifiedUsers(context.Context, *PaginationRequest) (*ListUnclassifiedUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUnclassifiedUsers not implemented")
}
func (UnimplementedACLServiceServer) GetEventsForPubkey(context.Context, *GetEventsForPubkeyRequest) (*EventsForPubkeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsForPubkey not implemented")
}
func (UnimplementedACLServiceServer) DeleteEventsForPubkey(context.Context, *DeleteEventsForPubkeyRequest) (*DeleteCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEventsForPubkey not implemented")
}
func (UnimplementedACLServiceServer) ScanAllPubkeys(context.Context, *Empty) (*ScanResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanAllPubkeys not implemented")
}
func (UnimplementedACLServiceServer) SubscribePubkey(context.Context, *SubscribeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribePubkey not implemented")
}
func (UnimplementedACLServiceServer) UnsubscribePubkey(context.Context, *PubkeyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribePubkey not implemented")
}
func (UnimplementedACLServiceServer) IsSubscribed(context.Context, *PubkeyRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsSubscribed not implemented")
}
func (UnimplementedACLServiceServer) GetSubscription(context.Context, *PubkeyRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedACLServiceServer) ClaimAlias(context.Context, *ClaimAliasRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimAlias not implemented")
}
func (UnimplementedACLServiceServer) GetAliasByPubkey(context.Context, *PubkeyRequest) (*AliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAliasByPubkey not implemented")
}
func (UnimplementedACLServiceServer) GetPubkeyByAlias(context.Context, *AliasRequest) (*PubkeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPubkeyByAlias not implemented")
}
func (UnimplementedACLServiceServer) IsAliasTaken(context.Context, *AliasRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAliasTaken not implemented")
}
func (UnimplementedACLServiceServer) mustEmbedUnimplementedACLServiceServer() {}
func (UnimplementedACLServiceServer) testEmbeddedByValue()                    {}

// UnsafeACLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACLServiceServer will
// result in compilation errors.
type UnsafeACLServiceServer interface {
	mustEmbedUnimplementedACLServiceServer()
}

func RegisterACLServiceServer(s grpc.ServiceRegistrar, srv ACLServiceServer) {
	// If the following call panics, it indicates UnimplementedACLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ACLService_ServiceDesc, srv)
}

func _ACLService_GetAccessLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetAccessLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetAccessLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetAccessLevel(ctx, req.(*AccessLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_CheckPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).CheckPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_CheckPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).CheckPolicy(ctx, req.(*PolicyCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetACLInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetACLInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetACLInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetACLInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetMode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).Ready(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetThrottleDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThrottleDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetThrottleDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetThrottleDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetThrottleDelay(ctx, req.(*ThrottleDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_AddFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).AddFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_AddFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).AddFollow(ctx, req.(*AddFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetFollowedPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetFollowedPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetFollowedPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetFollowedPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetAdminRelays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetAdminRelays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetAdminRelays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetAdminRelays(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_BanPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).BanPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_BanPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).BanPubkey(ctx, req.(*BanPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnbanPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnbanPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnbanPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnbanPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListBannedPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListBannedPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListBannedPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListBannedPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_AllowPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).AllowPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_AllowPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).AllowPubkey(ctx, req.(*AllowPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_DisallowPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).DisallowPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_DisallowPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).DisallowPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListAllowedPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListAllowedPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListAllowedPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListAllowedPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_BanEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).BanEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_BanEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).BanEvent(ctx, req.(*BanEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnbanEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnbanEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnbanEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnbanEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListBannedEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListBannedEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListBannedEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListBannedEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_AllowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).AllowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_AllowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).AllowEvent(ctx, req.(*BanEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_DisallowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).DisallowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_DisallowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).DisallowEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListAllowedEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListAllowedEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListAllowedEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListAllowedEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_BlockIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).BlockIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_BlockIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).BlockIP(ctx, req.(*BlockIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnblockIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnblockIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnblockIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnblockIP(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListBlockedIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListBlockedIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListBlockedIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListBlockedIPs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_AllowKind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowKindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).AllowKind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_AllowKind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).AllowKind(ctx, req.(*AllowKindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_DisallowKind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).DisallowKind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_DisallowKind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).DisallowKind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListAllowedKinds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListAllowedKinds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListAllowedKinds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListAllowedKinds(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UpdatePeerAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeerAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UpdatePeerAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UpdatePeerAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UpdatePeerAdmins(ctx, req.(*UpdatePeerAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_TrustPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).TrustPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_TrustPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).TrustPubkey(ctx, req.(*TrustPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UntrustPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UntrustPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UntrustPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UntrustPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListTrustedPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListTrustedPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListTrustedPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListTrustedPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_BlacklistPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).BlacklistPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_BlacklistPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).BlacklistPubkey(ctx, req.(*BlacklistPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnblacklistPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnblacklistPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnblacklistPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnblacklistPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListBlacklistedPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListBlacklistedPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListBlacklistedPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListBlacklistedPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_MarkSpam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkSpamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).MarkSpam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_MarkSpam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).MarkSpam(ctx, req.(*MarkSpamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnmarkSpam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnmarkSpam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnmarkSpam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnmarkSpam(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListSpamEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListSpamEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListSpamEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListSpamEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_RateLimitCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).RateLimitCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_RateLimitCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).RateLimitCheck(ctx, req.(*RateLimitCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ProcessConfigEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ProcessConfigEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ProcessConfigEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ProcessConfigEvent(ctx, req.(*ConfigEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetCuratingConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetCuratingConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetCuratingConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetCuratingConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_IsCuratingConfigured_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).IsCuratingConfigured(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_IsCuratingConfigured_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).IsCuratingConfigured(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ListUnclassifiedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ListUnclassifiedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ListUnclassifiedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ListUnclassifiedUsers(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetEventsForPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetEventsForPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetEventsForPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetEventsForPubkey(ctx, req.(*GetEventsForPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_DeleteEventsForPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventsForPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).DeleteEventsForPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_DeleteEventsForPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).DeleteEventsForPubkey(ctx, req.(*DeleteEventsForPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ScanAllPubkeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ScanAllPubkeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ScanAllPubkeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ScanAllPubkeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_SubscribePubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).SubscribePubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_SubscribePubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).SubscribePubkey(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_UnsubscribePubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).UnsubscribePubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_UnsubscribePubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).UnsubscribePubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_IsSubscribed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).IsSubscribed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_IsSubscribed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).IsSubscribed(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetSubscription(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_ClaimAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).ClaimAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_ClaimAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).ClaimAlias(ctx, req.(*ClaimAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetAliasByPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetAliasByPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetAliasByPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetAliasByPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_GetPubkeyByAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).GetPubkeyByAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_GetPubkeyByAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).GetPubkeyByAlias(ctx, req.(*AliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACLService_IsAliasTaken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACLServiceServer).IsAliasTaken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACLService_IsAliasTaken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACLServiceServer).IsAliasTaken(ctx, req.(*AliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ACLService_ServiceDesc is the grpc.ServiceDesc for ACLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orlyacl.v1.ACLService",
	HandlerType: (*ACLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessLevel",
			Handler:    _ACLService_GetAccessLevel_Handler,
		},
		{
			MethodName: "CheckPolicy",
			Handler:    _ACLService_CheckPolicy_Handler,
		},
		{
			MethodName: "GetACLInfo",
			Handler:    _ACLService_GetACLInfo_Handler,
		},
		{
			MethodName: "GetMode",
			Handler:    _ACLService_GetMode_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _ACLService_Ready_Handler,
		},
		{
			MethodName: "GetThrottleDelay",
			Handler:    _ACLService_GetThrottleDelay_Handler,
		},
		{
			MethodName: "AddFollow",
			Handler:    _ACLService_AddFollow_Handler,
		},
		{
			MethodName: "GetFollowedPubkeys",
			Handler:    _ACLService_GetFollowedPubkeys_Handler,
		},
		{
			MethodName: "GetAdminRelays",
			Handler:    _ACLService_GetAdminRelays_Handler,
		},
		{
			MethodName: "BanPubkey",
			Handler:    _ACLService_BanPubkey_Handler,
		},
		{
			MethodName: "UnbanPubkey",
			Handler:    _ACLService_UnbanPubkey_Handler,
		},
		{
			MethodName: "ListBannedPubkeys",
			Handler:    _ACLService_ListBannedPubkeys_Handler,
		},
		{
			MethodName: "AllowPubkey",
			Handler:    _ACLService_AllowPubkey_Handler,
		},
		{
			MethodName: "DisallowPubkey",
			Handler:    _ACLService_DisallowPubkey_Handler,
		},
		{
			MethodName: "ListAllowedPubkeys",
			Handler:    _ACLService_ListAllowedPubkeys_Handler,
		},
		{
			MethodName: "BanEvent",
			Handler:    _ACLService_BanEvent_Handler,
		},
		{
			MethodName: "UnbanEvent",
			Handler:    _ACLService_UnbanEvent_Handler,
		},
		{
			MethodName: "ListBannedEvents",
			Handler:    _ACLService_ListBannedEvents_Handler,
		},
		{
			MethodName: "AllowEvent",
			Handler:    _ACLService_AllowEvent_Handler,
		},
		{
			MethodName: "DisallowEvent",
			Handler:    _ACLService_DisallowEvent_Handler,
		},
		{
			MethodName: "ListAllowedEvents",
			Handler:    _ACLService_ListAllowedEvents_Handler,
		},
		{
			MethodName: "BlockIP",
			Handler:    _ACLService_BlockIP_Handler,
		},
		{
			MethodName: "UnblockIP",
			Handler:    _ACLService_UnblockIP_Handler,
		},
		{
			MethodName: "ListBlockedIPs",
			Handler:    _ACLService_ListBlockedIPs_Handler,
		},
		{
			MethodName: "AllowKind",
			Handler:    _ACLService_AllowKind_Handler,
		},
		{
			MethodName: "DisallowKind",
			Handler:    _ACLService_DisallowKind_Handler,
		},
		{
			MethodName: "ListAllowedKinds",
			Handler:    _ACLService_ListAllowedKinds_Handler,
		},
		{
			MethodName: "UpdatePeerAdmins",
			Handler:    _ACLService_UpdatePeerAdmins_Handler,
		},
		{
			MethodName: "TrustPubkey",
			Handler:    _ACLService_TrustPubkey_Handler,
		},
		{
			MethodName: "UntrustPubkey",
			Handler:    _ACLService_UntrustPubkey_Handler,
		},
		{
			MethodName: "ListTrustedPubkeys",
			Handler:    _ACLService_ListTrustedPubkeys_Handler,
		},
		{
			MethodName: "BlacklistPubkey",
			Handler:    _ACLService_BlacklistPubkey_Handler,
		},
		{
			MethodName: "UnblacklistPubkey",
			Handler:    _ACLService_UnblacklistPubkey_Handler,
		},
		{
			MethodName: "ListBlacklistedPubkeys",
			Handler:    _ACLService_ListBlacklistedPubkeys_Handler,
		},
		{
			MethodName: "MarkSpam",
			Handler:    _ACLService_MarkSpam_Handler,
		},
		{
			MethodName: "UnmarkSpam",
			Handler:    _ACLService_UnmarkSpam_Handler,
		},
		{
			MethodName: "ListSpamEvents",
			Handler:    _ACLService_ListSpamEvents_Handler,
		},
		{
			MethodName: "RateLimitCheck",
			Handler:    _ACLService_RateLimitCheck_Handler,
		},
		{
			MethodName: "ProcessConfigEvent",
			Handler:    _ACLService_ProcessConfigEvent_Handler,
		},
		{
			MethodName: "GetCuratingConfig",
			Handler:    _ACLService_GetCuratingConfig_Handler,
		},
		{
			MethodName: "IsCuratingConfigured",
			Handler:    _ACLService_IsCuratingConfigured_Handler,
		},
		{
			MethodName: "ListUnclassifiedUsers",
			Handler:    _ACLService_ListUnclassifiedUsers_Handler,
		},
		{
			MethodName: "GetEventsForPubkey",
			Handler:    _ACLService_GetEventsForPubkey_Handler,
		},
		{
			MethodName: "DeleteEventsForPubkey",
			Handler:    _ACLService_DeleteEventsForPubkey_Handler,
		},
		{
			MethodName: "ScanAllPubkeys",
			Handler:    _ACLService_ScanAllPubkeys_Handler,
		},
		{
			MethodName: "SubscribePubkey",
			Handler:    _ACLService_SubscribePubkey_Handler,
		},
		{
			MethodName: "UnsubscribePubkey",
			Handler:    _ACLService_UnsubscribePubkey_Handler,
		},
		{
			MethodName: "IsSubscribed",
			Handler:    _ACLService_IsSubscribed_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _ACLService_GetSubscription_Handler,
		},
		{
			MethodName: "ClaimAlias",
			Handler:    _ACLService_ClaimAlias_Handler,
		},
		{
			MethodName: "GetAliasByPubkey",
			Handler:    _ACLService_GetAliasByPubkey_Handler,
		},
		{
			MethodName: "GetPubkeyByAlias",
			Handler:    _ACLService_GetPubkeyByAlias_Handler,
		},
		{
			MethodName: "IsAliasTaken",
			Handler:    _ACLService_IsAliasTaken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orlyacl/v1/acl.proto",
}
