// Package common/jsbridge/dom
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: dom.Body
export function Body() {
  return $rt.dom.Body();
}

// jsbridge: dom.CreateElement
export function CreateElement(tag) {
  return $rt.dom.CreateElement(tag);
}

// jsbridge: dom.CreateTextNode
export function CreateTextNode(text) {
  return $rt.dom.CreateTextNode(text);
}

// jsbridge: dom.GetElementById
export function GetElementById(id) {
  return $rt.dom.GetElementById(id);
}

// jsbridge: dom.QuerySelector
export function QuerySelector(sel) {
  return $rt.dom.QuerySelector(sel);
}

// jsbridge: dom.AppendChild
export function AppendChild(parent, child) {
  $rt.dom.AppendChild(parent, child);
}

// jsbridge: dom.RemoveChild
export function RemoveChild(parent, child) {
  $rt.dom.RemoveChild(parent, child);
}

// jsbridge: dom.SetAttribute
export function SetAttribute(el, name, value) {
  $rt.dom.SetAttribute(el, name, value);
}

// jsbridge: dom.SetTextContent
export function SetTextContent(el, text) {
  $rt.dom.SetTextContent(el, text);
}

// jsbridge: dom.SetInnerHTML
export function SetInnerHTML(el, html) {
  $rt.dom.SetInnerHTML(el, html);
}

// jsbridge: dom.SetStyle
export function SetStyle(el, prop, value) {
  $rt.dom.SetStyle(el, prop, value);
}

// jsbridge: dom.AddClass
export function AddClass(el, cls) {
  $rt.dom.AddClass(el, cls);
}

// jsbridge: dom.RemoveClass
export function RemoveClass(el, cls) {
  $rt.dom.RemoveClass(el, cls);
}

// jsbridge: dom.SetProperty
export function SetProperty(el, prop, value) {
  $rt.dom.SetProperty(el, prop, value);
}

// jsbridge: dom.GetProperty
export function GetProperty(el, prop) {
  return $rt.dom.GetProperty(el, prop);
}

// jsbridge: dom.RegisterCallback
export function RegisterCallback(fn) {
  return $rt.dom.RegisterCallback(fn);
}

// jsbridge: dom.ReleaseCallback
export function ReleaseCallback(id) {
  $rt.dom.ReleaseCallback(id);
}

// jsbridge: dom.AddEventListener
export function AddEventListener(el, event, callbackId) {
  $rt.dom.AddEventListener(el, event, callbackId);
}

// jsbridge: dom.RemoveEventListener
export function RemoveEventListener(el, event, callbackId) {
  $rt.dom.RemoveEventListener(el, event, callbackId);
}

// jsbridge: dom.RequestAnimationFrame
export function RequestAnimationFrame(fn) {
  $rt.dom.RequestAnimationFrame(fn);
}

// jsbridge: dom.SetTimeout
export function SetTimeout(fn, ms) {
  return $rt.dom.SetTimeout(fn, ms);
}

// jsbridge: dom.FirstChild
export function FirstChild(el) {
  return $rt.dom.FirstChild(el);
}

// jsbridge: dom.InsertBefore
export function InsertBefore(parent, newChild, refChild) {
  $rt.dom.InsertBefore(parent, newChild, refChild);
}

// jsbridge: dom.ReleaseElement
export function ReleaseElement(el) {
  $rt.dom.ReleaseElement(el);
}

