// Package common/crypto/sha256
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables
export let k = { $value: $rt.builtin.makeSlice(64, 64, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let init0 = { $value: $rt.builtin.makeSlice(8, 8, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };

$rt.types.registerType('common/crypto/sha256.digest', {
  id: 'common/crypto/sha256.digest',
  kind: 'struct',
  methods: new Map(),
  fields: [
    { name: 'h', type: '[8]uint32', tag: '', embedded: false },
    { name: 'buf', type: '[64]byte', tag: '', embedded: false },
    { name: 'len', type: 'int', tag: '', embedded: false },
    { name: 'tot', type: 'uint64', tag: '', embedded: false },
  ],
  zero: () => ({ h: $rt.builtin.makeSlice(8, 8, 0), buf: $rt.builtin.makeSlice(64, 64, 0), len: 0, tot: 0 }),
});
export function init() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62, $t62_63, $t63_64, $t64_65, $t65_66, $t66_67, $t67_68, $t68_69, $t69_70, $t70_71, $t71_72;
  $t0_1 = k.$get().addr(0);
  $t1_2 = k.$get().addr(1);
  $t2_3 = k.$get().addr(2);
  $t3_4 = k.$get().addr(3);
  $t4_5 = k.$get().addr(4);
  $t5_6 = k.$get().addr(5);
  $t6_7 = k.$get().addr(6);
  $t7_8 = k.$get().addr(7);
  $t8_9 = k.$get().addr(8);
  $t9_10 = k.$get().addr(9);
  $t10_11 = k.$get().addr(10);
  $t11_12 = k.$get().addr(11);
  $t12_13 = k.$get().addr(12);
  $t13_14 = k.$get().addr(13);
  $t14_15 = k.$get().addr(14);
  $t15_16 = k.$get().addr(15);
  $t16_17 = k.$get().addr(16);
  $t17_18 = k.$get().addr(17);
  $t18_19 = k.$get().addr(18);
  $t19_20 = k.$get().addr(19);
  $t20_21 = k.$get().addr(20);
  $t21_22 = k.$get().addr(21);
  $t22_23 = k.$get().addr(22);
  $t23_24 = k.$get().addr(23);
  $t24_25 = k.$get().addr(24);
  $t25_26 = k.$get().addr(25);
  $t26_27 = k.$get().addr(26);
  $t27_28 = k.$get().addr(27);
  $t28_29 = k.$get().addr(28);
  $t29_30 = k.$get().addr(29);
  $t30_31 = k.$get().addr(30);
  $t31_32 = k.$get().addr(31);
  $t32_33 = k.$get().addr(32);
  $t33_34 = k.$get().addr(33);
  $t34_35 = k.$get().addr(34);
  $t35_36 = k.$get().addr(35);
  $t36_37 = k.$get().addr(36);
  $t37_38 = k.$get().addr(37);
  $t38_39 = k.$get().addr(38);
  $t39_40 = k.$get().addr(39);
  $t40_41 = k.$get().addr(40);
  $t41_42 = k.$get().addr(41);
  $t42_43 = k.$get().addr(42);
  $t43_44 = k.$get().addr(43);
  $t44_45 = k.$get().addr(44);
  $t45_46 = k.$get().addr(45);
  $t46_47 = k.$get().addr(46);
  $t47_48 = k.$get().addr(47);
  $t48_49 = k.$get().addr(48);
  $t49_50 = k.$get().addr(49);
  $t50_51 = k.$get().addr(50);
  $t51_52 = k.$get().addr(51);
  $t52_53 = k.$get().addr(52);
  $t53_54 = k.$get().addr(53);
  $t54_55 = k.$get().addr(54);
  $t55_56 = k.$get().addr(55);
  $t56_57 = k.$get().addr(56);
  $t57_58 = k.$get().addr(57);
  $t58_59 = k.$get().addr(58);
  $t59_60 = k.$get().addr(59);
  $t60_61 = k.$get().addr(60);
  $t61_62 = k.$get().addr(61);
  $t62_63 = k.$get().addr(62);
  $t63_64 = k.$get().addr(63);
  $t0_1.$set(1116352408);
  $t1_2.$set(1899447441);
  $t2_3.$set(3049323471);
  $t3_4.$set(3921009573);
  $t4_5.$set(961987163);
  $t5_6.$set(1508970993);
  $t6_7.$set(2453635748);
  $t7_8.$set(2870763221);
  $t8_9.$set(3624381080);
  $t9_10.$set(310598401);
  $t10_11.$set(607225278);
  $t11_12.$set(1426881987);
  $t12_13.$set(1925078388);
  $t13_14.$set(2162078206);
  $t14_15.$set(2614888103);
  $t15_16.$set(3248222580);
  $t16_17.$set(3835390401);
  $t17_18.$set(4022224774);
  $t18_19.$set(264347078);
  $t19_20.$set(604807628);
  $t20_21.$set(770255983);
  $t21_22.$set(1249150122);
  $t22_23.$set(1555081692);
  $t23_24.$set(1996064986);
  $t24_25.$set(2554220882);
  $t25_26.$set(2821834349);
  $t26_27.$set(2952996808);
  $t27_28.$set(3210313671);
  $t28_29.$set(3336571891);
  $t29_30.$set(3584528711);
  $t30_31.$set(113926993);
  $t31_32.$set(338241895);
  $t32_33.$set(666307205);
  $t33_34.$set(773529912);
  $t34_35.$set(1294757372);
  $t35_36.$set(1396182291);
  $t36_37.$set(1695183700);
  $t37_38.$set(1986661051);
  $t38_39.$set(2177026350);
  $t39_40.$set(2456956037);
  $t40_41.$set(2730485921);
  $t41_42.$set(2820302411);
  $t42_43.$set(3259730800);
  $t43_44.$set(3345764771);
  $t44_45.$set(3516065817);
  $t45_46.$set(3600352804);
  $t46_47.$set(4094571909);
  $t47_48.$set(275423344);
  $t48_49.$set(430227734);
  $t49_50.$set(506948616);
  $t50_51.$set(659060556);
  $t51_52.$set(883997877);
  $t52_53.$set(958139571);
  $t53_54.$set(1322822218);
  $t54_55.$set(1537002063);
  $t55_56.$set(1747873779);
  $t56_57.$set(1955562222);
  $t57_58.$set(2024104815);
  $t58_59.$set(2227730452);
  $t59_60.$set(2361852424);
  $t60_61.$set(2428436474);
  $t61_62.$set(2756734187);
  $t62_63.$set(3204031479);
  $t63_64.$set(3329325298);
  $t64_65 = init0.$get().addr(0);
  $t65_66 = init0.$get().addr(1);
  $t66_67 = init0.$get().addr(2);
  $t67_68 = init0.$get().addr(3);
  $t68_69 = init0.$get().addr(4);
  $t69_70 = init0.$get().addr(5);
  $t70_71 = init0.$get().addr(6);
  $t71_72 = init0.$get().addr(7);
  $t64_65.$set(1779033703);
  $t65_66.$set(3144134277);
  $t66_67.$set(1013904242);
  $t67_68.$set(2773480762);
  $t68_69.$set(1359893119);
  $t69_70.$set(2600822924);
  $t70_71.$set(528734635);
  $t71_72.$set(1541459225);
  return;
}

export function Sum(data) {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  $t0_1 = { $value: { h: $rt.builtin.makeSlice(8, 8, 0), buf: $rt.builtin.makeSlice(64, 64, 0), len: 0, tot: 0 }, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = digest$Reset($t0_1);
  $t2_3 = digest$Write($t0_1, data);
  $t3_4 = digest$Sum($t0_1);
  return $t3_4;
}

export function SumHex(data) {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  $t0_1 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = Sum(data);
  $t0_1.$set($rt.builtin.cloneValue($t1_2));
  $t2_3 = $rt.builtin.sliceSlice($t0_1.$get(), undefined, undefined, undefined);
  $t3_4 = bytesToHex($t2_3);
  return $t3_4;
}

export function block(h, data) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62, $t62_63, $t63_64, $t64_65, $t65_66, $t66_67, $t67_68, $t68_69, $t69_70, $t70_71, $t71_72, $t72_73, $t73_74, $t74_75, $t75_76, $t76_77, $t77_78, $t78_79, $t79_80, $t80_81, $t81_82, $t82_83, $t83_84, $t84_85, $t85_86, $t86_87, $t87_88, $t88_89, $t89_90, $t90_91, $t91_92, $t92_93, $t93_94, $t94_95, $t95_96, $t96_97, $t97_98, $t98_99, $t99_100, $t100_101, $t101_102, $t102_103, $t103_104, $t104_105, $t105_106, $t106_107, $t107_108, $t108_109, $t109_110, $t110_111, $t111_112, $t112_113, $t113_114, $t114_115, $t115_116, $t116_117, $t117_118, $t118_119, $t119_120, $t120_121, $t121_122, $t122_123, $t123_124, $t124_125, $t125_126, $t126_127, $t127_128, $t128_129, $t129_130, $t130_131, $t131_132, $t132_133, $t133_134, $t134_135, $t135_136, $t136_137, $t137_138, $t138_139, $t139_140, $t140_141, $t141_142, $t142_143, $t143_144, $t144_145, $t145_146, $t146_147, $t147_148, $t148_149, $t149_150, $t150_151, $t151_152, $t152_153, $t153_154, $t154_155, $t155_156, $t156_157;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = { $value: $rt.builtin.makeSlice(64, 64, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t1_2 = 0;
        $block = 1; break;
        break;
      }
      case 1: {
        $t2_3 = ($t1_2 < 16);
        if ($t2_3) {
          $block = 2; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 2: {
        $t3_4 = ($t1_2 * 4);
        $t4_5 = data.addr($t3_4);
        $t5_6 = $t4_5.$get();
        $t6_7 = ($t5_6 >>> 0);
        $t7_8 = (($t6_7 << 24) >>> 0);
        $t8_9 = ($t3_4 + 1);
        $t9_10 = data.addr($t8_9);
        $t10_11 = $t9_10.$get();
        $t11_12 = ($t10_11 >>> 0);
        $t12_13 = (($t11_12 << 16) >>> 0);
        $t13_14 = (($t7_8 | $t12_13) >>> 0);
        $t14_15 = ($t3_4 + 2);
        $t15_16 = data.addr($t14_15);
        $t16_17 = $t15_16.$get();
        $t17_18 = ($t16_17 >>> 0);
        $t18_19 = (($t17_18 << 8) >>> 0);
        $t19_20 = (($t13_14 | $t18_19) >>> 0);
        $t20_21 = ($t3_4 + 3);
        $t21_22 = data.addr($t20_21);
        $t22_23 = $t21_22.$get();
        $t23_24 = ($t22_23 >>> 0);
        $t24_25 = (($t19_20 | $t23_24) >>> 0);
        $t25_26 = $t0_1.$get().addr($t1_2);
        $t25_26.$set($t24_25);
        $t26_27 = ($t1_2 + 1);
        $t1_2 = $t26_27;
        $block = 1; break;
        break;
      }
      case 3: {
        $t27_28 = 16;
        $block = 4; break;
        break;
      }
      case 4: {
        $t28_29 = ($t27_28 < 64);
        if ($t28_29) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 5: {
        $t29_30 = ($t27_28 - 15);
        $t30_31 = $t0_1.$get().addr($t29_30);
        $t31_32 = $t30_31.$get();
        $t32_33 = rotr($t31_32, 7);
        $t33_34 = ($t27_28 - 15);
        $t34_35 = $t0_1.$get().addr($t33_34);
        $t35_36 = $t34_35.$get();
        $t36_37 = rotr($t35_36, 18);
        $t37_38 = (($t32_33 ^ $t36_37) >>> 0);
        $t38_39 = ($t27_28 - 15);
        $t39_40 = $t0_1.$get().addr($t38_39);
        $t40_41 = $t39_40.$get();
        $t41_42 = ($t40_41 >>> 3);
        $t42_43 = (($t37_38 ^ $t41_42) >>> 0);
        $t43_44 = ($t27_28 - 2);
        $t44_45 = $t0_1.$get().addr($t43_44);
        $t45_46 = $t44_45.$get();
        $t46_47 = rotr($t45_46, 17);
        $t47_48 = ($t27_28 - 2);
        $t48_49 = $t0_1.$get().addr($t47_48);
        $t49_50 = $t48_49.$get();
        $t50_51 = rotr($t49_50, 19);
        $t51_52 = (($t46_47 ^ $t50_51) >>> 0);
        $t52_53 = ($t27_28 - 2);
        $t53_54 = $t0_1.$get().addr($t52_53);
        $t54_55 = $t53_54.$get();
        $t55_56 = ($t54_55 >>> 10);
        $t56_57 = (($t51_52 ^ $t55_56) >>> 0);
        $t57_58 = ($t27_28 - 16);
        $t58_59 = $t0_1.$get().addr($t57_58);
        $t59_60 = $t58_59.$get();
        $t60_61 = (($t59_60 + $t42_43) >>> 0);
        $t61_62 = ($t27_28 - 7);
        $t62_63 = $t0_1.$get().addr($t61_62);
        $t63_64 = $t62_63.$get();
        $t64_65 = (($t60_61 + $t63_64) >>> 0);
        $t65_66 = (($t64_65 + $t56_57) >>> 0);
        $t66_67 = $t0_1.$get().addr($t27_28);
        $t66_67.$set($t65_66);
        $t67_68 = ($t27_28 + 1);
        $t27_28 = $t67_68;
        $block = 4; break;
        break;
      }
      case 6: {
        $t68_69 = h.$get().addr(0);
        $t69_70 = $t68_69.$get();
        $t70_71 = h.$get().addr(1);
        $t71_72 = $t70_71.$get();
        $t72_73 = h.$get().addr(2);
        $t73_74 = $t72_73.$get();
        $t74_75 = h.$get().addr(3);
        $t75_76 = $t74_75.$get();
        $t76_77 = h.$get().addr(4);
        $t77_78 = $t76_77.$get();
        $t78_79 = h.$get().addr(5);
        $t79_80 = $t78_79.$get();
        $t80_81 = h.$get().addr(6);
        $t81_82 = $t80_81.$get();
        $t82_83 = h.$get().addr(7);
        $t83_84 = $t82_83.$get();
        $t84_85 = $t69_70;
        $t85_86 = $t71_72;
        $t86_87 = $t73_74;
        $t87_88 = $t75_76;
        $t88_89 = $t77_78;
        $t89_90 = $t79_80;
        $t90_91 = $t81_82;
        $t91_92 = $t83_84;
        $t92_93 = 0;
        $block = 7; break;
        break;
      }
      case 7: {
        $t93_94 = ($t92_93 < 64);
        if ($t93_94) {
          $block = 8; break;
        }
        else {
          $block = 9; break;
        }
        break;
      }
      case 8: {
        $t94_95 = rotr($t88_89, 6);
        $t95_96 = rotr($t88_89, 11);
        $t96_97 = (($t94_95 ^ $t95_96) >>> 0);
        $t97_98 = rotr($t88_89, 25);
        $t98_99 = (($t96_97 ^ $t97_98) >>> 0);
        $t99_100 = (($t88_89 & $t89_90) >>> 0);
        $t100_101 = ~$t88_89;
        $t101_102 = (($t100_101 & $t90_91) >>> 0);
        $t102_103 = (($t99_100 ^ $t101_102) >>> 0);
        $t103_104 = (($t91_92 + $t98_99) >>> 0);
        $t104_105 = (($t103_104 + $t102_103) >>> 0);
        $t105_106 = k.$get().addr($t92_93);
        $t106_107 = $t105_106.$get();
        $t107_108 = (($t104_105 + $t106_107) >>> 0);
        $t108_109 = $t0_1.$get().addr($t92_93);
        $t109_110 = $t108_109.$get();
        $t110_111 = (($t107_108 + $t109_110) >>> 0);
        $t111_112 = rotr($t84_85, 2);
        $t112_113 = rotr($t84_85, 13);
        $t113_114 = (($t111_112 ^ $t112_113) >>> 0);
        $t114_115 = rotr($t84_85, 22);
        $t115_116 = (($t113_114 ^ $t114_115) >>> 0);
        $t116_117 = (($t84_85 & $t85_86) >>> 0);
        $t117_118 = (($t84_85 & $t86_87) >>> 0);
        $t118_119 = (($t116_117 ^ $t117_118) >>> 0);
        $t119_120 = (($t85_86 & $t86_87) >>> 0);
        $t120_121 = (($t118_119 ^ $t119_120) >>> 0);
        $t121_122 = (($t115_116 + $t120_121) >>> 0);
        $t122_123 = (($t87_88 + $t110_111) >>> 0);
        $t123_124 = (($t110_111 + $t121_122) >>> 0);
        $t124_125 = ($t92_93 + 1);
        let $phi0 = $t123_124;
        let $phi1 = $t84_85;
        let $phi2 = $t85_86;
        let $phi3 = $t86_87;
        let $phi4 = $t122_123;
        let $phi5 = $t88_89;
        let $phi6 = $t89_90;
        let $phi7 = $t90_91;
        let $phi8 = $t124_125;
        $t84_85 = $phi0;
        $t85_86 = $phi1;
        $t86_87 = $phi2;
        $t87_88 = $phi3;
        $t88_89 = $phi4;
        $t89_90 = $phi5;
        $t90_91 = $phi6;
        $t91_92 = $phi7;
        $t92_93 = $phi8;
        $block = 7; break;
        break;
      }
      case 9: {
        $t125_126 = h.$get().addr(0);
        $t126_127 = $t125_126.$get();
        $t127_128 = (($t126_127 + $t84_85) >>> 0);
        $t128_129 = h.$get().addr(0);
        $t128_129.$set($t127_128);
        $t129_130 = h.$get().addr(1);
        $t130_131 = $t129_130.$get();
        $t131_132 = (($t130_131 + $t85_86) >>> 0);
        $t132_133 = h.$get().addr(1);
        $t132_133.$set($t131_132);
        $t133_134 = h.$get().addr(2);
        $t134_135 = $t133_134.$get();
        $t135_136 = (($t134_135 + $t86_87) >>> 0);
        $t136_137 = h.$get().addr(2);
        $t136_137.$set($t135_136);
        $t137_138 = h.$get().addr(3);
        $t138_139 = $t137_138.$get();
        $t139_140 = (($t138_139 + $t87_88) >>> 0);
        $t140_141 = h.$get().addr(3);
        $t140_141.$set($t139_140);
        $t141_142 = h.$get().addr(4);
        $t142_143 = $t141_142.$get();
        $t143_144 = (($t142_143 + $t88_89) >>> 0);
        $t144_145 = h.$get().addr(4);
        $t144_145.$set($t143_144);
        $t145_146 = h.$get().addr(5);
        $t146_147 = $t145_146.$get();
        $t147_148 = (($t146_147 + $t89_90) >>> 0);
        $t148_149 = h.$get().addr(5);
        $t148_149.$set($t147_148);
        $t149_150 = h.$get().addr(6);
        $t150_151 = $t149_150.$get();
        $t151_152 = (($t150_151 + $t90_91) >>> 0);
        $t152_153 = h.$get().addr(6);
        $t152_153.$set($t151_152);
        $t153_154 = h.$get().addr(7);
        $t154_155 = $t153_154.$get();
        $t155_156 = (($t154_155 + $t91_92) >>> 0);
        $t156_157 = h.$get().addr(7);
        $t156_157.$set($t155_156);
        return;
        break;
      }
    }
  }
}

export function rotr(x, n) {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  $t0_1 = (x >>> n);
  $t1_2 = (32 - n);
  $t2_3 = ((x << $t1_2) >>> 0);
  $t3_4 = (($t0_1 | $t2_3) >>> 0);
  return $t3_4;
}

export function bytesToHex(b) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = $rt.builtin.len(b);
        $t1_2 = ($t0_1 * 2);
        $t2_3 = $rt.builtin.makeSlice($t1_2, $t1_2, 0);
        $t3_4 = $rt.builtin.len(b);
        $t4_5 = -1;
        $block = 1; break;
        break;
      }
      case 1: {
        $t5_6 = ($t4_5 + 1);
        $t6_7 = ($t5_6 < $t3_4);
        if ($t6_7) {
          $block = 2; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 2: {
        $t7_8 = b.addr($t5_6);
        $t8_9 = $t7_8.$get();
        $t9_10 = ($t5_6 * 2);
        $t10_11 = (($t8_9 & 0xFF) >> 4);
        $rt.runtime.boundsCheck($t10_11, '0123456789abcdef'.length);
        $t11_12 = '0123456789abcdef'.charCodeAt($t10_11);
        $t12_13 = $t2_3.addr($t9_10);
        $t12_13.$set($t11_12);
        $t13_14 = ($t5_6 * 2);
        $t14_15 = ($t13_14 + 1);
        $t15_16 = ($t8_9 & 15);
        $rt.runtime.boundsCheck($t15_16, '0123456789abcdef'.length);
        $t16_17 = '0123456789abcdef'.charCodeAt($t15_16);
        $t17_18 = $t2_3.addr($t14_15);
        $t17_18.$set($t16_17);
        $t4_5 = $t5_6;
        $block = 1; break;
        break;
      }
      case 3: {
        $t18_19 = $rt.builtin.bytesToString($t2_3);
        return $t18_19;
        break;
      }
    }
  }
}

export function digest$Reset(d) {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  $t0_1 = init0.$get();
  $t1_2 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
  $t1_2.$set($rt.builtin.cloneValue($t0_1));
  $t2_3 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
  $t2_3.$set(0);
  $t3_4 = { $get() { return d.$get().tot; }, $set(v) { const obj = d.$get(); obj.tot = v; d.$set(obj); } };
  $t3_4.$set(0);
  return;
}

$rt.types.getType('common/crypto/sha256.digest')?.methods?.set('Reset', digest$Reset);
export function digest$Sum(d) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62, $t62_63, $t63_64, $t64_65, $t65_66, $t66_67, $t67_68, $t68_69, $t69_70, $t70_71, $t71_72, $t72_73, $t73_74, $t74_75, $t75_76, $t76_77, $t77_78, $t78_79;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = { $value: $rt.builtin.makeSlice(64, 64, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t1_2 = $t0_1.$get().addr(0);
        $t1_2.$set(128);
        $t2_3 = { $get() { return d.$get().tot; }, $set(v) { const obj = d.$get(); obj.tot = v; d.$set(obj); } };
        $t3_4 = $t2_3.$get();
        $t4_5 = ($t3_4 * 8);
        $t5_6 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t6_7 = $t5_6.$get();
        $t7_8 = ($t6_7 < 56);
        if ($t7_8) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 1: {
        $t8_9 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t9_10 = $t8_9.$get();
        $t10_11 = (56 - $t9_10);
        $t11_12 = $rt.builtin.sliceSlice($t0_1.$get(), undefined, $t10_11, undefined);
        $t12_13 = digest$Write(d, $t11_12);
        $block = 2; break;
        break;
      }
      case 2: {
        $t13_14 = { $value: $rt.builtin.makeSlice(8, 8, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t14_15 = Math.trunc($t4_5 / (2 ** 56));
        $t15_16 = ($t14_15 & 0xFF);
        $t16_17 = $t13_14.$get().addr(0);
        $t16_17.$set($t15_16);
        $t17_18 = Math.trunc($t4_5 / (2 ** 48));
        $t18_19 = ($t17_18 & 0xFF);
        $t19_20 = $t13_14.$get().addr(1);
        $t19_20.$set($t18_19);
        $t20_21 = Math.trunc($t4_5 / (2 ** 40));
        $t21_22 = ($t20_21 & 0xFF);
        $t22_23 = $t13_14.$get().addr(2);
        $t22_23.$set($t21_22);
        $t23_24 = Math.trunc($t4_5 / (2 ** 32));
        $t24_25 = ($t23_24 & 0xFF);
        $t25_26 = $t13_14.$get().addr(3);
        $t25_26.$set($t24_25);
        $t26_27 = Math.trunc($t4_5 / (2 ** 24));
        $t27_28 = ($t26_27 & 0xFF);
        $t28_29 = $t13_14.$get().addr(4);
        $t28_29.$set($t27_28);
        $t29_30 = Math.trunc($t4_5 / (2 ** 16));
        $t30_31 = ($t29_30 & 0xFF);
        $t31_32 = $t13_14.$get().addr(5);
        $t31_32.$set($t30_31);
        $t32_33 = Math.trunc($t4_5 / (2 ** 8));
        $t33_34 = ($t32_33 & 0xFF);
        $t34_35 = $t13_14.$get().addr(6);
        $t34_35.$set($t33_34);
        $t35_36 = ($t4_5 & 0xFF);
        $t36_37 = $t13_14.$get().addr(7);
        $t36_37.$set($t35_36);
        $t37_38 = $rt.builtin.sliceSlice($t13_14.$get(), undefined, undefined, undefined);
        $t38_39 = digest$Write(d, $t37_38);
        $t39_40 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t45_46 = 0;
        $block = 4; break;
        break;
      }
      case 3: {
        $t40_41 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t41_42 = $t40_41.$get();
        $t42_43 = (120 - $t41_42);
        $t43_44 = $rt.builtin.sliceSlice($t0_1.$get(), undefined, $t42_43, undefined);
        $t44_45 = digest$Write(d, $t43_44);
        $block = 2; break;
        break;
      }
      case 4: {
        $t46_47 = ($t45_46 < 8);
        if ($t46_47) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 5: {
        $t47_48 = ($t45_46 * 4);
        $t48_49 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t49_50 = $t48_49.$get().addr($t45_46);
        $t50_51 = $t49_50.$get();
        $t51_52 = ($t50_51 >>> 24);
        $t52_53 = ($t51_52 & 0xFF);
        $t53_54 = $t39_40.$get().addr($t47_48);
        $t53_54.$set($t52_53);
        $t54_55 = ($t45_46 * 4);
        $t55_56 = ($t54_55 + 1);
        $t56_57 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t57_58 = $t56_57.$get().addr($t45_46);
        $t58_59 = $t57_58.$get();
        $t59_60 = ($t58_59 >>> 16);
        $t60_61 = ($t59_60 & 0xFF);
        $t61_62 = $t39_40.$get().addr($t55_56);
        $t61_62.$set($t60_61);
        $t62_63 = ($t45_46 * 4);
        $t63_64 = ($t62_63 + 2);
        $t64_65 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t65_66 = $t64_65.$get().addr($t45_46);
        $t66_67 = $t65_66.$get();
        $t67_68 = ($t66_67 >>> 8);
        $t68_69 = ($t67_68 & 0xFF);
        $t69_70 = $t39_40.$get().addr($t63_64);
        $t69_70.$set($t68_69);
        $t70_71 = ($t45_46 * 4);
        $t71_72 = ($t70_71 + 3);
        $t72_73 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t73_74 = $t72_73.$get().addr($t45_46);
        $t74_75 = $t73_74.$get();
        $t75_76 = ($t74_75 & 0xFF);
        $t76_77 = $t39_40.$get().addr($t71_72);
        $t76_77.$set($t75_76);
        $t77_78 = ($t45_46 + 1);
        $t45_46 = $t77_78;
        $block = 4; break;
        break;
      }
      case 6: {
        $t78_79 = $t39_40.$get();
        return $t78_79;
        break;
      }
    }
  }
}

$rt.types.getType('common/crypto/sha256.digest')?.methods?.set('Sum', digest$Sum);
export function digest$Write(d, p) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = $rt.builtin.len(p);
        $t1_2 = $t0_1;
        $t2_3 = { $get() { return d.$get().tot; }, $set(v) { const obj = d.$get(); obj.tot = v; d.$set(obj); } };
        $t3_4 = $t2_3.$get();
        $t4_5 = ($t3_4 + $t1_2);
        $t5_6 = { $get() { return d.$get().tot; }, $set(v) { const obj = d.$get(); obj.tot = v; d.$set(obj); } };
        $t5_6.$set($t4_5);
        $t6_7 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t7_8 = $t6_7.$get();
        $t8_9 = ($t7_8 > 0);
        if ($t8_9) {
          $block = 1; break;
        }
        else {
          $t33_34 = p;
          $block = 5; break;
        }
        break;
      }
      case 1: {
        $t9_10 = { $get() { return d.$get().buf; }, $set(v) { const obj = d.$get(); obj.buf = v; d.$set(obj); } };
        $t10_11 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t11_12 = $t10_11.$get();
        $t12_13 = $rt.builtin.sliceSlice($t9_10.$get(), $t11_12, undefined, undefined);
        $t13_14 = $rt.builtin.copy($t12_13, p);
        $t14_15 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t15_16 = $t14_15.$get();
        $t16_17 = ($t15_16 + $t13_14);
        $t17_18 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t17_18.$set($t16_17);
        $t18_19 = $rt.builtin.sliceSlice(p, $t13_14, undefined, undefined);
        $t19_20 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t20_21 = $t19_20.$get();
        $t21_22 = ($t20_21 === 64);
        if ($t21_22) {
          $block = 2; break;
        }
        else {
          $t33_34 = $t18_19;
          $block = 5; break;
        }
        break;
      }
      case 2: {
        $t22_23 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t23_24 = { $get() { return d.$get().buf; }, $set(v) { const obj = d.$get(); obj.buf = v; d.$set(obj); } };
        $t24_25 = $rt.builtin.sliceSlice($t23_24.$get(), undefined, undefined, undefined);
        $t25_26 = block($t22_23, $t24_25);
        $t26_27 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t26_27.$set(0);
        $t33_34 = $t18_19;
        $block = 5; break;
        break;
      }
      case 3: {
        $t27_28 = { $get() { return d.$get().h; }, $set(v) { const obj = d.$get(); obj.h = v; d.$set(obj); } };
        $t28_29 = $rt.builtin.sliceSlice($t33_34, undefined, 64, undefined);
        $t29_30 = block($t27_28, $t28_29);
        $t30_31 = $rt.builtin.sliceSlice($t33_34, 64, undefined, undefined);
        $t33_34 = $t30_31;
        $block = 5; break;
        break;
      }
      case 4: {
        $t31_32 = $rt.builtin.len($t33_34);
        $t32_33 = ($t31_32 > 0);
        if ($t32_33) {
          $block = 6; break;
        }
        else {
          $block = 7; break;
        }
        break;
      }
      case 5: {
        $t34_35 = $rt.builtin.len($t33_34);
        $t35_36 = ($t34_35 >= 64);
        if ($t35_36) {
          $block = 3; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 6: {
        $t36_37 = { $get() { return d.$get().buf; }, $set(v) { const obj = d.$get(); obj.buf = v; d.$set(obj); } };
        $t37_38 = $rt.builtin.sliceSlice($t36_37.$get(), undefined, undefined, undefined);
        $t38_39 = $rt.builtin.copy($t37_38, $t33_34);
        $t39_40 = { $get() { return d.$get().len; }, $set(v) { const obj = d.$get(); obj.len = v; d.$set(obj); } };
        $t39_40.$set($t38_39);
        $block = 7; break;
        break;
      }
      case 7: {
        return;
        break;
      }
    }
  }
}

$rt.types.getType('common/crypto/sha256.digest')?.methods?.set('Write', digest$Write);
