// Package common/jsbridge/localstorage
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: localstorage.GetItem
export function GetItem(key) {
  return $rt.localstorage.GetItem(key);
}

// jsbridge: localstorage.SetItem
export function SetItem(key, value) {
  $rt.localstorage.SetItem(key, value);
}

// jsbridge: localstorage.RemoveItem
export function RemoveItem(key) {
  $rt.localstorage.RemoveItem(key);
}

