// Package common/jsbridge/sw
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: sw.OnInstall
export function OnInstall(fn) {
  $rt.sw.OnInstall(fn);
}

// jsbridge: sw.OnActivate
export function OnActivate(fn) {
  $rt.sw.OnActivate(fn);
}

// jsbridge: sw.OnFetch
export function OnFetch(fn) {
  $rt.sw.OnFetch(fn);
}

// jsbridge: sw.OnMessage
export function OnMessage(fn) {
  $rt.sw.OnMessage(fn);
}

// jsbridge: sw.WaitUntil
export function WaitUntil(event, fn) {
  $rt.sw.WaitUntil(event, fn);
}

// jsbridge: sw.RespondWith
export function RespondWith(event, resp) {
  $rt.sw.RespondWith(event, resp);
}

// jsbridge: sw.RespondWithNetwork
export function RespondWithNetwork(event) {
  $rt.sw.RespondWithNetwork(event);
}

// jsbridge: sw.RespondWithCacheFirst
export function RespondWithCacheFirst(event) {
  $rt.sw.RespondWithCacheFirst(event);
}

// jsbridge: sw.GetRequestURL
export function GetRequestURL(event) {
  return $rt.sw.GetRequestURL(event);
}

// jsbridge: sw.GetRequestPath
export function GetRequestPath(event) {
  return $rt.sw.GetRequestPath(event);
}

// jsbridge: sw.GetMessageData
export function GetMessageData(event) {
  return $rt.sw.GetMessageData(event);
}

// jsbridge: sw.GetMessageClientID
export function GetMessageClientID(event) {
  return $rt.sw.GetMessageClientID(event);
}

// jsbridge: sw.Origin
export function Origin() {
  return $rt.sw.Origin();
}

// jsbridge: sw.SkipWaiting
export function SkipWaiting() {
  $rt.sw.SkipWaiting();
}

// jsbridge: sw.ClaimClients
export function ClaimClients(done) {
  $rt.sw.ClaimClients(done);
}

// jsbridge: sw.MatchClients
export function MatchClients(fn) {
  $rt.sw.MatchClients(fn);
}

// jsbridge: sw.PostMessage
export function PostMessage(client, msg) {
  $rt.sw.PostMessage(client, msg);
}

// jsbridge: sw.PostMessageJSON
export function PostMessageJSON(client, json) {
  $rt.sw.PostMessageJSON(client, json);
}

// jsbridge: sw.GetClientByID
export function GetClientByID(id, fn) {
  $rt.sw.GetClientByID(id, fn);
}

// jsbridge: sw.Navigate
export function Navigate(client, url) {
  $rt.sw.Navigate(client, url);
}

// jsbridge: sw.CacheOpen
export function CacheOpen(name, fn) {
  $rt.sw.CacheOpen(name, fn);
}

// jsbridge: sw.CacheAddAll
export function CacheAddAll(cache, urls, done) {
  $rt.sw.CacheAddAll(cache, urls, done);
}

// jsbridge: sw.CachePut
export function CachePut(cache, url, resp, done) {
  $rt.sw.CachePut(cache, url, resp, done);
}

// jsbridge: sw.CacheMatch
export function CacheMatch(url, fn) {
  $rt.sw.CacheMatch(url, fn);
}

// jsbridge: sw.CacheDelete
export function CacheDelete(name, done) {
  $rt.sw.CacheDelete(name, done);
}

// jsbridge: sw.Fetch
export function Fetch(url, fn) {
  $rt.sw.Fetch(url, fn);
}

// jsbridge: sw.ResponseOK
export function ResponseOK(resp) {
  return $rt.sw.ResponseOK(resp);
}

// jsbridge: sw.SSEConnect
export function SSEConnect(url, onMessage) {
  return $rt.sw.SSEConnect(url, onMessage);
}

// jsbridge: sw.SSEClose
export function SSEClose(id) {
  $rt.sw.SSEClose(id);
}

// jsbridge: sw.SetTimeout
export function SetTimeout(ms, fn) {
  return $rt.sw.SetTimeout(ms, fn);
}

// jsbridge: sw.ClearTimeout
export function ClearTimeout(t) {
  $rt.sw.ClearTimeout(t);
}

// jsbridge: sw.NowSeconds
export function NowSeconds() {
  return $rt.sw.NowSeconds();
}

// jsbridge: sw.NowMillis
export function NowMillis() {
  return $rt.sw.NowMillis();
}

// jsbridge: sw.Log
export function Log(msg) {
  $rt.sw.Log(msg);
}

// jsbridge: sw.Warn
export function Warn(msg) {
  $rt.sw.Warn(msg);
}

