// Package smesh3
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

import * as common$helpers from './common_helpers.mjs';
import * as common$jsbridge$crypto from './common_jsbridge_crypto.mjs';
import * as common$jsbridge$dom from './common_jsbridge_dom.mjs';
import * as common$jsbridge$localstorage from './common_jsbridge_localstorage.mjs';
import * as common$relay from './common_relay.mjs';

// Package-level variables
export let seckey = { $value: null, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let pubkey = { $value: null, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let pubhex = { $value: '', $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let feedContainer = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let statusEl = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let eventCount = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let appContainer = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };

export function init() {
  return;
}

export async function main() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = common$jsbridge$localstorage.GetItem('sm3sh-pubkey');
        $t1_2 = ($t0_1 !== '');
        if ($t1_2) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      case 1:
        pubhex.$set($t0_1);
        $t2_3 = common$helpers.HexDecode($t0_1);
        pubkey.$set($t2_3);
        $t3_4 = await showApp();
        $block = 2; break;
        break;
      case 2:
        return;
        break;
      case 3:
        $t4_5 = showLogin();
        $block = 2; break;
        break;
    }
  }
}

export function showLogin() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62, $t62_63, $t63_64, $t64_65, $t65_66, $t66_67, $t67_68, $t68_69, $t69_70, $t70_71, $t71_72, $t72_73, $t73_74, $t74_75, $t75_76, $t76_77, $t77_78, $t78_79, $t79_80, $t80_81, $t81_82, $t82_83;
  $t0_1 = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = common$jsbridge$dom.Body();
  $t0_1.$set($t1_2);
  $t2_3 = $t0_1.$get();
  $t3_4 = clearChildren($t2_3);
  $t4_5 = common$jsbridge$dom.CreateElement('div');
  $t5_6 = common$jsbridge$dom.SetStyle($t4_5, 'display', 'flex');
  $t6_7 = common$jsbridge$dom.SetStyle($t4_5, 'alignItems', 'center');
  $t7_8 = common$jsbridge$dom.SetStyle($t4_5, 'justifyContent', 'center');
  $t8_9 = common$jsbridge$dom.SetStyle($t4_5, 'height', '100vh');
  $t9_10 = common$jsbridge$dom.SetStyle($t4_5, 'flexDirection', 'column');
  $t10_11 = common$jsbridge$dom.CreateElement('h1');
  $t11_12 = common$jsbridge$dom.SetTextContent($t10_11, 'sm3sh');
  $t12_13 = common$jsbridge$dom.SetStyle($t10_11, 'color', 'var(--accent)');
  $t13_14 = common$jsbridge$dom.SetStyle($t10_11, 'fontSize', '48px');
  $t14_15 = common$jsbridge$dom.SetStyle($t10_11, 'marginBottom', '4px');
  $t15_16 = common$jsbridge$dom.AppendChild($t4_5, $t10_11);
  $t16_17 = common$jsbridge$dom.CreateElement('p');
  $t17_18 = common$jsbridge$dom.SetTextContent($t16_17, 'nostr client — tinygo → javascript');
  $t18_19 = common$jsbridge$dom.SetStyle($t16_17, 'color', 'var(--muted)');
  $t19_20 = common$jsbridge$dom.SetStyle($t16_17, 'marginBottom', '32px');
  $t20_21 = common$jsbridge$dom.AppendChild($t4_5, $t16_17);
  $t21_22 = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t22_23 = common$jsbridge$dom.CreateElement('input');
  $t21_22.$set($t22_23);
  $t23_24 = $t21_22.$get();
  $t24_25 = common$jsbridge$dom.SetAttribute($t23_24, 'type', 'password');
  $t25_26 = $t21_22.$get();
  $t26_27 = common$jsbridge$dom.SetAttribute($t25_26, 'placeholder', 'nsec1...');
  $t27_28 = $t21_22.$get();
  $t28_29 = common$jsbridge$dom.SetAttribute($t27_28, 'autocomplete', 'off');
  $t29_30 = $t21_22.$get();
  $t30_31 = common$jsbridge$dom.SetAttribute($t29_30, 'spellcheck', 'false');
  $t31_32 = $t21_22.$get();
  $t32_33 = common$jsbridge$dom.SetStyle($t31_32, 'width', '420px');
  $t33_34 = $t21_22.$get();
  $t34_35 = common$jsbridge$dom.SetStyle($t33_34, 'maxWidth', '90vw');
  $t35_36 = $t21_22.$get();
  $t36_37 = common$jsbridge$dom.SetStyle($t35_36, 'padding', '12px');
  $t37_38 = $t21_22.$get();
  $t38_39 = common$jsbridge$dom.SetStyle($t37_38, 'fontFamily', 'monospace');
  $t39_40 = $t21_22.$get();
  $t40_41 = common$jsbridge$dom.SetStyle($t39_40, 'fontSize', '14px');
  $t41_42 = $t21_22.$get();
  $t42_43 = common$jsbridge$dom.SetStyle($t41_42, 'border', '1px solid var(--muted)');
  $t43_44 = $t21_22.$get();
  $t44_45 = common$jsbridge$dom.SetStyle($t43_44, 'borderRadius', '4px');
  $t45_46 = $t21_22.$get();
  $t46_47 = common$jsbridge$dom.SetStyle($t45_46, 'background', 'var(--bg)');
  $t47_48 = $t21_22.$get();
  $t48_49 = common$jsbridge$dom.SetStyle($t47_48, 'color', 'var(--fg)');
  $t49_50 = $t21_22.$get();
  $t50_51 = common$jsbridge$dom.SetStyle($t49_50, 'outline', 'none');
  $t51_52 = $t21_22.$get();
  $t52_53 = common$jsbridge$dom.SetStyle($t51_52, 'marginBottom', '12px');
  $t53_54 = $t21_22.$get();
  $t54_55 = common$jsbridge$dom.AppendChild($t4_5, $t53_54);
  $t55_56 = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t56_57 = common$jsbridge$dom.CreateElement('div');
  $t55_56.$set($t56_57);
  $t57_58 = $t55_56.$get();
  $t58_59 = common$jsbridge$dom.SetStyle($t57_58, 'color', '#e55');
  $t59_60 = $t55_56.$get();
  $t60_61 = common$jsbridge$dom.SetStyle($t59_60, 'fontSize', '13px');
  $t61_62 = $t55_56.$get();
  $t62_63 = common$jsbridge$dom.SetStyle($t61_62, 'marginBottom', '12px');
  $t63_64 = $t55_56.$get();
  $t64_65 = common$jsbridge$dom.SetStyle($t63_64, 'minHeight', '18px');
  $t65_66 = $t55_56.$get();
  $t66_67 = common$jsbridge$dom.AppendChild($t4_5, $t65_66);
  $t67_68 = common$jsbridge$dom.CreateElement('button');
  $t68_69 = common$jsbridge$dom.SetTextContent($t67_68, 'login with nsec');
  $t69_70 = common$jsbridge$dom.SetStyle($t67_68, 'padding', '10px 32px');
  $t70_71 = common$jsbridge$dom.SetStyle($t67_68, 'fontFamily', 'monospace');
  $t71_72 = common$jsbridge$dom.SetStyle($t67_68, 'fontSize', '14px');
  $t72_73 = common$jsbridge$dom.SetStyle($t67_68, 'background', 'var(--accent)');
  $t73_74 = common$jsbridge$dom.SetStyle($t67_68, 'color', '#000');
  $t74_75 = common$jsbridge$dom.SetStyle($t67_68, 'border', 'none');
  $t75_76 = common$jsbridge$dom.SetStyle($t67_68, 'borderRadius', '4px');
  $t76_77 = common$jsbridge$dom.SetStyle($t67_68, 'cursor', 'pointer');
  $t77_78 = common$jsbridge$dom.AppendChild($t4_5, $t67_68);
  $t78_79 = showLogin$1.bind(null, $t21_22, $t55_56, $t0_1);
  $t79_80 = common$jsbridge$dom.RegisterCallback($t78_79);
  $t80_81 = common$jsbridge$dom.AddEventListener($t67_68, 'click', $t79_80);
  $t81_82 = $t0_1.$get();
  $t82_83 = common$jsbridge$dom.AppendChild($t81_82, $t4_5);
  return;
}

async function showLogin$1(input, errEl, body) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = input.$get();
        $t1_2 = common$jsbridge$dom.GetProperty($t0_1, 'value');
        $t2_3 = ($t1_2 === '');
        if ($t2_3) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      case 1:
        $t3_4 = errEl.$get();
        $t4_5 = common$jsbridge$dom.SetTextContent($t3_4, 'enter your nsec');
        return;
        break;
      case 2:
        $t5_6 = common$helpers.DecodeNsec($t1_2);
        $t6_7 = ($t5_6 === null);
        if ($t6_7) {
          $block = 3; break;
        }
        else {
          $block = 4; break;
        }
        break;
      case 3:
        $t7_8 = errEl.$get();
        $t8_9 = common$jsbridge$dom.SetTextContent($t7_8, 'invalid nsec');
        return;
        break;
      case 4:
        $t9_10 = common$jsbridge$crypto.PubKeyFromSecKey($t5_6);
        $t10_11 = ($t9_10 === null);
        if ($t10_11) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      case 5:
        $t11_12 = errEl.$get();
        $t12_13 = common$jsbridge$dom.SetTextContent($t11_12, 'invalid key');
        return;
        break;
      case 6:
        seckey.$set($t5_6);
        pubkey.$set($t9_10);
        $t13_14 = common$helpers.HexEncode($t9_10);
        pubhex.$set($t13_14);
        $t14_15 = pubhex.$get();
        $t15_16 = common$jsbridge$localstorage.SetItem('sm3sh-pubkey', $t14_15);
        $t16_17 = common$jsbridge$localstorage.SetItem('sm3sh-mode', 'nsec');
        $t17_18 = input.$get();
        $t18_19 = common$jsbridge$dom.SetProperty($t17_18, 'value', '');
        $t19_20 = body.$get();
        $t20_21 = clearChildren($t19_20);
        $t21_22 = await showApp();
        return;
        break;
    }
  }
}

export async function showApp() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = common$jsbridge$dom.Body();
        $t1_2 = common$jsbridge$dom.CreateElement('div');
        $t2_3 = common$jsbridge$dom.SetStyle($t1_2, 'display', 'flex');
        $t3_4 = common$jsbridge$dom.SetStyle($t1_2, 'justifyContent', 'space-between');
        $t4_5 = common$jsbridge$dom.SetStyle($t1_2, 'alignItems', 'center');
        $t5_6 = common$jsbridge$dom.SetStyle($t1_2, 'padding', '8px 16px');
        $t6_7 = common$jsbridge$dom.SetStyle($t1_2, 'borderBottom', '1px solid var(--muted)');
        $t7_8 = common$jsbridge$dom.CreateElement('span');
        $t8_9 = common$jsbridge$dom.SetTextContent($t7_8, 'sm3sh');
        $t9_10 = common$jsbridge$dom.SetStyle($t7_8, 'color', 'var(--accent)');
        $t10_11 = common$jsbridge$dom.SetStyle($t7_8, 'fontWeight', 'bold');
        $t11_12 = common$jsbridge$dom.AppendChild($t1_2, $t7_8);
        $t12_13 = pubkey.$get();
        $t13_14 = common$helpers.EncodeNpub($t12_13);
        $t14_15 = common$jsbridge$dom.CreateElement('span');
        $t15_16 = common$jsbridge$dom.SetStyle($t14_15, 'color', 'var(--muted)');
        $t16_17 = common$jsbridge$dom.SetStyle($t14_15, 'fontSize', '12px');
        $t17_18 = $rt.builtin.len($t13_14);
        $t18_19 = ($t17_18 > 20);
        if ($t18_19) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      case 1:
        $t19_20 = $rt.builtin.stringSlice($t13_14, undefined, 12);
        $t20_21 = ($t19_20 + '...');
        $t21_22 = $rt.builtin.len($t13_14);
        $t22_23 = ($t21_22 - 4);
        $t23_24 = $rt.builtin.stringSlice($t13_14, $t22_23, undefined);
        $t24_25 = ($t20_21 + $t23_24);
        $t25_26 = common$jsbridge$dom.SetTextContent($t14_15, $t24_25);
        $block = 2; break;
        break;
      case 2:
        $t26_27 = common$jsbridge$dom.AppendChild($t1_2, $t14_15);
        $t27_28 = common$jsbridge$dom.CreateElement('button');
        $t28_29 = common$jsbridge$dom.SetTextContent($t27_28, 'logout');
        $t29_30 = common$jsbridge$dom.SetStyle($t27_28, 'fontFamily', 'monospace');
        $t30_31 = common$jsbridge$dom.SetStyle($t27_28, 'fontSize', '12px');
        $t31_32 = common$jsbridge$dom.SetStyle($t27_28, 'background', 'none');
        $t32_33 = common$jsbridge$dom.SetStyle($t27_28, 'border', '1px solid var(--muted)');
        $t33_34 = common$jsbridge$dom.SetStyle($t27_28, 'color', 'var(--fg)');
        $t34_35 = common$jsbridge$dom.SetStyle($t27_28, 'borderRadius', '4px');
        $t35_36 = common$jsbridge$dom.SetStyle($t27_28, 'padding', '4px 12px');
        $t36_37 = common$jsbridge$dom.SetStyle($t27_28, 'cursor', 'pointer');
        $t37_38 = common$jsbridge$dom.RegisterCallback(showApp$1);
        $t38_39 = common$jsbridge$dom.AddEventListener($t27_28, 'click', $t37_38);
        $t39_40 = common$jsbridge$dom.AppendChild($t1_2, $t27_28);
        $t40_41 = common$jsbridge$dom.AppendChild($t0_1, $t1_2);
        $t41_42 = common$jsbridge$dom.CreateElement('div');
        appContainer.$set($t41_42);
        $t42_43 = appContainer.$get();
        $t43_44 = common$jsbridge$dom.SetStyle($t42_43, 'padding', '16px');
        $t44_45 = appContainer.$get();
        $t45_46 = common$jsbridge$dom.AppendChild($t0_1, $t44_45);
        $t46_47 = common$jsbridge$dom.CreateElement('div');
        statusEl.$set($t46_47);
        $t47_48 = statusEl.$get();
        $t48_49 = common$jsbridge$dom.SetStyle($t47_48, 'color', 'var(--muted)');
        $t49_50 = statusEl.$get();
        $t50_51 = common$jsbridge$dom.SetStyle($t49_50, 'fontSize', '13px');
        $t51_52 = statusEl.$get();
        $t52_53 = common$jsbridge$dom.SetStyle($t51_52, 'marginBottom', '12px');
        $t53_54 = statusEl.$get();
        $t54_55 = common$jsbridge$dom.SetTextContent($t53_54, 'connecting...');
        $t55_56 = appContainer.$get();
        $t56_57 = statusEl.$get();
        $t57_58 = common$jsbridge$dom.AppendChild($t55_56, $t56_57);
        $t58_59 = common$jsbridge$dom.CreateElement('div');
        feedContainer.$set($t58_59);
        $t59_60 = appContainer.$get();
        $t60_61 = feedContainer.$get();
        $t61_62 = common$jsbridge$dom.AppendChild($t59_60, $t60_61);
        $rt.goroutine.spawn(async () => await connectRelay());
        return;
        break;
    }
  }
}

function showApp$1() {
  let $t0_1;
  $t0_1 = doLogout();
  return;
}

export function doLogout() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = seckey.$get();
        $t1_2 = $rt.builtin.len($t0_1);
        $t2_3 = -1;
        $block = 1; break;
        break;
      case 1:
        $t3_4 = ($t2_3 + 1);
        $t4_5 = ($t3_4 < $t1_2);
        if ($t4_5) {
          $block = 2; break;
        }
        else {
          $block = 3; break;
        }
        break;
      case 2:
        $t5_6 = seckey.$get();
        $t6_7 = $t5_6.addr($t3_4);
        $t6_7.$set(0);
        $t2_3 = $t3_4;
        $block = 1; break;
        break;
      case 3:
        seckey.$set(null);
        pubkey.$set(null);
        pubhex.$set('');
        $t7_8 = common$jsbridge$localstorage.RemoveItem('sm3sh-pubkey');
        $t8_9 = common$jsbridge$localstorage.RemoveItem('sm3sh-mode');
        $t9_10 = common$jsbridge$dom.Body();
        $t10_11 = clearChildren($t9_10);
        $t11_12 = showLogin();
        return;
        break;
    }
  }
}

export async function connectRelay() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = { $value: '', $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t0_1.$set('wss://relay.damus.io');
        $t1_2 = $t0_1.$get();
        $t2_3 = await common$relay.Dial($t1_2);
        $t3_4 = await common$relay.Conn$WaitOpen($t2_3);
        if ($t3_4) {
          $block = 2; break;
        }
        else {
          $block = 1; break;
        }
        break;
      case 1:
        $t4_5 = statusEl.$get();
        $t5_6 = $t0_1.$get();
        $t6_7 = ('failed: ' + $t5_6);
        $t7_8 = common$jsbridge$dom.SetTextContent($t4_5, $t6_7);
        $t8_9 = statusEl.$get();
        $t9_10 = common$jsbridge$dom.SetStyle($t8_9, 'color', '#e55');
        return;
        break;
      case 2:
        $t10_11 = statusEl.$get();
        $t11_12 = $t0_1.$get();
        $t12_13 = ('connected: ' + $t11_12);
        $t13_14 = common$jsbridge$dom.SetTextContent($t10_11, $t12_13);
        $t14_15 = { $value: { IDs: null, Authors: null, Kinds: null, Tags: null, Since: 0, Until: 0, Limit: 0 }, $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t15_16 = { $get() { return $t14_15.$get().Kinds; }, $set(v) { const obj = $t14_15.$get(); obj.Kinds = v; $t14_15.$set(obj); } };
        $t16_17 = { $value: $rt.builtin.makeSlice(1, 1, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t17_18 = $t16_17.$get().addr(0);
        $t17_18.$set(1);
        $t18_19 = $rt.builtin.sliceSlice($t16_17.$get(), undefined, undefined, undefined);
        $t19_20 = { $get() { return $t14_15.$get().Limit; }, $set(v) { const obj = $t14_15.$get(); obj.Limit = v; $t14_15.$set(obj); } };
        $t15_16.$set($t18_19);
        $t19_20.$set(20);
        $t20_21 = { $value: $rt.builtin.makeSlice(1, 1, null), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t21_22 = $t20_21.$get().addr(0);
        $t21_22.$set($t14_15);
        $t22_23 = $rt.builtin.sliceSlice($t20_21.$get(), undefined, undefined, undefined);
        $t23_24 = common$relay.Conn$Subscribe($t2_3, 'feed', $t22_23);
        $t24_25 = { $get() { return $t23_24.$get().OnEvent; }, $set(v) { const obj = $t23_24.$get(); obj.OnEvent = v; $t23_24.$set(obj); } };
        $t24_25.$set(connectRelay$1);
        $t25_26 = connectRelay$2.bind(null, $t0_1);
        $t26_27 = { $get() { return $t23_24.$get().OnEOSE; }, $set(v) { const obj = $t23_24.$get(); obj.OnEOSE = v; $t23_24.$set(obj); } };
        $t26_27.$set($t25_26);
        return;
        break;
    }
  }
}

function connectRelay$1(ev) {
  let $t0_1, $t1_2, $t2_3;
  $t0_1 = eventCount.$get();
  $t1_2 = ($t0_1 + 1);
  eventCount.$set($t1_2);
  $t2_3 = renderNote(ev);
  return;
}

function connectRelay$2(url) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8;
  $t0_1 = statusEl.$get();
  $t1_2 = url.$get();
  $t2_3 = ($t1_2 + ' | ');
  $t3_4 = eventCount.$get();
  $t4_5 = itoa($t3_4);
  $t5_6 = ($t2_3 + $t4_5);
  $t6_7 = ($t5_6 + ' events');
  $t7_8 = common$jsbridge$dom.SetTextContent($t0_1, $t6_7);
  return;
}

export function renderNote(ev) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = common$jsbridge$dom.CreateElement('div');
        $t1_2 = common$jsbridge$dom.SetStyle($t0_1, 'borderBottom', '1px solid var(--muted)');
        $t2_3 = common$jsbridge$dom.SetStyle($t0_1, 'padding', '12px 0');
        $t3_4 = common$jsbridge$dom.CreateElement('div');
        $t4_5 = common$jsbridge$dom.SetStyle($t3_4, 'fontSize', '12px');
        $t5_6 = common$jsbridge$dom.SetStyle($t3_4, 'color', 'var(--muted)');
        $t6_7 = common$jsbridge$dom.SetStyle($t3_4, 'marginBottom', '4px');
        $t7_8 = { $get() { return ev.$get().PubKey; }, $set(v) { const obj = ev.$get(); obj.PubKey = v; ev.$set(obj); } };
        $t8_9 = $t7_8.$get();
        $t9_10 = common$helpers.HexDecode($t8_9);
        $t10_11 = common$helpers.EncodeNpub($t9_10);
        $t11_12 = $rt.builtin.len($t10_11);
        $t12_13 = ($t11_12 > 20);
        if ($t12_13) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      case 1:
        $t13_14 = $rt.builtin.stringSlice($t10_11, undefined, 12);
        $t14_15 = ($t13_14 + '...');
        $t15_16 = $rt.builtin.len($t10_11);
        $t16_17 = ($t15_16 - 4);
        $t17_18 = $rt.builtin.stringSlice($t10_11, $t16_17, undefined);
        $t18_19 = ($t14_15 + $t17_18);
        $t19_20 = common$jsbridge$dom.SetTextContent($t3_4, $t18_19);
        $block = 2; break;
        break;
      case 2:
        $t20_21 = common$jsbridge$dom.AppendChild($t0_1, $t3_4);
        $t21_22 = common$jsbridge$dom.CreateElement('div');
        $t22_23 = common$jsbridge$dom.SetStyle($t21_22, 'fontSize', '14px');
        $t23_24 = common$jsbridge$dom.SetStyle($t21_22, 'lineHeight', '1.5');
        $t24_25 = common$jsbridge$dom.SetStyle($t21_22, 'wordBreak', 'break-word');
        $t25_26 = { $get() { return ev.$get().Content; }, $set(v) { const obj = ev.$get(); obj.Content = v; ev.$set(obj); } };
        $t26_27 = $t25_26.$get();
        $t27_28 = $rt.builtin.len($t26_27);
        $t28_29 = ($t27_28 > 500);
        if ($t28_29) {
          $block = 4; break;
        }
        else {
          $t35_36 = $t26_27;
          $block = 5; break;
        }
        break;
      case 3:
        $t29_30 = { $get() { return ev.$get().PubKey; }, $set(v) { const obj = ev.$get(); obj.PubKey = v; ev.$set(obj); } };
        $t30_31 = $t29_30.$get();
        $t31_32 = common$helpers.PubkeyShort($t30_31);
        $t32_33 = common$jsbridge$dom.SetTextContent($t3_4, $t31_32);
        $block = 2; break;
        break;
      case 4:
        $t33_34 = $rt.builtin.stringSlice($t26_27, undefined, 500);
        $t34_35 = ($t33_34 + '...');
        $t35_36 = $t34_35;
        $block = 5; break;
        break;
      case 5:
        $t36_37 = common$jsbridge$dom.SetTextContent($t21_22, $t35_36);
        $t37_38 = common$jsbridge$dom.AppendChild($t0_1, $t21_22);
        $t38_39 = feedContainer.$get();
        $t39_40 = common$jsbridge$dom.FirstChild($t38_39);
        $t40_41 = ($t39_40 !== 0);
        if ($t40_41) {
          $block = 6; break;
        }
        else {
          $block = 8; break;
        }
        break;
      case 6:
        $t41_42 = feedContainer.$get();
        $t42_43 = common$jsbridge$dom.InsertBefore($t41_42, $t0_1, $t39_40);
        $block = 7; break;
        break;
      case 7:
        return;
        break;
      case 8:
        $t43_44 = feedContainer.$get();
        $t44_45 = common$jsbridge$dom.AppendChild($t43_44, $t0_1);
        $block = 7; break;
        break;
    }
  }
}

export function clearChildren(el) {
  let $t0_1;
  $t0_1 = common$jsbridge$dom.SetInnerHTML(el, '');
  return;
}

export function itoa(n) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0:
        $t0_1 = (n === 0);
        if ($t0_1) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      case 1:
        return '0';
        break;
      case 2:
        $t1_2 = (n < 0);
        if ($t1_2) {
          $block = 3; break;
        }
        else {
          $t3_4 = n;
          $t4_5 = false;
          $block = 4; break;
        }
        break;
      case 3:
        $t2_3 = -n;
        $t3_4 = $t2_3;
        $t4_5 = true;
        $block = 4; break;
        break;
      case 4:
        $t5_6 = { $value: $rt.builtin.makeSlice(20, 20, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t12_13 = $t3_4;
        $t13_14 = 20;
        $block = 7; break;
        break;
      case 5:
        $t6_7 = ($t13_14 - 1);
        $t7_8 = ($t12_13 % 10);
        $t8_9 = (48 + $t7_8);
        $t9_10 = ($t8_9 & 0xFF);
        $t10_11 = $t5_6.$get().addr($t6_7);
        $t10_11.$set($t9_10);
        $t11_12 = Math.trunc($t12_13 / 10);
        $t12_13 = $t11_12;
        $t13_14 = $t6_7;
        $block = 7; break;
        break;
      case 6:
        if ($t4_5) {
          $block = 8; break;
        }
        else {
          $t17_18 = $t13_14;
          $block = 9; break;
        }
        break;
      case 7:
        $t14_15 = ($t12_13 > 0);
        if ($t14_15) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      case 8:
        $t15_16 = ($t13_14 - 1);
        $t16_17 = $t5_6.$get().addr($t15_16);
        $t16_17.$set(45);
        $t17_18 = $t15_16;
        $block = 9; break;
        break;
      case 9:
        $t18_19 = $rt.builtin.sliceSlice($t5_6.$get(), $t17_18, undefined, undefined);
        $t19_20 = $rt.builtin.bytesToString($t18_19);
        return $t19_20;
        break;
    }
  }
}

