// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orlysync/relaygroup/v1/service.proto

package relaygroupv1

import (
	v1 "git.smesh.lol/orly/pkg/proto/orlysync/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelayGroupConfig represents a relay group configuration
type RelayGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relays        []string               `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"` // List of relay URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayGroupConfig) Reset() {
	*x = RelayGroupConfig{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayGroupConfig) ProtoMessage() {}

func (x *RelayGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayGroupConfig.ProtoReflect.Descriptor instead.
func (*RelayGroupConfig) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RelayGroupConfig) GetRelays() []string {
	if x != nil {
		return x.Relays
	}
	return nil
}

// RelayGroupConfigResponse contains the authoritative config
type RelayGroupConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Config          *RelayGroupConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Found           bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	SourceEventId   []byte                 `protobuf:"bytes,3,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`      // ID of the event that provided this config
	SourceTimestamp int64                  `protobuf:"varint,4,opt,name=source_timestamp,json=sourceTimestamp,proto3" json:"source_timestamp,omitempty"` // Timestamp of the source event
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayGroupConfigResponse) Reset() {
	*x = RelayGroupConfigResponse{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayGroupConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayGroupConfigResponse) ProtoMessage() {}

func (x *RelayGroupConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayGroupConfigResponse.ProtoReflect.Descriptor instead.
func (*RelayGroupConfigResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RelayGroupConfigResponse) GetConfig() *RelayGroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RelayGroupConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RelayGroupConfigResponse) GetSourceEventId() []byte {
	if x != nil {
		return x.SourceEventId
	}
	return nil
}

func (x *RelayGroupConfigResponse) GetSourceTimestamp() int64 {
	if x != nil {
		return x.SourceTimestamp
	}
	return 0
}

// RelaysResponse contains the list of relays
type RelaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relays        []string               `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaysResponse) Reset() {
	*x = RelaysResponse{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaysResponse) ProtoMessage() {}

func (x *RelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaysResponse.ProtoReflect.Descriptor instead.
func (*RelaysResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *RelaysResponse) GetRelays() []string {
	if x != nil {
		return x.Relays
	}
	return nil
}

// AuthorizedPublisherRequest checks if a pubkey is authorized
type AuthorizedPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // 32 bytes public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedPublisherRequest) Reset() {
	*x = AuthorizedPublisherRequest{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPublisherRequest) ProtoMessage() {}

func (x *AuthorizedPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPublisherRequest.ProtoReflect.Descriptor instead.
func (*AuthorizedPublisherRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizedPublisherRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

// AuthorizedPublisherResponse indicates if the pubkey is authorized
type AuthorizedPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedPublisherResponse) Reset() {
	*x = AuthorizedPublisherResponse{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPublisherResponse) ProtoMessage() {}

func (x *AuthorizedPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPublisherResponse.ProtoReflect.Descriptor instead.
func (*AuthorizedPublisherResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizedPublisherResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

// AuthorizedPubkeysResponse contains all authorized pubkeys
type AuthorizedPubkeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkeys       [][]byte               `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"` // List of 32-byte pubkeys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedPubkeysResponse) Reset() {
	*x = AuthorizedPubkeysResponse{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPubkeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPubkeysResponse) ProtoMessage() {}

func (x *AuthorizedPubkeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPubkeysResponse.ProtoReflect.Descriptor instead.
func (*AuthorizedPubkeysResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizedPubkeysResponse) GetPubkeys() [][]byte {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

// ValidateEventRequest requests validation of a relay group event
type ValidateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEventRequest) Reset() {
	*x = ValidateEventRequest{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEventRequest) ProtoMessage() {}

func (x *ValidateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEventRequest.ProtoReflect.Descriptor instead.
func (*ValidateEventRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateEventRequest) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// ValidateEventResponse contains validation results
type ValidateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if not valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEventResponse) Reset() {
	*x = ValidateEventResponse{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEventResponse) ProtoMessage() {}

func (x *ValidateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEventResponse.ProtoReflect.Descriptor instead.
func (*ValidateEventResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateEventResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HandleEventRequest requests processing of a relay group event
type HandleEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEventRequest) Reset() {
	*x = HandleEventRequest{}
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventRequest) ProtoMessage() {}

func (x *HandleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_relaygroup_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventRequest.ProtoReflect.Descriptor instead.
func (*HandleEventRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_relaygroup_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *HandleEventRequest) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_orlysync_relaygroup_v1_service_proto protoreflect.FileDescriptor

const file_orlysync_relaygroup_v1_service_proto_rawDesc = "" +
	"\n" +
	"$orlysync/relaygroup/v1/service.proto\x12\x16orlysync.relaygroup.v1\x1a\x1eorlysync/common/v1/types.proto\"*\n" +
	"\x10RelayGroupConfig\x12\x16\n" +
	"\x06relays\x18\x01 \x03(\tR\x06relays\"\xc5\x01\n" +
	"\x18RelayGroupConfigResponse\x12@\n" +
	"\x06config\x18\x01 \x01(\v2(.orlysync.relaygroup.v1.RelayGroupConfigR\x06config\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12&\n" +
	"\x0fsource_event_id\x18\x03 \x01(\fR\rsourceEventId\x12)\n" +
	"\x10source_timestamp\x18\x04 \x01(\x03R\x0fsourceTimestamp\"(\n" +
	"\x0eRelaysResponse\x12\x16\n" +
	"\x06relays\x18\x01 \x03(\tR\x06relays\"4\n" +
	"\x1aAuthorizedPublisherRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\"=\n" +
	"\x1bAuthorizedPublisherResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"5\n" +
	"\x19AuthorizedPubkeysResponse\x12\x18\n" +
	"\apubkeys\x18\x01 \x03(\fR\apubkeys\"G\n" +
	"\x14ValidateEventRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.orlysync.common.v1.EventR\x05event\"C\n" +
	"\x15ValidateEventResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x12HandleEventRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.orlysync.common.v1.EventR\x05event2\xd3\x05\n" +
	"\x11RelayGroupService\x12E\n" +
	"\x05Ready\x12\x19.orlysync.common.v1.Empty\x1a!.orlysync.common.v1.ReadyResponse\x12f\n" +
	"\x17FindAuthoritativeConfig\x12\x19.orlysync.common.v1.Empty\x1a0.orlysync.relaygroup.v1.RelayGroupConfigResponse\x12N\n" +
	"\tGetRelays\x12\x19.orlysync.common.v1.Empty\x1a&.orlysync.relaygroup.v1.RelaysResponse\x12\x80\x01\n" +
	"\x15IsAuthorizedPublisher\x122.orlysync.relaygroup.v1.AuthorizedPublisherRequest\x1a3.orlysync.relaygroup.v1.AuthorizedPublisherResponse\x12d\n" +
	"\x14GetAuthorizedPubkeys\x12\x19.orlysync.common.v1.Empty\x1a1.orlysync.relaygroup.v1.AuthorizedPubkeysResponse\x12v\n" +
	"\x17ValidateRelayGroupEvent\x12,.orlysync.relaygroup.v1.ValidateEventRequest\x1a-.orlysync.relaygroup.v1.ValidateEventResponse\x12^\n" +
	"\x15HandleRelayGroupEvent\x12*.orlysync.relaygroup.v1.HandleEventRequest\x1a\x19.orlysync.common.v1.EmptyBBZ@git.smesh.lol/orly/pkg/proto/orlysync/relaygroup/v1;relaygroupv1b\x06proto3"

var (
	file_orlysync_relaygroup_v1_service_proto_rawDescOnce sync.Once
	file_orlysync_relaygroup_v1_service_proto_rawDescData []byte
)

func file_orlysync_relaygroup_v1_service_proto_rawDescGZIP() []byte {
	file_orlysync_relaygroup_v1_service_proto_rawDescOnce.Do(func() {
		file_orlysync_relaygroup_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orlysync_relaygroup_v1_service_proto_rawDesc), len(file_orlysync_relaygroup_v1_service_proto_rawDesc)))
	})
	return file_orlysync_relaygroup_v1_service_proto_rawDescData
}

var file_orlysync_relaygroup_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orlysync_relaygroup_v1_service_proto_goTypes = []any{
	(*RelayGroupConfig)(nil),            // 0: orlysync.relaygroup.v1.RelayGroupConfig
	(*RelayGroupConfigResponse)(nil),    // 1: orlysync.relaygroup.v1.RelayGroupConfigResponse
	(*RelaysResponse)(nil),              // 2: orlysync.relaygroup.v1.RelaysResponse
	(*AuthorizedPublisherRequest)(nil),  // 3: orlysync.relaygroup.v1.AuthorizedPublisherRequest
	(*AuthorizedPublisherResponse)(nil), // 4: orlysync.relaygroup.v1.AuthorizedPublisherResponse
	(*AuthorizedPubkeysResponse)(nil),   // 5: orlysync.relaygroup.v1.AuthorizedPubkeysResponse
	(*ValidateEventRequest)(nil),        // 6: orlysync.relaygroup.v1.ValidateEventRequest
	(*ValidateEventResponse)(nil),       // 7: orlysync.relaygroup.v1.ValidateEventResponse
	(*HandleEventRequest)(nil),          // 8: orlysync.relaygroup.v1.HandleEventRequest
	(*v1.Event)(nil),                    // 9: orlysync.common.v1.Event
	(*v1.Empty)(nil),                    // 10: orlysync.common.v1.Empty
	(*v1.ReadyResponse)(nil),            // 11: orlysync.common.v1.ReadyResponse
}
var file_orlysync_relaygroup_v1_service_proto_depIdxs = []int32{
	0,  // 0: orlysync.relaygroup.v1.RelayGroupConfigResponse.config:type_name -> orlysync.relaygroup.v1.RelayGroupConfig
	9,  // 1: orlysync.relaygroup.v1.ValidateEventRequest.event:type_name -> orlysync.common.v1.Event
	9,  // 2: orlysync.relaygroup.v1.HandleEventRequest.event:type_name -> orlysync.common.v1.Event
	10, // 3: orlysync.relaygroup.v1.RelayGroupService.Ready:input_type -> orlysync.common.v1.Empty
	10, // 4: orlysync.relaygroup.v1.RelayGroupService.FindAuthoritativeConfig:input_type -> orlysync.common.v1.Empty
	10, // 5: orlysync.relaygroup.v1.RelayGroupService.GetRelays:input_type -> orlysync.common.v1.Empty
	3,  // 6: orlysync.relaygroup.v1.RelayGroupService.IsAuthorizedPublisher:input_type -> orlysync.relaygroup.v1.AuthorizedPublisherRequest
	10, // 7: orlysync.relaygroup.v1.RelayGroupService.GetAuthorizedPubkeys:input_type -> orlysync.common.v1.Empty
	6,  // 8: orlysync.relaygroup.v1.RelayGroupService.ValidateRelayGroupEvent:input_type -> orlysync.relaygroup.v1.ValidateEventRequest
	8,  // 9: orlysync.relaygroup.v1.RelayGroupService.HandleRelayGroupEvent:input_type -> orlysync.relaygroup.v1.HandleEventRequest
	11, // 10: orlysync.relaygroup.v1.RelayGroupService.Ready:output_type -> orlysync.common.v1.ReadyResponse
	1,  // 11: orlysync.relaygroup.v1.RelayGroupService.FindAuthoritativeConfig:output_type -> orlysync.relaygroup.v1.RelayGroupConfigResponse
	2,  // 12: orlysync.relaygroup.v1.RelayGroupService.GetRelays:output_type -> orlysync.relaygroup.v1.RelaysResponse
	4,  // 13: orlysync.relaygroup.v1.RelayGroupService.IsAuthorizedPublisher:output_type -> orlysync.relaygroup.v1.AuthorizedPublisherResponse
	5,  // 14: orlysync.relaygroup.v1.RelayGroupService.GetAuthorizedPubkeys:output_type -> orlysync.relaygroup.v1.AuthorizedPubkeysResponse
	7,  // 15: orlysync.relaygroup.v1.RelayGroupService.ValidateRelayGroupEvent:output_type -> orlysync.relaygroup.v1.ValidateEventResponse
	10, // 16: orlysync.relaygroup.v1.RelayGroupService.HandleRelayGroupEvent:output_type -> orlysync.common.v1.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orlysync_relaygroup_v1_service_proto_init() }
func file_orlysync_relaygroup_v1_service_proto_init() {
	if File_orlysync_relaygroup_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orlysync_relaygroup_v1_service_proto_rawDesc), len(file_orlysync_relaygroup_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orlysync_relaygroup_v1_service_proto_goTypes,
		DependencyIndexes: file_orlysync_relaygroup_v1_service_proto_depIdxs,
		MessageInfos:      file_orlysync_relaygroup_v1_service_proto_msgTypes,
	}.Build()
	File_orlysync_relaygroup_v1_service_proto = out.File
	file_orlysync_relaygroup_v1_service_proto_goTypes = nil
	file_orlysync_relaygroup_v1_service_proto_depIdxs = nil
}
