// Package common/jsbridge/idb
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

// Package-level variables

export function init() {
  return;
}

// jsbridge: idb.Open
export function Open(fn) {
  $rt.idb.Open(fn);
}

// jsbridge: idb.SaveEvent
export function SaveEvent(eventJSON, fn) {
  $rt.idb.SaveEvent(eventJSON, fn);
}

// jsbridge: idb.QueryEvents
export function QueryEvents(filterJSON, fn) {
  $rt.idb.QueryEvents(filterJSON, fn);
}

// jsbridge: idb.SaveDM
export function SaveDM(dmJSON, fn) {
  $rt.idb.SaveDM(dmJSON, fn);
}

// jsbridge: idb.QueryDMs
export function QueryDMs(peer, limit, until, fn) {
  $rt.idb.QueryDMs(peer, limit, until, fn);
}

// jsbridge: idb.GetConversationList
export function GetConversationList(fn) {
  $rt.idb.GetConversationList(fn);
}

// jsbridge: idb.ClearDMsByPeer
export function ClearDMsByPeer(peer, fn) {
  $rt.idb.ClearDMsByPeer(peer, fn);
}

// jsbridge: idb.SetVersion
export function SetVersion(v) {
  $rt.idb.SetVersion(v);
}

