// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orlysync/distributed/v1/service.proto

package distributedv1

import (
	v1 "git.smesh.lol/orly/pkg/proto/orlysync/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CurrentRequest is sent to request current serial number
type CurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // Requesting node's identity
	RelayUrl      string                 `protobuf:"bytes,2,opt,name=relay_url,json=relayUrl,proto3" json:"relay_url,omitempty"` // Requesting relay's URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRequest) Reset() {
	*x = CurrentRequest{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRequest) ProtoMessage() {}

func (x *CurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRequest.ProtoReflect.Descriptor instead.
func (*CurrentRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CurrentRequest) GetRelayUrl() string {
	if x != nil {
		return x.RelayUrl
	}
	return ""
}

// CurrentResponse contains the current serial number
type CurrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // Responding node's identity
	RelayUrl      string                 `protobuf:"bytes,2,opt,name=relay_url,json=relayUrl,proto3" json:"relay_url,omitempty"` // Responding relay's URL
	Serial        uint64                 `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`                    // Current serial number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentResponse) Reset() {
	*x = CurrentResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentResponse) ProtoMessage() {}

func (x *CurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentResponse.ProtoReflect.Descriptor instead.
func (*CurrentResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CurrentResponse) GetRelayUrl() string {
	if x != nil {
		return x.RelayUrl
	}
	return ""
}

func (x *CurrentResponse) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

// EventIDsRequest requests event IDs in a serial range
type EventIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // Requesting node's identity
	RelayUrl      string                 `protobuf:"bytes,2,opt,name=relay_url,json=relayUrl,proto3" json:"relay_url,omitempty"` // Requesting relay's URL
	From          uint64                 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`                        // Start serial (inclusive)
	To            uint64                 `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`                            // End serial (inclusive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventIDsRequest) Reset() {
	*x = EventIDsRequest{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIDsRequest) ProtoMessage() {}

func (x *EventIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIDsRequest.ProtoReflect.Descriptor instead.
func (*EventIDsRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *EventIDsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventIDsRequest) GetRelayUrl() string {
	if x != nil {
		return x.RelayUrl
	}
	return ""
}

func (x *EventIDsRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *EventIDsRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

// EventIDsResponse contains event IDs mapped to serial numbers
type EventIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventMap      map[string]uint64      `protobuf:"bytes,1,rep,name=event_map,json=eventMap,proto3" json:"event_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // event_id (hex) -> serial
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventIDsResponse) Reset() {
	*x = EventIDsResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIDsResponse) ProtoMessage() {}

func (x *EventIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIDsResponse.ProtoReflect.Descriptor instead.
func (*EventIDsResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *EventIDsResponse) GetEventMap() map[string]uint64 {
	if x != nil {
		return x.EventMap
	}
	return nil
}

// PeersResponse contains the list of sync peers
type PeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // List of peer relay URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponse) Reset() {
	*x = PeersResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse) ProtoMessage() {}

func (x *PeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse.ProtoReflect.Descriptor instead.
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *PeersResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

// UpdatePeersRequest updates the peer list
type UpdatePeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // New list of peer relay URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePeersRequest) Reset() {
	*x = UpdatePeersRequest{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePeersRequest) ProtoMessage() {}

func (x *UpdatePeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePeersRequest.ProtoReflect.Descriptor instead.
func (*UpdatePeersRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePeersRequest) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

// AuthorizedPeerRequest checks if a peer is authorized
type AuthorizedPeerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerUrl        string                 `protobuf:"bytes,1,opt,name=peer_url,json=peerUrl,proto3" json:"peer_url,omitempty"`
	ExpectedPubkey string                 `protobuf:"bytes,2,opt,name=expected_pubkey,json=expectedPubkey,proto3" json:"expected_pubkey,omitempty"` // Expected NIP-11 pubkey
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizedPeerRequest) Reset() {
	*x = AuthorizedPeerRequest{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPeerRequest) ProtoMessage() {}

func (x *AuthorizedPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPeerRequest.ProtoReflect.Descriptor instead.
func (*AuthorizedPeerRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizedPeerRequest) GetPeerUrl() string {
	if x != nil {
		return x.PeerUrl
	}
	return ""
}

func (x *AuthorizedPeerRequest) GetExpectedPubkey() string {
	if x != nil {
		return x.ExpectedPubkey
	}
	return ""
}

// AuthorizedPeerResponse indicates if the peer is authorized
type AuthorizedPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedPeerResponse) Reset() {
	*x = AuthorizedPeerResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedPeerResponse) ProtoMessage() {}

func (x *AuthorizedPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedPeerResponse.ProtoReflect.Descriptor instead.
func (*AuthorizedPeerResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizedPeerResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

// PeerPubkeyRequest requests the pubkey for a peer
type PeerPubkeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerUrl       string                 `protobuf:"bytes,1,opt,name=peer_url,json=peerUrl,proto3" json:"peer_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerPubkeyRequest) Reset() {
	*x = PeerPubkeyRequest{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerPubkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerPubkeyRequest) ProtoMessage() {}

func (x *PeerPubkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerPubkeyRequest.ProtoReflect.Descriptor instead.
func (*PeerPubkeyRequest) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *PeerPubkeyRequest) GetPeerUrl() string {
	if x != nil {
		return x.PeerUrl
	}
	return ""
}

// PeerPubkeyResponse contains the peer's pubkey
type PeerPubkeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // Peer's NIP-11 pubkey (hex or npub)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerPubkeyResponse) Reset() {
	*x = PeerPubkeyResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerPubkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerPubkeyResponse) ProtoMessage() {}

func (x *PeerPubkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerPubkeyResponse.ProtoReflect.Descriptor instead.
func (*PeerPubkeyResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *PeerPubkeyResponse) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

// NewEventNotification notifies of a new event
type NewEventNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       []byte                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 32 bytes event ID
	Serial        uint64                 `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`                 // Assigned serial number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEventNotification) Reset() {
	*x = NewEventNotification{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventNotification) ProtoMessage() {}

func (x *NewEventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventNotification.ProtoReflect.Descriptor instead.
func (*NewEventNotification) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *NewEventNotification) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *NewEventNotification) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

// SyncStatusResponse contains sync status for all peers
type SyncStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentSerial uint64                 `protobuf:"varint,1,opt,name=current_serial,json=currentSerial,proto3" json:"current_serial,omitempty"`
	Peers         []*v1.PeerInfo         `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusResponse) Reset() {
	*x = SyncStatusResponse{}
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusResponse) ProtoMessage() {}

func (x *SyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orlysync_distributed_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_orlysync_distributed_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *SyncStatusResponse) GetCurrentSerial() uint64 {
	if x != nil {
		return x.CurrentSerial
	}
	return 0
}

func (x *SyncStatusResponse) GetPeers() []*v1.PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_orlysync_distributed_v1_service_proto protoreflect.FileDescriptor

const file_orlysync_distributed_v1_service_proto_rawDesc = "" +
	"\n" +
	"%orlysync/distributed/v1/service.proto\x12\x17orlysync.distributed.v1\x1a\x1eorlysync/common/v1/types.proto\"F\n" +
	"\x0eCurrentRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\trelay_url\x18\x02 \x01(\tR\brelayUrl\"_\n" +
	"\x0fCurrentResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\trelay_url\x18\x02 \x01(\tR\brelayUrl\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\x04R\x06serial\"k\n" +
	"\x0fEventIDsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\trelay_url\x18\x02 \x01(\tR\brelayUrl\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x04R\x02to\"\xa5\x01\n" +
	"\x10EventIDsResponse\x12T\n" +
	"\tevent_map\x18\x01 \x03(\v27.orlysync.distributed.v1.EventIDsResponse.EventMapEntryR\beventMap\x1a;\n" +
	"\rEventMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"%\n" +
	"\rPeersResponse\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\"*\n" +
	"\x12UpdatePeersRequest\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\"[\n" +
	"\x15AuthorizedPeerRequest\x12\x19\n" +
	"\bpeer_url\x18\x01 \x01(\tR\apeerUrl\x12'\n" +
	"\x0fexpected_pubkey\x18\x02 \x01(\tR\x0eexpectedPubkey\"8\n" +
	"\x16AuthorizedPeerResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\".\n" +
	"\x11PeerPubkeyRequest\x12\x19\n" +
	"\bpeer_url\x18\x01 \x01(\tR\apeerUrl\",\n" +
	"\x12PeerPubkeyResponse\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"I\n" +
	"\x14NewEventNotification\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x04R\x06serial\"o\n" +
	"\x12SyncStatusResponse\x12%\n" +
	"\x0ecurrent_serial\x18\x01 \x01(\x04R\rcurrentSerial\x122\n" +
	"\x05peers\x18\x02 \x03(\v2\x1c.orlysync.common.v1.PeerInfoR\x05peers2\xea\t\n" +
	"\x16DistributedSyncService\x12E\n" +
	"\x05Ready\x12\x19.orlysync.common.v1.Empty\x1a!.orlysync.common.v1.ReadyResponse\x12B\n" +
	"\aGetInfo\x12\x19.orlysync.common.v1.Empty\x1a\x1c.orlysync.common.v1.SyncInfo\x12e\n" +
	"\x10GetCurrentSerial\x12'.orlysync.distributed.v1.CurrentRequest\x1a(.orlysync.distributed.v1.CurrentResponse\x12b\n" +
	"\vGetEventIDs\x12(.orlysync.distributed.v1.EventIDsRequest\x1a).orlysync.distributed.v1.EventIDsResponse\x12Y\n" +
	"\x14HandleCurrentRequest\x12\x1f.orlysync.common.v1.HTTPRequest\x1a .orlysync.common.v1.HTTPResponse\x12Z\n" +
	"\x15HandleEventIDsRequest\x12\x1f.orlysync.common.v1.HTTPRequest\x1a .orlysync.common.v1.HTTPResponse\x12M\n" +
	"\bGetPeers\x12\x19.orlysync.common.v1.Empty\x1a&.orlysync.distributed.v1.PeersResponse\x12U\n" +
	"\vUpdatePeers\x12+.orlysync.distributed.v1.UpdatePeersRequest\x1a\x19.orlysync.common.v1.Empty\x12s\n" +
	"\x10IsAuthorizedPeer\x12..orlysync.distributed.v1.AuthorizedPeerRequest\x1a/.orlysync.distributed.v1.AuthorizedPeerResponse\x12h\n" +
	"\rGetPeerPubkey\x12*.orlysync.distributed.v1.PeerPubkeyRequest\x1a+.orlysync.distributed.v1.PeerPubkeyResponse\x12D\n" +
	"\fUpdateSerial\x12\x19.orlysync.common.v1.Empty\x1a\x19.orlysync.common.v1.Empty\x12Z\n" +
	"\x0eNotifyNewEvent\x12-.orlysync.distributed.v1.NewEventNotification\x1a\x19.orlysync.common.v1.Empty\x12C\n" +
	"\vTriggerSync\x12\x19.orlysync.common.v1.Empty\x1a\x19.orlysync.common.v1.Empty\x12W\n" +
	"\rGetSyncStatus\x12\x19.orlysync.common.v1.Empty\x1a+.orlysync.distributed.v1.SyncStatusResponseBDZBgit.smesh.lol/orly/pkg/proto/orlysync/distributed/v1;distributedv1b\x06proto3"

var (
	file_orlysync_distributed_v1_service_proto_rawDescOnce sync.Once
	file_orlysync_distributed_v1_service_proto_rawDescData []byte
)

func file_orlysync_distributed_v1_service_proto_rawDescGZIP() []byte {
	file_orlysync_distributed_v1_service_proto_rawDescOnce.Do(func() {
		file_orlysync_distributed_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orlysync_distributed_v1_service_proto_rawDesc), len(file_orlysync_distributed_v1_service_proto_rawDesc)))
	})
	return file_orlysync_distributed_v1_service_proto_rawDescData
}

var file_orlysync_distributed_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orlysync_distributed_v1_service_proto_goTypes = []any{
	(*CurrentRequest)(nil),         // 0: orlysync.distributed.v1.CurrentRequest
	(*CurrentResponse)(nil),        // 1: orlysync.distributed.v1.CurrentResponse
	(*EventIDsRequest)(nil),        // 2: orlysync.distributed.v1.EventIDsRequest
	(*EventIDsResponse)(nil),       // 3: orlysync.distributed.v1.EventIDsResponse
	(*PeersResponse)(nil),          // 4: orlysync.distributed.v1.PeersResponse
	(*UpdatePeersRequest)(nil),     // 5: orlysync.distributed.v1.UpdatePeersRequest
	(*AuthorizedPeerRequest)(nil),  // 6: orlysync.distributed.v1.AuthorizedPeerRequest
	(*AuthorizedPeerResponse)(nil), // 7: orlysync.distributed.v1.AuthorizedPeerResponse
	(*PeerPubkeyRequest)(nil),      // 8: orlysync.distributed.v1.PeerPubkeyRequest
	(*PeerPubkeyResponse)(nil),     // 9: orlysync.distributed.v1.PeerPubkeyResponse
	(*NewEventNotification)(nil),   // 10: orlysync.distributed.v1.NewEventNotification
	(*SyncStatusResponse)(nil),     // 11: orlysync.distributed.v1.SyncStatusResponse
	nil,                            // 12: orlysync.distributed.v1.EventIDsResponse.EventMapEntry
	(*v1.PeerInfo)(nil),            // 13: orlysync.common.v1.PeerInfo
	(*v1.Empty)(nil),               // 14: orlysync.common.v1.Empty
	(*v1.HTTPRequest)(nil),         // 15: orlysync.common.v1.HTTPRequest
	(*v1.ReadyResponse)(nil),       // 16: orlysync.common.v1.ReadyResponse
	(*v1.SyncInfo)(nil),            // 17: orlysync.common.v1.SyncInfo
	(*v1.HTTPResponse)(nil),        // 18: orlysync.common.v1.HTTPResponse
}
var file_orlysync_distributed_v1_service_proto_depIdxs = []int32{
	12, // 0: orlysync.distributed.v1.EventIDsResponse.event_map:type_name -> orlysync.distributed.v1.EventIDsResponse.EventMapEntry
	13, // 1: orlysync.distributed.v1.SyncStatusResponse.peers:type_name -> orlysync.common.v1.PeerInfo
	14, // 2: orlysync.distributed.v1.DistributedSyncService.Ready:input_type -> orlysync.common.v1.Empty
	14, // 3: orlysync.distributed.v1.DistributedSyncService.GetInfo:input_type -> orlysync.common.v1.Empty
	0,  // 4: orlysync.distributed.v1.DistributedSyncService.GetCurrentSerial:input_type -> orlysync.distributed.v1.CurrentRequest
	2,  // 5: orlysync.distributed.v1.DistributedSyncService.GetEventIDs:input_type -> orlysync.distributed.v1.EventIDsRequest
	15, // 6: orlysync.distributed.v1.DistributedSyncService.HandleCurrentRequest:input_type -> orlysync.common.v1.HTTPRequest
	15, // 7: orlysync.distributed.v1.DistributedSyncService.HandleEventIDsRequest:input_type -> orlysync.common.v1.HTTPRequest
	14, // 8: orlysync.distributed.v1.DistributedSyncService.GetPeers:input_type -> orlysync.common.v1.Empty
	5,  // 9: orlysync.distributed.v1.DistributedSyncService.UpdatePeers:input_type -> orlysync.distributed.v1.UpdatePeersRequest
	6,  // 10: orlysync.distributed.v1.DistributedSyncService.IsAuthorizedPeer:input_type -> orlysync.distributed.v1.AuthorizedPeerRequest
	8,  // 11: orlysync.distributed.v1.DistributedSyncService.GetPeerPubkey:input_type -> orlysync.distributed.v1.PeerPubkeyRequest
	14, // 12: orlysync.distributed.v1.DistributedSyncService.UpdateSerial:input_type -> orlysync.common.v1.Empty
	10, // 13: orlysync.distributed.v1.DistributedSyncService.NotifyNewEvent:input_type -> orlysync.distributed.v1.NewEventNotification
	14, // 14: orlysync.distributed.v1.DistributedSyncService.TriggerSync:input_type -> orlysync.common.v1.Empty
	14, // 15: orlysync.distributed.v1.DistributedSyncService.GetSyncStatus:input_type -> orlysync.common.v1.Empty
	16, // 16: orlysync.distributed.v1.DistributedSyncService.Ready:output_type -> orlysync.common.v1.ReadyResponse
	17, // 17: orlysync.distributed.v1.DistributedSyncService.GetInfo:output_type -> orlysync.common.v1.SyncInfo
	1,  // 18: orlysync.distributed.v1.DistributedSyncService.GetCurrentSerial:output_type -> orlysync.distributed.v1.CurrentResponse
	3,  // 19: orlysync.distributed.v1.DistributedSyncService.GetEventIDs:output_type -> orlysync.distributed.v1.EventIDsResponse
	18, // 20: orlysync.distributed.v1.DistributedSyncService.HandleCurrentRequest:output_type -> orlysync.common.v1.HTTPResponse
	18, // 21: orlysync.distributed.v1.DistributedSyncService.HandleEventIDsRequest:output_type -> orlysync.common.v1.HTTPResponse
	4,  // 22: orlysync.distributed.v1.DistributedSyncService.GetPeers:output_type -> orlysync.distributed.v1.PeersResponse
	14, // 23: orlysync.distributed.v1.DistributedSyncService.UpdatePeers:output_type -> orlysync.common.v1.Empty
	7,  // 24: orlysync.distributed.v1.DistributedSyncService.IsAuthorizedPeer:output_type -> orlysync.distributed.v1.AuthorizedPeerResponse
	9,  // 25: orlysync.distributed.v1.DistributedSyncService.GetPeerPubkey:output_type -> orlysync.distributed.v1.PeerPubkeyResponse
	14, // 26: orlysync.distributed.v1.DistributedSyncService.UpdateSerial:output_type -> orlysync.common.v1.Empty
	14, // 27: orlysync.distributed.v1.DistributedSyncService.NotifyNewEvent:output_type -> orlysync.common.v1.Empty
	14, // 28: orlysync.distributed.v1.DistributedSyncService.TriggerSync:output_type -> orlysync.common.v1.Empty
	11, // 29: orlysync.distributed.v1.DistributedSyncService.GetSyncStatus:output_type -> orlysync.distributed.v1.SyncStatusResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_orlysync_distributed_v1_service_proto_init() }
func file_orlysync_distributed_v1_service_proto_init() {
	if File_orlysync_distributed_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orlysync_distributed_v1_service_proto_rawDesc), len(file_orlysync_distributed_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orlysync_distributed_v1_service_proto_goTypes,
		DependencyIndexes: file_orlysync_distributed_v1_service_proto_depIdxs,
		MessageInfos:      file_orlysync_distributed_v1_service_proto_msgTypes,
	}.Build()
	File_orlysync_distributed_v1_service_proto = out.File
	file_orlysync_distributed_v1_service_proto_goTypes = nil
	file_orlysync_distributed_v1_service_proto_depIdxs = nil
}
