// Package sw-marmot
// Generated by TinyJS — TinyGo JavaScript backend

import * as $rt from './$runtime/index.mjs';

import * as common$crypto$secp256k1 from './common_crypto_secp256k1.mjs';
import * as common$crypto$sha256 from './common_crypto_sha256.mjs';
import * as common$helpers from './common_helpers.mjs';
import * as common$jsbridge$subtle from './common_jsbridge_subtle.mjs';
import * as common$jsbridge$sw from './common_jsbridge_sw.mjs';
import * as common$jsbridge$ws from './common_jsbridge_ws.mjs';

// Package-level variables
export let seckey = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let hasKey = { $value: false, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let myPubkey = { $value: '', $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let cryptoCBs = { $value: null, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let nextCryptoID = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let busConn = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let busReady = { $value: false, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let marmotConn = { $value: 0, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let marmotReady = { $value: false, $get() { return this.$value; }, $set(v) { this.$value = v; } };
export let marmotPending = { $value: null, $get() { return this.$value; }, $set(v) { this.$value = v; } };

$rt.types.registerType('sw-marmot.DMRecord', {
  id: 'sw-marmot.DMRecord',
  kind: 'struct',
  methods: new Map(),
  fields: [
    { name: 'ID', type: 'string', tag: '', embedded: false },
    { name: 'Peer', type: 'string', tag: '', embedded: false },
    { name: 'From', type: 'string', tag: '', embedded: false },
    { name: 'Content', type: 'string', tag: '', embedded: false },
    { name: 'CreatedAt', type: 'int64', tag: '', embedded: false },
    { name: 'Protocol', type: 'string', tag: '', embedded: false },
    { name: 'EventID', type: 'string', tag: '', embedded: false },
  ],
  zero: () => ({ ID: '', Peer: '', From: '', Content: '', CreatedAt: 0, Protocol: '', EventID: '' }),
});
$rt.types.registerType('sw-marmot.mw', {
  id: 'sw-marmot.mw',
  kind: 'struct',
  methods: new Map(),
  fields: [
    { name: 's', type: 'string', tag: '', embedded: false },
    { name: 'i', type: 'int', tag: '', embedded: false },
  ],
  zero: () => ({ s: '', i: 0 }),
});
export function init() {
  return;
}

export function identitySetKey(hexKey) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = hexTo32(hexKey);
        seckey.$set($rt.builtin.cloneValue($t0_1));
        hasKey.$set(true);
        $t1_2 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t2_3 = seckey.$get();
        $t3_4 = common$crypto$secp256k1.PubKeyFromSecKey($t2_3);
        $t4_5 = $t3_4[0];
        $t1_2.$set($rt.builtin.cloneValue($t4_5));
        $t5_6 = $t3_4[1];
        if ($t5_6) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        $t6_7 = $rt.builtin.sliceSlice($t1_2.$get(), undefined, undefined, undefined);
        $t7_8 = common$helpers.HexEncode($t6_7);
        myPubkey.$set($t7_8);
        $block = 2; break;
        break;
      }
      case 2: {
        return;
        break;
      }
    }
  }
}

export function identitySetPubkey(hex) {
  myPubkey.$set(hex);
  return;
}

export function identityClearKey() {
  seckey.$set($rt.builtin.cloneValue($rt.builtin.makeSlice(32, 32, 0)));
  hasKey.$set(false);
  myPubkey.$set('');
  return;
}

export function makeDMRecord(peer, from, content, createdAt, protocol, eventID) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9;
  $t0_1 = { $value: { ID: '', Peer: '', From: '', Content: '', CreatedAt: 0, Protocol: '', EventID: '' }, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = { $get() { return $t0_1.$get().ID; }, $set(v) { const obj = $t0_1.$get(); obj.ID = v; $t0_1.$set(obj); } };
  $t2_3 = dmDedupID(peer, content, createdAt);
  $t3_4 = { $get() { return $t0_1.$get().Peer; }, $set(v) { const obj = $t0_1.$get(); obj.Peer = v; $t0_1.$set(obj); } };
  $t4_5 = { $get() { return $t0_1.$get().From; }, $set(v) { const obj = $t0_1.$get(); obj.From = v; $t0_1.$set(obj); } };
  $t5_6 = { $get() { return $t0_1.$get().Content; }, $set(v) { const obj = $t0_1.$get(); obj.Content = v; $t0_1.$set(obj); } };
  $t6_7 = { $get() { return $t0_1.$get().CreatedAt; }, $set(v) { const obj = $t0_1.$get(); obj.CreatedAt = v; $t0_1.$set(obj); } };
  $t7_8 = { $get() { return $t0_1.$get().Protocol; }, $set(v) { const obj = $t0_1.$get(); obj.Protocol = v; $t0_1.$set(obj); } };
  $t8_9 = { $get() { return $t0_1.$get().EventID; }, $set(v) { const obj = $t0_1.$get(); obj.EventID = v; $t0_1.$set(obj); } };
  $t1_2.$set($t2_3);
  $t3_4.$set(peer);
  $t4_5.$set(from);
  $t5_6.$set(content);
  $t6_7.$set(createdAt);
  $t7_8.$set(protocol);
  $t8_9.$set(eventID);
  return $t0_1;
}

export function dmDedupID(peer, content, createdAt) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14;
  $t0_1 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = $rt.builtin.stringToBytes(content);
  $t2_3 = common$crypto$sha256.Sum($t1_2);
  $t0_1.$set($rt.builtin.cloneValue($t2_3));
  $t3_4 = Math.trunc(createdAt / 300);
  $t4_5 = common$helpers.Itoa($t3_4);
  $t5_6 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t6_7 = $rt.builtin.sliceSlice($t0_1.$get(), undefined, undefined, undefined);
  $t7_8 = common$helpers.HexEncode($t6_7);
  $t8_9 = (peer + $t7_8);
  $t9_10 = ($t8_9 + $t4_5);
  $t10_11 = $rt.builtin.stringToBytes($t9_10);
  $t11_12 = common$crypto$sha256.Sum($t10_11);
  $t5_6.$set($rt.builtin.cloneValue($t11_12));
  $t12_13 = $rt.builtin.sliceSlice($t5_6.$get(), undefined, undefined, undefined);
  $t13_14 = common$helpers.HexEncode($t12_13);
  return $t13_14;
}

export function initSharedState() {
  let $t0_1;
  $t0_1 = $rt.builtin.makeMap('int');
  cryptoCBs.$set($t0_1);
  return;
}

export function cryptoProxy(method, peerPubkey, data, cb) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21;
  $t0_1 = nextCryptoID.$get();
  $t1_2 = nextCryptoID.$get();
  $t2_3 = ($t1_2 + 1);
  nextCryptoID.$set($t2_3);
  $t3_4 = cryptoCBs.$get();
  $rt.builtin.mapUpdate($t3_4, $t0_1, cb);
  $t4_5 = jstr('marmot');
  $t5_6 = ('["CRYPTO_REQ",' + $t4_5);
  $t6_7 = ($t5_6 + ',');
  $t7_8 = $t0_1;
  $t8_9 = common$helpers.Itoa($t7_8);
  $t9_10 = ($t6_7 + $t8_9);
  $t10_11 = ($t9_10 + ',');
  $t11_12 = jstr(method);
  $t12_13 = ($t10_11 + $t11_12);
  $t13_14 = ($t12_13 + ',');
  $t14_15 = jstr(peerPubkey);
  $t15_16 = ($t13_14 + $t14_15);
  $t16_17 = ($t15_16 + ',');
  $t17_18 = jstr(data);
  $t18_19 = ($t16_17 + $t17_18);
  $t19_20 = ($t18_19 + ']');
  $t20_21 = busSend('shell', $t19_20);
  return;
}

export function jstr(s) {
  let $t0_1;
  $t0_1 = common$helpers.JsonString(s);
  return $t0_1;
}

export function hexTo32(s) {
  let $t0_1, $t1_2, $t2_3;
  $t0_1 = common$helpers.HexDecode32(s);
  $t1_2 = $t0_1[0];
  $t2_3 = $t0_1[1];
  return $t1_2;
}

export function random32() {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  $t0_1 = { $value: $rt.builtin.makeSlice(32, 32, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t1_2 = $rt.builtin.sliceSlice($t0_1.$get(), undefined, undefined, undefined);
  $t2_3 = common$jsbridge$subtle.RandomBytes($t1_2);
  $t3_4 = $t0_1.$get();
  return $t3_4;
}

export function newMW(s) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = { $value: { s: '', i: 0 }, $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t1_2 = { $get() { return $t0_1.$get().s; }, $set(v) { const obj = $t0_1.$get(); obj.s = v; $t0_1.$set(obj); } };
        $t1_2.$set(s);
        $block = 3; break;
        break;
      }
      case 1: {
        $t2_3 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t3_4 = $t2_3.$get();
        $t4_5 = ($t3_4 + 1);
        $t5_6 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t5_6.$set($t4_5);
        $block = 3; break;
        break;
      }
      case 2: {
        $t6_7 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t7_8 = $t6_7.$get();
        $t8_9 = $rt.builtin.len(s);
        $t9_10 = ($t7_8 < $t8_9);
        if ($t9_10) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 3: {
        $t10_11 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t11_12 = $t10_11.$get();
        $t12_13 = $rt.builtin.len(s);
        $t13_14 = ($t11_12 < $t12_13);
        if ($t13_14) {
          $block = 4; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t14_15 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t15_16 = $t14_15.$get();
        $rt.runtime.boundsCheck($t15_16, $rt.builtin.byteLen(s));
        $t16_17 = $rt.builtin.stringByteAt(s, $t15_16);
        $t17_18 = ($t16_17 !== 91);
        if ($t17_18) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 5: {
        $t18_19 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t19_20 = $t18_19.$get();
        $t20_21 = ($t19_20 + 1);
        $t21_22 = { $get() { return $t0_1.$get().i; }, $set(v) { const obj = $t0_1.$get(); obj.i = v; $t0_1.$set(obj); } };
        $t21_22.$set($t20_21);
        $block = 6; break;
        break;
      }
      case 6: {
        $t22_23 = $t0_1.$get();
        return $t22_23;
        break;
      }
    }
  }
}

export function skipval(s, i) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = $rt.builtin.len(s);
        $t1_2 = (i >= $t0_1);
        if ($t1_2) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        return -1;
        break;
      }
      case 2: {
        $rt.runtime.boundsCheck(i, $rt.builtin.byteLen(s));
        $t2_3 = $rt.builtin.stringByteAt(s, i);
        $t3_4 = ($t2_3 === 34);
        if ($t3_4) {
          $block = 3; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 3: {
        $t4_5 = (i + 1);
        $t9_10 = $t4_5;
        $block = 8; break;
        break;
      }
      case 4: {
        $t5_6 = skipBrack(s, i, 123, 125);
        return $t5_6;
        break;
      }
      case 5: {
        $t6_7 = ($t2_3 === 123);
        if ($t6_7) {
          $block = 4; break;
        }
        else {
          $block = 14; break;
        }
        break;
      }
      case 6: {
        $rt.runtime.boundsCheck($t9_10, $rt.builtin.byteLen(s));
        $t7_8 = $rt.builtin.stringByteAt(s, $t9_10);
        $t8_9 = ($t7_8 === 92);
        if ($t8_9) {
          $block = 9; break;
        }
        else {
          $block = 10; break;
        }
        break;
      }
      case 7: {
        return -1;
        break;
      }
      case 8: {
        $t10_11 = $rt.builtin.len(s);
        $t11_12 = ($t9_10 < $t10_11);
        if ($t11_12) {
          $block = 6; break;
        }
        else {
          $block = 7; break;
        }
        break;
      }
      case 9: {
        $t12_13 = ($t9_10 + 2);
        $t9_10 = $t12_13;
        $block = 8; break;
        break;
      }
      case 10: {
        $rt.runtime.boundsCheck($t9_10, $rt.builtin.byteLen(s));
        $t13_14 = $rt.builtin.stringByteAt(s, $t9_10);
        $t14_15 = ($t13_14 === 34);
        if ($t14_15) {
          $block = 11; break;
        }
        else {
          $block = 12; break;
        }
        break;
      }
      case 11: {
        $t15_16 = ($t9_10 + 1);
        return $t15_16;
        break;
      }
      case 12: {
        $t16_17 = ($t9_10 + 1);
        $t9_10 = $t16_17;
        $block = 8; break;
        break;
      }
      case 13: {
        $t17_18 = skipBrack(s, i, 91, 93);
        return $t17_18;
        break;
      }
      case 14: {
        $t18_19 = ($t2_3 === 91);
        if ($t18_19) {
          $block = 13; break;
        }
        else {
          $block = 16; break;
        }
        break;
      }
      case 15: {
        $t19_20 = (i + 4);
        $t20_21 = $rt.builtin.len(s);
        $t21_22 = ($t19_20 <= $t20_21);
        if ($t21_22) {
          $block = 19; break;
        }
        else {
          $block = 20; break;
        }
        break;
      }
      case 16: {
        $t22_23 = ($t2_3 === 116);
        if ($t22_23) {
          $block = 15; break;
        }
        else {
          $block = 18; break;
        }
        break;
      }
      case 17: {
        $t23_24 = (i + 5);
        $t24_25 = $rt.builtin.len(s);
        $t25_26 = ($t23_24 <= $t24_25);
        if ($t25_26) {
          $block = 23; break;
        }
        else {
          $block = 24; break;
        }
        break;
      }
      case 18: {
        $t26_27 = ($t2_3 === 102);
        if ($t26_27) {
          $block = 17; break;
        }
        else {
          $block = 22; break;
        }
        break;
      }
      case 19: {
        $t27_28 = (i + 4);
        return $t27_28;
        break;
      }
      case 20: {
        return -1;
        break;
      }
      case 21: {
        $t28_29 = (i + 4);
        $t29_30 = $rt.builtin.len(s);
        $t30_31 = ($t28_29 <= $t29_30);
        if ($t30_31) {
          $block = 25; break;
        }
        else {
          $block = 26; break;
        }
        break;
      }
      case 22: {
        $t31_32 = ($t2_3 === 110);
        if ($t31_32) {
          $block = 21; break;
        }
        else {
          $t35_36 = i;
          $block = 29; break;
        }
        break;
      }
      case 23: {
        $t32_33 = (i + 5);
        return $t32_33;
        break;
      }
      case 24: {
        return -1;
        break;
      }
      case 25: {
        $t33_34 = (i + 4);
        return $t33_34;
        break;
      }
      case 26: {
        return -1;
        break;
      }
      case 27: {
        $t34_35 = ($t35_36 + 1);
        $t35_36 = $t34_35;
        $block = 29; break;
        break;
      }
      case 28: {
        return $t35_36;
        break;
      }
      case 29: {
        $t36_37 = $rt.builtin.len(s);
        $t37_38 = ($t35_36 < $t36_37);
        if ($t37_38) {
          $block = 34; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
      case 30: {
        $rt.runtime.boundsCheck($t35_36, $rt.builtin.byteLen(s));
        $t38_39 = $rt.builtin.stringByteAt(s, $t35_36);
        $t39_40 = ($t38_39 !== 10);
        if ($t39_40) {
          $block = 27; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
      case 31: {
        $rt.runtime.boundsCheck($t35_36, $rt.builtin.byteLen(s));
        $t40_41 = $rt.builtin.stringByteAt(s, $t35_36);
        $t41_42 = ($t40_41 !== 32);
        if ($t41_42) {
          $block = 30; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
      case 32: {
        $rt.runtime.boundsCheck($t35_36, $rt.builtin.byteLen(s));
        $t42_43 = $rt.builtin.stringByteAt(s, $t35_36);
        $t43_44 = ($t42_43 !== 93);
        if ($t43_44) {
          $block = 31; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
      case 33: {
        $rt.runtime.boundsCheck($t35_36, $rt.builtin.byteLen(s));
        $t44_45 = $rt.builtin.stringByteAt(s, $t35_36);
        $t45_46 = ($t44_45 !== 125);
        if ($t45_46) {
          $block = 32; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
      case 34: {
        $rt.runtime.boundsCheck($t35_36, $rt.builtin.byteLen(s));
        $t46_47 = $rt.builtin.stringByteAt(s, $t35_36);
        $t47_48 = ($t46_47 !== 44);
        if ($t47_48) {
          $block = 33; break;
        }
        else {
          $block = 28; break;
        }
        break;
      }
    }
  }
}

export function skipBrack(s, i, open, close) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = (i + 1);
        $t2_3 = $t0_1;
        $t3_4 = 1;
        $t4_5 = false;
        $block = 3; break;
        break;
      }
      case 1: {
        if ($t4_5) {
          $block = 5; break;
        }
        else {
          $block = 7; break;
        }
        break;
      }
      case 2: {
        $t1_2 = ($t3_4 !== 0);
        if ($t1_2) {
          $block = 16; break;
        }
        else {
          $block = 17; break;
        }
        break;
      }
      case 3: {
        $t5_6 = $rt.builtin.len(s);
        $t6_7 = ($t2_3 < $t5_6);
        if ($t6_7) {
          $block = 4; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t7_8 = ($t3_4 > 0);
        if ($t7_8) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 5: {
        $rt.runtime.boundsCheck($t2_3, $rt.builtin.byteLen(s));
        $t8_9 = $rt.builtin.stringByteAt(s, $t2_3);
        $t9_10 = ($t8_9 === 92);
        if ($t9_10) {
          $block = 8; break;
        }
        else {
          $block = 9; break;
        }
        break;
      }
      case 6: {
        $t13_14 = ($t10_11 + 1);
        $t2_3 = $t13_14;
        $t3_4 = $t11_12;
        $t4_5 = $t12_13;
        $block = 3; break;
        break;
      }
      case 7: {
        $rt.runtime.boundsCheck($t2_3, $rt.builtin.byteLen(s));
        $t14_15 = $rt.builtin.stringByteAt(s, $t2_3);
        $t15_16 = ($t14_15 === 34);
        if ($t15_16) {
          $block = 11; break;
        }
        else {
          $block = 13; break;
        }
        break;
      }
      case 8: {
        $t16_17 = ($t2_3 + 1);
        $t10_11 = $t16_17;
        $t11_12 = $t3_4;
        $t12_13 = $t4_5;
        $block = 6; break;
        break;
      }
      case 9: {
        $rt.runtime.boundsCheck($t2_3, $rt.builtin.byteLen(s));
        $t17_18 = $rt.builtin.stringByteAt(s, $t2_3);
        $t18_19 = ($t17_18 === 34);
        if ($t18_19) {
          $block = 10; break;
        }
        else {
          $t10_11 = $t2_3;
          $t11_12 = $t3_4;
          $t12_13 = $t4_5;
          $block = 6; break;
        }
        break;
      }
      case 10: {
        $t10_11 = $t2_3;
        $t11_12 = $t3_4;
        $t12_13 = false;
        $block = 6; break;
        break;
      }
      case 11: {
        $t10_11 = $t2_3;
        $t11_12 = $t3_4;
        $t12_13 = true;
        $block = 6; break;
        break;
      }
      case 12: {
        $t19_20 = ($t3_4 + 1);
        $t10_11 = $t2_3;
        $t11_12 = $t19_20;
        $t12_13 = $t4_5;
        $block = 6; break;
        break;
      }
      case 13: {
        $t20_21 = ($t14_15 === open);
        if ($t20_21) {
          $block = 12; break;
        }
        else {
          $block = 15; break;
        }
        break;
      }
      case 14: {
        $t21_22 = ($t3_4 - 1);
        $t10_11 = $t2_3;
        $t11_12 = $t21_22;
        $t12_13 = $t4_5;
        $block = 6; break;
        break;
      }
      case 15: {
        $t22_23 = ($t14_15 === close);
        if ($t22_23) {
          $block = 14; break;
        }
        else {
          $t10_11 = $t2_3;
          $t11_12 = $t3_4;
          $t12_13 = $t4_5;
          $block = 6; break;
        }
        break;
      }
      case 16: {
        return -1;
        break;
      }
      case 17: {
        return $t2_3;
        break;
      }
    }
  }
}

export function main() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5;
  $t0_1 = initSharedState();
  $t1_2 = common$jsbridge$sw.OnInstall(onInstall);
  $t2_3 = common$jsbridge$sw.OnActivate(onActivate);
  $t3_4 = common$jsbridge$sw.OnFetch(onFetch);
  $t4_5 = common$jsbridge$sw.OnMessage(onMessage);
  return;
}

export function onInstall(event) {
  let $t0_1;
  $t0_1 = common$jsbridge$sw.WaitUntil(event, onInstall$1);
  return;
}

function onInstall$1(done) {
  let $t0_1, $t1_2;
  $t0_1 = common$jsbridge$sw.SkipWaiting();
  $t1_2 = done();
  return;
}

export function onActivate(event) {
  let $t0_1;
  $t0_1 = common$jsbridge$sw.WaitUntil(event, onActivate$1);
  return;
}

function onActivate$1(done) {
  let $t0_1, $t1_2, $t2_3;
  $t0_1 = { $value: null, $get() { return this.$value; }, $set(v) { this.$value = v; } };
  $t0_1.$set(done);
  $t1_2 = onActivate$1$1.bind(null, $t0_1);
  $t2_3 = common$jsbridge$sw.ClaimClients($t1_2);
  return;
}

function onActivate$1$1(done) {
  let $t0_1, $t1_2, $t2_3;
  $t0_1 = connectBus();
  $t1_2 = done.$get();
  $t2_3 = $t1_2();
  return;
}

export function onFetch(event) {
  return;
}

export function onMessage(event) {
  return;
}

export function connectBus() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = common$jsbridge$sw.Origin();
        $t1_2 = $rt.builtin.len($t0_1);
        $t2_3 = ($t1_2 > 5);
        if ($t2_3) {
          $block = 4; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 1: {
        $t3_4 = $rt.builtin.stringSlice($t0_1, 5, undefined);
        $t4_5 = ('wss' + $t3_4);
        $t5_6 = $t4_5;
        $block = 2; break;
        break;
      }
      case 2: {
        $t6_7 = ($t5_6 + '/__bus');
        $t7_8 = common$jsbridge$sw.Log('marmot-sw: connecting to bus');
        $t8_9 = common$jsbridge$ws.Dial($t6_7, connectBus$1, connectBus$2, connectBus$3, connectBus$4);
        busConn.$set($t8_9);
        return;
        break;
      }
      case 3: {
        $t9_10 = $rt.builtin.len($t0_1);
        $t10_11 = ($t9_10 > 4);
        if ($t10_11) {
          $block = 6; break;
        }
        else {
          $t5_6 = $t0_1;
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t11_12 = $rt.builtin.stringSlice($t0_1, undefined, 5);
        $t12_13 = ($t11_12 === 'https');
        if ($t12_13) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 5: {
        $t13_14 = $rt.builtin.stringSlice($t0_1, 4, undefined);
        $t14_15 = ('ws' + $t13_14);
        $t5_6 = $t14_15;
        $block = 2; break;
        break;
      }
      case 6: {
        $t15_16 = $rt.builtin.stringSlice($t0_1, undefined, 4);
        $t16_17 = ($t15_16 === 'http');
        if ($t16_17) {
          $block = 5; break;
        }
        else {
          $t5_6 = $t0_1;
          $block = 2; break;
        }
        break;
      }
    }
  }
}

function connectBus$1(connID, msg) {
  let $t0_1;
  $t0_1 = onBusMessage(msg);
  return;
}

function connectBus$2(connID) {
  let $t0_1;
  $t0_1 = onBusOpen();
  return;
}

function connectBus$3(connID, code, reason) {
  let $t0_1, $t1_2;
  $t0_1 = common$jsbridge$sw.Log('marmot-sw: bus closed');
  busReady.$set(false);
  $t1_2 = common$jsbridge$sw.SetTimeout(2000, connectBus$3$1);
  return;
}

function connectBus$3$1() {
  let $t0_1;
  $t0_1 = connectBus();
  return;
}

function connectBus$4(connID) {
  let $t0_1;
  busReady.$set(false);
  $t0_1 = common$jsbridge$sw.SetTimeout(2000, connectBus$4$1);
  return;
}

function connectBus$4$1() {
  let $t0_1;
  $t0_1 = connectBus();
  return;
}

export function onBusOpen() {
  let $t0_1, $t1_2, $t2_3;
  busReady.$set(true);
  $t0_1 = common$jsbridge$sw.Log('marmot-sw: bus connected');
  $t1_2 = busConn.$get();
  $t2_3 = common$jsbridge$ws.Send($t1_2, '{"role":"marmot"}');
  return;
}

export function busSend(to, msg) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = busReady.$get();
        if ($t0_1) {
          $block = 2; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 1: {
        return;
        break;
      }
      case 2: {
        $t1_2 = busConn.$get();
        $t2_3 = jstr(to);
        $t3_4 = ('{"to":' + $t2_3);
        $t4_5 = ($t3_4 + ',"msg":');
        $t5_6 = ($t4_5 + msg);
        $t6_7 = ($t5_6 + '}');
        $t7_8 = common$jsbridge$ws.Send($t1_2, $t6_7);
        return;
        break;
      }
    }
  }
}

export function onBusMessage(msg) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = $rt.builtin.len(msg);
        $t1_2 = Math.min($t0_1, 80);
        $t2_3 = $rt.builtin.stringSlice(msg, undefined, $t1_2);
        $t3_4 = ('marmot-sw: bus: ' + $t2_3);
        $t4_5 = common$jsbridge$sw.Log($t3_4);
        $t5_6 = { $value: { s: '', i: 0 }, $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t6_7 = newMW(msg);
        $t5_6.$set($rt.builtin.cloneValue($t6_7));
        $t7_8 = mw$str($t5_6);
        $t8_9 = ($t7_8 === 'SET_KEY');
        if ($t8_9) {
          $block = 2; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 1: {
        return;
        break;
      }
      case 2: {
        $t9_10 = mw$str($t5_6);
        $t10_11 = identitySetKey($t9_10);
        $block = 1; break;
        break;
      }
      case 3: {
        $t11_12 = mw$str($t5_6);
        $t12_13 = identitySetPubkey($t11_12);
        $block = 1; break;
        break;
      }
      case 4: {
        $t13_14 = ($t7_8 === 'SET_PUBKEY');
        if ($t13_14) {
          $block = 3; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 5: {
        $t14_15 = identityClearKey();
        $block = 1; break;
        break;
      }
      case 6: {
        $t15_16 = ($t7_8 === 'CLEAR_KEY');
        if ($t15_16) {
          $block = 5; break;
        }
        else {
          $block = 8; break;
        }
        break;
      }
      case 7: {
        $t16_17 = mw$strs($t5_6);
        $t17_18 = marmotInit($t16_17);
        $block = 1; break;
        break;
      }
      case 8: {
        $t18_19 = ($t7_8 === 'MLS_INIT');
        if ($t18_19) {
          $block = 7; break;
        }
        else {
          $block = 10; break;
        }
        break;
      }
      case 9: {
        $t19_20 = mw$str($t5_6);
        $t20_21 = mw$str($t5_6);
        $t21_22 = marmotSend($t19_20, $t20_21);
        $block = 1; break;
        break;
      }
      case 10: {
        $t22_23 = ($t7_8 === 'MLS_SEND');
        if ($t22_23) {
          $block = 9; break;
        }
        else {
          $block = 12; break;
        }
        break;
      }
      case 11: {
        $t23_24 = marmotSubscribe();
        $block = 1; break;
        break;
      }
      case 12: {
        $t24_25 = ($t7_8 === 'MLS_SUB');
        if ($t24_25) {
          $block = 11; break;
        }
        else {
          $block = 14; break;
        }
        break;
      }
      case 13: {
        $t25_26 = mw$strs($t5_6);
        $t26_27 = marmotPublishKP($t25_26);
        $block = 1; break;
        break;
      }
      case 14: {
        $t27_28 = ($t7_8 === 'MLS_PUBLISH_KP');
        if ($t27_28) {
          $block = 13; break;
        }
        else {
          $block = 16; break;
        }
        break;
      }
      case 15: {
        $t28_29 = marmotListGroups();
        $block = 1; break;
        break;
      }
      case 16: {
        $t29_30 = ($t7_8 === 'MLS_LIST_GROUPS');
        if ($t29_30) {
          $block = 15; break;
        }
        else {
          $block = 18; break;
        }
        break;
      }
      case 17: {
        $t30_31 = mw$num($t5_6);
        $t31_32 = $t30_31;
        $t32_33 = mw$str($t5_6);
        $t33_34 = mw$str($t5_6);
        $t34_35 = cryptoCBs.$get();
        { const $r = $rt.builtin.mapLookup($t34_35, $t31_32); $t35_36 = [$r.value, $r.ok]; }
        $t36_37 = $t35_36[0];
        $t37_38 = $t35_36[1];
        if ($t37_38) {
          $block = 19; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 18: {
        $t38_39 = ($t7_8 === 'CRYPTO_RESULT');
        if ($t38_39) {
          $block = 17; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 19: {
        $t39_40 = cryptoCBs.$get();
        $t40_41 = $rt.builtin.mapDelete($t39_40, $t31_32);
        $t41_42 = $t36_37($t32_33, $t33_34);
        $block = 1; break;
        break;
      }
    }
  }
}

export function marmotInit(relayURLs) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = marmotReady.$get();
        if ($t0_1) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        return;
        break;
      }
      case 2: {
        $t1_2 = common$jsbridge$sw.Origin();
        $t2_3 = ('marmot-sw: connecting to ' + $t1_2);
        $t3_4 = ($t2_3 + '/__marmot');
        $t4_5 = common$jsbridge$sw.Log($t3_4);
        $t5_6 = $rt.builtin.len($t1_2);
        $t6_7 = ($t5_6 > 5);
        if ($t6_7) {
          $block = 6; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 3: {
        $t7_8 = $rt.builtin.stringSlice($t1_2, 5, undefined);
        $t8_9 = ('wss' + $t7_8);
        $t9_10 = $t8_9;
        $block = 4; break;
        break;
      }
      case 4: {
        $t10_11 = ($t9_10 + '/__marmot');
        marmotPending.$set(null);
        $t11_12 = common$jsbridge$ws.Dial($t10_11, marmotInit$1, marmotInit$2, marmotInit$3, marmotInit$4);
        marmotConn.$set($t11_12);
        return;
        break;
      }
      case 5: {
        $t12_13 = $rt.builtin.len($t1_2);
        $t13_14 = ($t12_13 > 4);
        if ($t13_14) {
          $block = 8; break;
        }
        else {
          $t9_10 = $t1_2;
          $block = 4; break;
        }
        break;
      }
      case 6: {
        $t14_15 = $rt.builtin.stringSlice($t1_2, undefined, 5);
        $t15_16 = ($t14_15 === 'https');
        if ($t15_16) {
          $block = 3; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 7: {
        $t16_17 = $rt.builtin.stringSlice($t1_2, 4, undefined);
        $t17_18 = ('ws' + $t16_17);
        $t9_10 = $t17_18;
        $block = 4; break;
        break;
      }
      case 8: {
        $t18_19 = $rt.builtin.stringSlice($t1_2, undefined, 4);
        $t19_20 = ($t18_19 === 'http');
        if ($t19_20) {
          $block = 7; break;
        }
        else {
          $t9_10 = $t1_2;
          $block = 4; break;
        }
        break;
      }
    }
  }
}

function marmotInit$1(connID, msg) {
  let $t0_1;
  $t0_1 = marmotOnMessage(msg);
  return;
}

function marmotInit$2(connID) {
  let $t0_1;
  $t0_1 = marmotOnOpen();
  return;
}

function marmotInit$3(connID, code, reason) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5;
  $t0_1 = code;
  $t1_2 = common$helpers.Itoa($t0_1);
  $t2_3 = ('marmot-sw: marmot ws closed code=' + $t1_2);
  $t3_4 = common$jsbridge$sw.Log($t2_3);
  $t4_5 = marmotOnClose();
  return;
}

function marmotInit$4(connID) {
  let $t0_1;
  $t0_1 = marmotOnClose();
  return;
}

export function marmotOnOpen() {
  let $t0_1, $t1_2, $t2_3, $t3_4;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        marmotReady.$set(true);
        $t0_1 = common$jsbridge$sw.Log('marmot-sw: marmot connected');
        $t1_2 = myPubkey.$get();
        $t2_3 = ($t1_2 !== '');
        if ($t2_3) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        $t3_4 = marmotAuth();
        $block = 2; break;
        break;
      }
      case 2: {
        return;
        break;
      }
    }
  }
}

export function marmotOnClose() {
  marmotReady.$set(false);
  return;
}

export function marmotAuth() {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = myPubkey.$get();
        $t1_2 = ($t0_1 === '');
        if ($t1_2) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        return;
        break;
      }
      case 2: {
        $t2_3 = hasKey.$get();
        if ($t2_3) {
          $block = 4; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 3: {
        $t3_4 = common$jsbridge$sw.NowSeconds();
        $t4_5 = common$helpers.Itoa($t3_4);
        $t5_6 = ('{"kind":22242,"content":"marmot-auth","tags":[],"created_at":' + $t4_5);
        $t6_7 = ($t5_6 + ',"pubkey":');
        $t7_8 = myPubkey.$get();
        $t8_9 = jstr($t7_8);
        $t9_10 = ($t6_7 + $t8_9);
        $t10_11 = ($t9_10 + '}');
        $t11_12 = cryptoProxy('signEvent', '', $t10_11, marmotAuth$1);
        return;
        break;
      }
      case 4: {
        $t12_13 = myPubkey.$get();
        $t13_14 = common$helpers.HexDecode($t12_13);
        $t14_15 = ($t13_14 === null);
        if ($t14_15) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 5: {
        return;
        break;
      }
      case 6: {
        $t15_16 = common$crypto$sha256.Sum($t13_14);
        $t16_17 = random32();
        $t17_18 = { $value: $rt.builtin.makeSlice(64, 64, 0), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t18_19 = seckey.$get();
        $t19_20 = common$crypto$secp256k1.SignSchnorr($t18_19, $t15_16, $t16_17);
        $t20_21 = $t19_20[0];
        $t17_18.$set($rt.builtin.cloneValue($t20_21));
        $t21_22 = $t19_20[1];
        if ($t21_22) {
          $block = 8; break;
        }
        else {
          $block = 7; break;
        }
        break;
      }
      case 7: {
        $t22_23 = common$jsbridge$sw.Log('marmot-sw: auth sign failed');
        return;
        break;
      }
      case 8: {
        $t23_24 = myPubkey.$get();
        $t24_25 = jstr($t23_24);
        $t25_26 = ('{"method":"auth","pubkey":' + $t24_25);
        $t26_27 = ($t25_26 + ',"sig":');
        $t27_28 = $rt.builtin.sliceSlice($t17_18.$get(), undefined, undefined, undefined);
        $t28_29 = common$helpers.HexEncode($t27_28);
        $t29_30 = jstr($t28_29);
        $t30_31 = ($t26_27 + $t29_30);
        $t31_32 = ($t30_31 + '}');
        $t32_33 = marmotSendJSON($t31_32);
        return;
        break;
      }
    }
  }
}

function marmotAuth$1(signedJSON, errMsg) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = (errMsg !== '');
        if ($t0_1) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 1: {
        $t1_2 = ('marmot-sw: extension sign failed: ' + errMsg);
        $t2_3 = common$jsbridge$sw.Log($t1_2);
        return;
        break;
      }
      case 2: {
        $t3_4 = ('{"method":"auth","event":' + signedJSON);
        $t4_5 = ($t3_4 + '}');
        $t5_6 = marmotSendJSON($t4_5);
        return;
        break;
      }
      case 3: {
        $t6_7 = (signedJSON === '');
        if ($t6_7) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
    }
  }
}

export function marmotSend(recipient, content) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7;
  $t0_1 = jstr(recipient);
  $t1_2 = ('{"method":"send_dm","recipient":' + $t0_1);
  $t2_3 = ($t1_2 + ',"content":');
  $t3_4 = jstr(content);
  $t4_5 = ($t2_3 + $t3_4);
  $t5_6 = ($t4_5 + '}');
  $t6_7 = marmotSendJSON($t5_6);
  return;
}

export function marmotSubscribe() {
  let $t0_1;
  $t0_1 = marmotSendJSON('{"method":"subscribe"}');
  return;
}

export function marmotPublishKP(relays) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = $rt.builtin.len(relays);
        $t1_2 = ($t0_1 > 0);
        if ($t1_2) {
          $block = 1; break;
        }
        else {
          $t4_5 = '{"method":"publish_kp"';
          $block = 2; break;
        }
        break;
      }
      case 1: {
        $t2_3 = ('{"method":"publish_kp"' + ',"relays":[');
        $t3_4 = $rt.builtin.len(relays);
        $t7_8 = $t2_3;
        $t8_9 = -1;
        $block = 3; break;
        break;
      }
      case 2: {
        $t5_6 = ($t4_5 + '}');
        $t6_7 = marmotSendJSON($t5_6);
        return;
        break;
      }
      case 3: {
        $t9_10 = ($t8_9 + 1);
        $t10_11 = ($t9_10 < $t3_4);
        if ($t10_11) {
          $block = 4; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 4: {
        $t11_12 = relays.addr($t9_10);
        $t12_13 = $t11_12.$get();
        $t13_14 = ($t9_10 > 0);
        if ($t13_14) {
          $block = 6; break;
        }
        else {
          $t16_17 = $t7_8;
          $block = 7; break;
        }
        break;
      }
      case 5: {
        $t14_15 = ($t7_8 + ']');
        $t4_5 = $t14_15;
        $block = 2; break;
        break;
      }
      case 6: {
        $t15_16 = ($t7_8 + ',');
        $t16_17 = $t15_16;
        $block = 7; break;
        break;
      }
      case 7: {
        $t17_18 = jstr($t12_13);
        $t18_19 = ($t16_17 + $t17_18);
        $t7_8 = $t18_19;
        $t8_9 = $t9_10;
        $block = 3; break;
        break;
      }
    }
  }
}

export function marmotListGroups() {
  let $t0_1;
  $t0_1 = marmotSendJSON('{"method":"list_groups"}');
  return;
}

export function marmotSendJSON(msg) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = marmotReady.$get();
        if ($t0_1) {
          $block = 2; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 1: {
        $t1_2 = marmotPending.$get();
        $t2_3 = { $value: $rt.builtin.makeSlice(1, 1, ''), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t3_4 = $t2_3.$get().addr(0);
        $t3_4.$set(msg);
        $t4_5 = $rt.builtin.sliceSlice($t2_3.$get(), undefined, undefined, undefined);
        $t5_6 = $rt.builtin.appendSlice($t1_2, $t4_5);
        marmotPending.$set($t5_6);
        return;
        break;
      }
      case 2: {
        $t6_7 = marmotConn.$get();
        $t7_8 = common$jsbridge$ws.Send($t6_7, msg);
        return;
        break;
      }
    }
  }
}

export function marmotOnMessage(msg) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = jsonField(msg, 'method');
        $t1_2 = ($t0_1 === 'auth');
        if ($t1_2) {
          $block = 2; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 1: {
        return;
        break;
      }
      case 2: {
        $t2_3 = jsonField(msg, 'error');
        $t3_4 = ($t2_3 !== '');
        if ($t3_4) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 3: {
        $t4_5 = jsonField(msg, 'peer');
        $t5_6 = jsonField(msg, 'content');
        $t6_7 = jsonField(msg, 'ts');
        $t7_8 = parseInt($t6_7);
        $t8_9 = ($t4_5 !== '');
        if ($t8_9) {
          $block = 13; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 4: {
        $t9_10 = ($t0_1 === 'dm_received');
        if ($t9_10) {
          $block = 3; break;
        }
        else {
          $block = 11; break;
        }
        break;
      }
      case 5: {
        $t10_11 = ('marmot-sw: auth failed: ' + $t2_3);
        $t11_12 = common$jsbridge$sw.Log($t10_11);
        $block = 1; break;
        break;
      }
      case 6: {
        $t12_13 = common$jsbridge$sw.Log('marmot-sw: authenticated');
        $t13_14 = marmotPending.$get();
        $t14_15 = $rt.builtin.len($t13_14);
        $t15_16 = -1;
        $block = 7; break;
        break;
      }
      case 7: {
        $t16_17 = ($t15_16 + 1);
        $t17_18 = ($t16_17 < $t14_15);
        if ($t17_18) {
          $block = 8; break;
        }
        else {
          $block = 9; break;
        }
        break;
      }
      case 8: {
        $t18_19 = $t13_14.addr($t16_17);
        $t19_20 = $t18_19.$get();
        $t20_21 = marmotConn.$get();
        $t21_22 = common$jsbridge$ws.Send($t20_21, $t19_20);
        $t15_16 = $t16_17;
        $block = 7; break;
        break;
      }
      case 9: {
        marmotPending.$set(null);
        $t22_23 = marmotSubscribe();
        $block = 1; break;
        break;
      }
      case 10: {
        $t23_24 = jsonField(msg, 'error');
        $t24_25 = ($t23_24 !== '');
        if ($t24_25) {
          $block = 16; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 11: {
        $t25_26 = ($t0_1 === 'send_dm');
        if ($t25_26) {
          $block = 10; break;
        }
        else {
          $block = 15; break;
        }
        break;
      }
      case 12: {
        $t26_27 = makeDMRecord($t4_5, $t4_5, $t5_6, $t7_8, 'marmot', '');
        $t27_28 = DMRecord$ToJSON($t26_27);
        $t28_29 = ('["DM_RECEIVED",' + $t27_28);
        $t29_30 = ($t28_29 + ']');
        $t30_31 = busSend('shell', $t29_30);
        $block = 1; break;
        break;
      }
      case 13: {
        $t31_32 = ($t5_6 !== '');
        if ($t31_32) {
          $block = 12; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 14: {
        $t32_33 = jsonField(msg, 'error');
        $t33_34 = ($t32_33 !== '');
        if ($t33_34) {
          $block = 19; break;
        }
        else {
          $block = 20; break;
        }
        break;
      }
      case 15: {
        $t34_35 = ($t0_1 === 'subscribe');
        if ($t34_35) {
          $block = 14; break;
        }
        else {
          $block = 18; break;
        }
        break;
      }
      case 16: {
        $t35_36 = ('marmot-sw: send_dm error: ' + $t23_24);
        $t36_37 = common$jsbridge$sw.Log($t35_36);
        $block = 1; break;
        break;
      }
      case 17: {
        $t37_38 = jsonField(msg, 'error');
        $t38_39 = ($t37_38 !== '');
        if ($t38_39) {
          $block = 23; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
      case 18: {
        $t39_40 = ($t0_1 === 'publish_kp');
        if ($t39_40) {
          $block = 17; break;
        }
        else {
          $block = 22; break;
        }
        break;
      }
      case 19: {
        $t40_41 = ('marmot-sw: subscribe error: ' + $t32_33);
        $t41_42 = common$jsbridge$sw.Log($t40_41);
        $block = 1; break;
        break;
      }
      case 20: {
        $t42_43 = common$jsbridge$sw.Log('marmot-sw: subscribed');
        $block = 1; break;
        break;
      }
      case 21: {
        $t43_44 = ('["MLS_GROUPS",' + msg);
        $t44_45 = ($t43_44 + ']');
        $t45_46 = busSend('shell', $t44_45);
        $block = 1; break;
        break;
      }
      case 22: {
        $t46_47 = ($t0_1 === 'list_groups');
        if ($t46_47) {
          $block = 21; break;
        }
        else {
          $block = 25; break;
        }
        break;
      }
      case 23: {
        $t47_48 = ('marmot-sw: publish_kp error: ' + $t37_38);
        $t48_49 = common$jsbridge$sw.Log($t47_48);
        $block = 1; break;
        break;
      }
      case 24: {
        $t49_50 = jsonField(msg, 'error');
        $t50_51 = ('marmot-sw: server error: ' + $t49_50);
        $t51_52 = common$jsbridge$sw.Log($t50_51);
        $block = 1; break;
        break;
      }
      case 25: {
        $t52_53 = ($t0_1 === 'error');
        if ($t52_53) {
          $block = 24; break;
        }
        else {
          $block = 1; break;
        }
        break;
      }
    }
  }
}

export function jsonField(json, key) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = ('"' + key);
        $t1_2 = ($t0_1 + '":');
        $t2_3 = 0;
        $block = 1; break;
        break;
      }
      case 1: {
        $t3_4 = $rt.builtin.len(json);
        $t4_5 = $rt.builtin.len($t1_2);
        $t5_6 = ($t3_4 - $t4_5);
        $t6_7 = ($t2_3 <= $t5_6);
        if ($t6_7) {
          $block = 2; break;
        }
        else {
          $t11_12 = -1;
          $block = 3; break;
        }
        break;
      }
      case 2: {
        $t7_8 = $rt.builtin.len($t1_2);
        $t8_9 = ($t2_3 + $t7_8);
        $t9_10 = $rt.builtin.stringSlice(json, $t2_3, $t8_9);
        $t10_11 = ($t9_10 === $t1_2);
        if ($t10_11) {
          $block = 4; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 3: {
        $t12_13 = ($t11_12 < 0);
        if ($t12_13) {
          $block = 6; break;
        }
        else {
          $t19_20 = $t11_12;
          $block = 9; break;
        }
        break;
      }
      case 4: {
        $t13_14 = $rt.builtin.len($t1_2);
        $t14_15 = ($t2_3 + $t13_14);
        $t11_12 = $t14_15;
        $block = 3; break;
        break;
      }
      case 5: {
        $t15_16 = ($t2_3 + 1);
        $t2_3 = $t15_16;
        $block = 1; break;
        break;
      }
      case 6: {
        return '';
        break;
      }
      case 7: {
        $t16_17 = ($t19_20 + 1);
        $t19_20 = $t16_17;
        $block = 9; break;
        break;
      }
      case 8: {
        $t17_18 = $rt.builtin.len(json);
        $t18_19 = ($t19_20 >= $t17_18);
        if ($t18_19) {
          $block = 12; break;
        }
        else {
          $block = 13; break;
        }
        break;
      }
      case 9: {
        $t20_21 = $rt.builtin.len(json);
        $t21_22 = ($t19_20 < $t20_21);
        if ($t21_22) {
          $block = 10; break;
        }
        else {
          $block = 8; break;
        }
        break;
      }
      case 10: {
        $rt.runtime.boundsCheck($t19_20, $rt.builtin.byteLen(json));
        $t22_23 = $rt.builtin.stringByteAt(json, $t19_20);
        $t23_24 = ($t22_23 === 32);
        if ($t23_24) {
          $block = 7; break;
        }
        else {
          $block = 11; break;
        }
        break;
      }
      case 11: {
        $rt.runtime.boundsCheck($t19_20, $rt.builtin.byteLen(json));
        $t24_25 = $rt.builtin.stringByteAt(json, $t19_20);
        $t25_26 = ($t24_25 === 9);
        if ($t25_26) {
          $block = 7; break;
        }
        else {
          $block = 8; break;
        }
        break;
      }
      case 12: {
        return '';
        break;
      }
      case 13: {
        $rt.runtime.boundsCheck($t19_20, $rt.builtin.byteLen(json));
        $t26_27 = $rt.builtin.stringByteAt(json, $t19_20);
        $t27_28 = ($t26_27 === 34);
        if ($t27_28) {
          $block = 14; break;
        }
        else {
          $block = 15; break;
        }
        break;
      }
      case 14: {
        $t28_29 = ($t19_20 + 1);
        $t32_33 = $t28_29;
        $block = 18; break;
        break;
      }
      case 15: {
        $t42_43 = $t19_20;
        $block = 24; break;
        break;
      }
      case 16: {
        $rt.runtime.boundsCheck($t32_33, $rt.builtin.byteLen(json));
        $t29_30 = $rt.builtin.stringByteAt(json, $t32_33);
        $t30_31 = ($t29_30 === 92);
        if ($t30_31) {
          $block = 20; break;
        }
        else {
          $t38_39 = $t32_33;
          $block = 21; break;
        }
        break;
      }
      case 17: {
        $t31_32 = $rt.builtin.stringSlice(json, $t28_29, $t32_33);
        return $t31_32;
        break;
      }
      case 18: {
        $t33_34 = $rt.builtin.len(json);
        $t34_35 = ($t32_33 < $t33_34);
        if ($t34_35) {
          $block = 19; break;
        }
        else {
          $block = 17; break;
        }
        break;
      }
      case 19: {
        $rt.runtime.boundsCheck($t32_33, $rt.builtin.byteLen(json));
        $t35_36 = $rt.builtin.stringByteAt(json, $t32_33);
        $t36_37 = ($t35_36 !== 34);
        if ($t36_37) {
          $block = 16; break;
        }
        else {
          $block = 17; break;
        }
        break;
      }
      case 20: {
        $t37_38 = ($t32_33 + 1);
        $t38_39 = $t37_38;
        $block = 21; break;
        break;
      }
      case 21: {
        $t39_40 = ($t38_39 + 1);
        $t32_33 = $t39_40;
        $block = 18; break;
        break;
      }
      case 22: {
        $t40_41 = ($t42_43 + 1);
        $t42_43 = $t40_41;
        $block = 24; break;
        break;
      }
      case 23: {
        $t41_42 = $rt.builtin.stringSlice(json, $t19_20, $t42_43);
        return $t41_42;
        break;
      }
      case 24: {
        $t43_44 = $rt.builtin.len(json);
        $t44_45 = ($t42_43 < $t43_44);
        if ($t44_45) {
          $block = 27; break;
        }
        else {
          $block = 23; break;
        }
        break;
      }
      case 25: {
        $rt.runtime.boundsCheck($t42_43, $rt.builtin.byteLen(json));
        $t45_46 = $rt.builtin.stringByteAt(json, $t42_43);
        $t46_47 = ($t45_46 !== 32);
        if ($t46_47) {
          $block = 22; break;
        }
        else {
          $block = 23; break;
        }
        break;
      }
      case 26: {
        $rt.runtime.boundsCheck($t42_43, $rt.builtin.byteLen(json));
        $t47_48 = $rt.builtin.stringByteAt(json, $t42_43);
        $t48_49 = ($t47_48 !== 125);
        if ($t48_49) {
          $block = 25; break;
        }
        else {
          $block = 23; break;
        }
        break;
      }
      case 27: {
        $rt.runtime.boundsCheck($t42_43, $rt.builtin.byteLen(json));
        $t49_50 = $rt.builtin.stringByteAt(json, $t42_43);
        $t50_51 = ($t49_50 !== 44);
        if ($t50_51) {
          $block = 26; break;
        }
        else {
          $block = 23; break;
        }
        break;
      }
    }
  }
}

export function parseInt(s) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = 0;
        $t1_2 = 0;
        $block = 1; break;
        break;
      }
      case 1: {
        $t2_3 = $rt.builtin.len(s);
        $t3_4 = ($t1_2 < $t2_3);
        if ($t3_4) {
          $block = 2; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 2: {
        $rt.runtime.boundsCheck($t1_2, $rt.builtin.byteLen(s));
        $t4_5 = $rt.builtin.stringByteAt(s, $t1_2);
        $t5_6 = ($t4_5 >= 48);
        if ($t5_6) {
          $block = 6; break;
        }
        else {
          $t11_12 = $t0_1;
          $block = 5; break;
        }
        break;
      }
      case 3: {
        return $t0_1;
        break;
      }
      case 4: {
        $t6_7 = ($t0_1 * 10);
        $rt.runtime.boundsCheck($t1_2, $rt.builtin.byteLen(s));
        $t7_8 = $rt.builtin.stringByteAt(s, $t1_2);
        $t8_9 = (($t7_8 - 48) & 0xFF);
        $t9_10 = $t8_9;
        $t10_11 = ($t6_7 + $t9_10);
        $t11_12 = $t10_11;
        $block = 5; break;
        break;
      }
      case 5: {
        $t12_13 = ($t1_2 + 1);
        $t0_1 = $t11_12;
        $t1_2 = $t12_13;
        $block = 1; break;
        break;
      }
      case 6: {
        $rt.runtime.boundsCheck($t1_2, $rt.builtin.byteLen(s));
        $t13_14 = $rt.builtin.stringByteAt(s, $t1_2);
        $t14_15 = ($t13_14 <= 57);
        if ($t14_15) {
          $block = 4; break;
        }
        else {
          $t11_12 = $t0_1;
          $block = 5; break;
        }
        break;
      }
    }
  }
}

export function DMRecord$ToJSON(r) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35;
  $t0_1 = { $get() { return r.$get().ID; }, $set(v) { const obj = r.$get(); obj.ID = v; r.$set(obj); } };
  $t1_2 = $t0_1.$get();
  $t2_3 = jstr($t1_2);
  $t3_4 = ('{"id":' + $t2_3);
  $t4_5 = ($t3_4 + ',"peer":');
  $t5_6 = { $get() { return r.$get().Peer; }, $set(v) { const obj = r.$get(); obj.Peer = v; r.$set(obj); } };
  $t6_7 = $t5_6.$get();
  $t7_8 = jstr($t6_7);
  $t8_9 = ($t4_5 + $t7_8);
  $t9_10 = ($t8_9 + ',"from":');
  $t10_11 = { $get() { return r.$get().From; }, $set(v) { const obj = r.$get(); obj.From = v; r.$set(obj); } };
  $t11_12 = $t10_11.$get();
  $t12_13 = jstr($t11_12);
  $t13_14 = ($t9_10 + $t12_13);
  $t14_15 = ($t13_14 + ',"content":');
  $t15_16 = { $get() { return r.$get().Content; }, $set(v) { const obj = r.$get(); obj.Content = v; r.$set(obj); } };
  $t16_17 = $t15_16.$get();
  $t17_18 = jstr($t16_17);
  $t18_19 = ($t14_15 + $t17_18);
  $t19_20 = ($t18_19 + ',"created_at":');
  $t20_21 = { $get() { return r.$get().CreatedAt; }, $set(v) { const obj = r.$get(); obj.CreatedAt = v; r.$set(obj); } };
  $t21_22 = $t20_21.$get();
  $t22_23 = common$helpers.Itoa($t21_22);
  $t23_24 = ($t19_20 + $t22_23);
  $t24_25 = ($t23_24 + ',"protocol":');
  $t25_26 = { $get() { return r.$get().Protocol; }, $set(v) { const obj = r.$get(); obj.Protocol = v; r.$set(obj); } };
  $t26_27 = $t25_26.$get();
  $t27_28 = jstr($t26_27);
  $t28_29 = ($t24_25 + $t27_28);
  $t29_30 = ($t28_29 + ',"eventId":');
  $t30_31 = { $get() { return r.$get().EventID; }, $set(v) { const obj = r.$get(); obj.EventID = v; r.$set(obj); } };
  $t31_32 = $t30_31.$get();
  $t32_33 = jstr($t31_32);
  $t33_34 = ($t29_30 + $t32_33);
  $t34_35 = ($t33_34 + '}');
  return $t34_35;
}

$rt.types.getType('sw-marmot.DMRecord')?.methods?.set('ToJSON', DMRecord$ToJSON);
export function mw$num(w) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = mw$sep(w);
        $t1_2 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t2_3 = $t1_2.$get();
        $t3_4 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t4_5 = $t3_4.$get();
        $t5_6 = $rt.builtin.len($t4_5);
        $t6_7 = ($t2_3 < $t5_6);
        if ($t6_7) {
          $block = 3; break;
        }
        else {
          $t11_12 = false;
          $block = 2; break;
        }
        break;
      }
      case 1: {
        $t7_8 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t8_9 = $t7_8.$get();
        $t9_10 = ($t8_9 + 1);
        $t10_11 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t10_11.$set($t9_10);
        $t11_12 = true;
        $block = 2; break;
        break;
      }
      case 2: {
        $t31_32 = 0;
        $block = 6; break;
        break;
      }
      case 3: {
        $t12_13 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t13_14 = $t12_13.$get();
        $t14_15 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t15_16 = $t14_15.$get();
        $rt.runtime.boundsCheck($t13_14, $rt.builtin.byteLen($t15_16));
        $t16_17 = $rt.builtin.stringByteAt($t15_16, $t13_14);
        $t17_18 = ($t16_17 === 45);
        if ($t17_18) {
          $block = 1; break;
        }
        else {
          $t11_12 = false;
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t18_19 = ($t31_32 * 10);
        $t19_20 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t20_21 = $t19_20.$get();
        $t21_22 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t22_23 = $t21_22.$get();
        $rt.runtime.boundsCheck($t20_21, $rt.builtin.byteLen($t22_23));
        $t23_24 = $rt.builtin.stringByteAt($t22_23, $t20_21);
        $t24_25 = (($t23_24 - 48) & 0xFF);
        $t25_26 = $t24_25;
        $t26_27 = ($t18_19 + $t25_26);
        $t27_28 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t28_29 = $t27_28.$get();
        $t29_30 = ($t28_29 + 1);
        $t30_31 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t30_31.$set($t29_30);
        $t31_32 = $t26_27;
        $block = 6; break;
        break;
      }
      case 5: {
        if ($t11_12) {
          $block = 9; break;
        }
        else {
          $t51_52 = $t31_32;
          $block = 10; break;
        }
        break;
      }
      case 6: {
        $t32_33 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t33_34 = $t32_33.$get();
        $t34_35 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t35_36 = $t34_35.$get();
        $t36_37 = $rt.builtin.len($t35_36);
        $t37_38 = ($t33_34 < $t36_37);
        if ($t37_38) {
          $block = 8; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 7: {
        $t38_39 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t39_40 = $t38_39.$get();
        $t40_41 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t41_42 = $t40_41.$get();
        $rt.runtime.boundsCheck($t39_40, $rt.builtin.byteLen($t41_42));
        $t42_43 = $rt.builtin.stringByteAt($t41_42, $t39_40);
        $t43_44 = ($t42_43 <= 57);
        if ($t43_44) {
          $block = 4; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 8: {
        $t44_45 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t45_46 = $t44_45.$get();
        $t46_47 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t47_48 = $t46_47.$get();
        $rt.runtime.boundsCheck($t45_46, $rt.builtin.byteLen($t47_48));
        $t48_49 = $rt.builtin.stringByteAt($t47_48, $t45_46);
        $t49_50 = ($t48_49 >= 48);
        if ($t49_50) {
          $block = 7; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 9: {
        $t50_51 = -$t31_32;
        $t51_52 = $t50_51;
        $block = 10; break;
        break;
      }
      case 10: {
        return $t51_52;
        break;
      }
    }
  }
}

$rt.types.getType('sw-marmot.mw')?.methods?.set('num', mw$num);
export function mw$raw(w) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = mw$sep(w);
        $t1_2 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t2_3 = $t1_2.$get();
        $t3_4 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t4_5 = $t3_4.$get();
        $t5_6 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t6_7 = $t5_6.$get();
        $t7_8 = skipval($t4_5, $t6_7);
        $t8_9 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t8_9.$set($t7_8);
        $t9_10 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t10_11 = $t9_10.$get();
        $t11_12 = ($t10_11 < 0);
        if ($t11_12) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 1: {
        $t12_13 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t13_14 = $t12_13.$get();
        $t14_15 = $rt.builtin.len($t13_14);
        $t15_16 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t15_16.$set($t14_15);
        return '';
        break;
      }
      case 2: {
        $t16_17 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t17_18 = $t16_17.$get();
        $t18_19 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t19_20 = $t18_19.$get();
        $t20_21 = $rt.builtin.stringSlice($t17_18, $t2_3, $t19_20);
        return $t20_21;
        break;
      }
    }
  }
}

$rt.types.getType('sw-marmot.mw')?.methods?.set('raw', mw$raw);
export function mw$sep(w) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $block = 3; break;
        break;
      }
      case 1: {
        $t0_1 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t1_2 = $t0_1.$get();
        $t2_3 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t3_4 = $t2_3.$get();
        $rt.runtime.boundsCheck($t1_2, $rt.builtin.byteLen($t3_4));
        $t4_5 = $rt.builtin.stringByteAt($t3_4, $t1_2);
        $t5_6 = ($t4_5 !== 32);
        if ($t5_6) {
          $block = 8; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 2: {
        return;
        break;
      }
      case 3: {
        $t6_7 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t7_8 = $t6_7.$get();
        $t8_9 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t9_10 = $t8_9.$get();
        $t10_11 = $rt.builtin.len($t9_10);
        $t11_12 = ($t7_8 < $t10_11);
        if ($t11_12) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t12_13 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t13_14 = $t12_13.$get();
        $t14_15 = ($t13_14 + 1);
        $t15_16 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t15_16.$set($t14_15);
        $block = 3; break;
        break;
      }
      case 5: {
        $t16_17 = ($t4_5 !== 44);
        if ($t16_17) {
          $block = 2; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 6: {
        $t17_18 = ($t4_5 !== 9);
        if ($t17_18) {
          $block = 5; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 7: {
        $t18_19 = ($t4_5 !== 13);
        if ($t18_19) {
          $block = 6; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
      case 8: {
        $t19_20 = ($t4_5 !== 10);
        if ($t19_20) {
          $block = 7; break;
        }
        else {
          $block = 4; break;
        }
        break;
      }
    }
  }
}

$rt.types.getType('sw-marmot.mw')?.methods?.set('sep', mw$sep);
export function mw$str(w) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = mw$sep(w);
        $t1_2 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t2_3 = $t1_2.$get();
        $t3_4 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t4_5 = $t3_4.$get();
        $t5_6 = $rt.builtin.len($t4_5);
        $t6_7 = ($t2_3 >= $t5_6);
        if ($t6_7) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 1: {
        return '';
        break;
      }
      case 2: {
        $t7_8 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t8_9 = $t7_8.$get();
        $t9_10 = ($t8_9 + 1);
        $t10_11 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t10_11.$set($t9_10);
        $t11_12 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t12_13 = $t11_12.$get();
        $block = 6; break;
        break;
      }
      case 3: {
        $t13_14 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t14_15 = $t13_14.$get();
        $t15_16 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t16_17 = $t15_16.$get();
        $rt.runtime.boundsCheck($t14_15, $rt.builtin.byteLen($t16_17));
        $t17_18 = $rt.builtin.stringByteAt($t16_17, $t14_15);
        $t18_19 = ($t17_18 !== 34);
        if ($t18_19) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t19_20 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t20_21 = $t19_20.$get();
        $t21_22 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t22_23 = $t21_22.$get();
        $rt.runtime.boundsCheck($t20_21, $rt.builtin.byteLen($t22_23));
        $t23_24 = $rt.builtin.stringByteAt($t22_23, $t20_21);
        $t24_25 = ($t23_24 === 92);
        if ($t24_25) {
          $block = 8; break;
        }
        else {
          $block = 9; break;
        }
        break;
      }
      case 5: {
        $t25_26 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t26_27 = $t25_26.$get();
        $t27_28 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t28_29 = $t27_28.$get();
        $t29_30 = $rt.builtin.len($t28_29);
        $t30_31 = ($t26_27 >= $t29_30);
        if ($t30_31) {
          $block = 10; break;
        }
        else {
          $block = 11; break;
        }
        break;
      }
      case 6: {
        $t31_32 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t32_33 = $t31_32.$get();
        $t33_34 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t34_35 = $t33_34.$get();
        $t35_36 = $rt.builtin.len($t34_35);
        $t36_37 = ($t32_33 < $t35_36);
        if ($t36_37) {
          $block = 7; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 7: {
        $t37_38 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t38_39 = $t37_38.$get();
        $t39_40 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t40_41 = $t39_40.$get();
        $rt.runtime.boundsCheck($t38_39, $rt.builtin.byteLen($t40_41));
        $t41_42 = $rt.builtin.stringByteAt($t40_41, $t38_39);
        $t42_43 = ($t41_42 !== 34);
        if ($t42_43) {
          $block = 4; break;
        }
        else {
          $block = 5; break;
        }
        break;
      }
      case 8: {
        $t43_44 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t44_45 = $t43_44.$get();
        $t45_46 = ($t44_45 + 1);
        $t46_47 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t46_47.$set($t45_46);
        $block = 9; break;
        break;
      }
      case 9: {
        $t47_48 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t48_49 = $t47_48.$get();
        $t49_50 = ($t48_49 + 1);
        $t50_51 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t50_51.$set($t49_50);
        $block = 6; break;
        break;
      }
      case 10: {
        return '';
        break;
      }
      case 11: {
        $t51_52 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t52_53 = $t51_52.$get();
        $t53_54 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t54_55 = $t53_54.$get();
        $t55_56 = $rt.builtin.stringSlice($t52_53, $t12_13, $t54_55);
        $t56_57 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t57_58 = $t56_57.$get();
        $t58_59 = ($t57_58 + 1);
        $t59_60 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t59_60.$set($t58_59);
        return $t55_56;
        break;
      }
    }
  }
}

$rt.types.getType('sw-marmot.mw')?.methods?.set('str', mw$str);
export function mw$strs(w) {
  let $t0_1, $t1_2, $t2_3, $t3_4, $t4_5, $t5_6, $t6_7, $t7_8, $t8_9, $t9_10, $t10_11, $t11_12, $t12_13, $t13_14, $t14_15, $t15_16, $t16_17, $t17_18, $t18_19, $t19_20, $t20_21, $t21_22, $t22_23, $t23_24, $t24_25, $t25_26, $t26_27, $t27_28, $t28_29, $t29_30, $t30_31, $t31_32, $t32_33, $t33_34, $t34_35, $t35_36, $t36_37, $t37_38, $t38_39, $t39_40, $t40_41, $t41_42, $t42_43, $t43_44, $t44_45, $t45_46, $t46_47, $t47_48, $t48_49, $t49_50, $t50_51, $t51_52, $t52_53, $t53_54, $t54_55, $t55_56, $t56_57, $t57_58, $t58_59, $t59_60, $t60_61, $t61_62, $t62_63, $t63_64, $t64_65, $t65_66, $t66_67, $t67_68, $t68_69, $t69_70, $t70_71, $t71_72, $t72_73, $t73_74, $t74_75, $t75_76, $t76_77, $t77_78, $t78_79, $t79_80, $t80_81, $t81_82, $t82_83, $t83_84, $t84_85, $t85_86, $t86_87, $t87_88, $t88_89, $t89_90, $t90_91, $t91_92;
  let $block = 0;
  while (true) {
    switch ($block) {
      case 0: {
        $t0_1 = mw$sep(w);
        $t1_2 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t2_3 = $t1_2.$get();
        $t3_4 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t4_5 = $t3_4.$get();
        $t5_6 = $rt.builtin.len($t4_5);
        $t6_7 = ($t2_3 >= $t5_6);
        if ($t6_7) {
          $block = 1; break;
        }
        else {
          $block = 3; break;
        }
        break;
      }
      case 1: {
        return null;
        break;
      }
      case 2: {
        $t7_8 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t8_9 = $t7_8.$get();
        $t9_10 = ($t8_9 + 1);
        $t10_11 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t10_11.$set($t9_10);
        $t17_18 = null;
        $block = 4; break;
        break;
      }
      case 3: {
        $t11_12 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t12_13 = $t11_12.$get();
        $t13_14 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t14_15 = $t13_14.$get();
        $rt.runtime.boundsCheck($t12_13, $rt.builtin.byteLen($t14_15));
        $t15_16 = $rt.builtin.stringByteAt($t14_15, $t12_13);
        $t16_17 = ($t15_16 !== 91);
        if ($t16_17) {
          $block = 1; break;
        }
        else {
          $block = 2; break;
        }
        break;
      }
      case 4: {
        $t18_19 = mw$sep(w);
        $t19_20 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t20_21 = $t19_20.$get();
        $t21_22 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t22_23 = $t21_22.$get();
        $t23_24 = $rt.builtin.len($t22_23);
        $t24_25 = ($t20_21 >= $t23_24);
        if ($t24_25) {
          $block = 5; break;
        }
        else {
          $block = 6; break;
        }
        break;
      }
      case 5: {
        return $t17_18;
        break;
      }
      case 6: {
        $t25_26 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t26_27 = $t25_26.$get();
        $t27_28 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t28_29 = $t27_28.$get();
        $rt.runtime.boundsCheck($t26_27, $rt.builtin.byteLen($t28_29));
        $t29_30 = $rt.builtin.stringByteAt($t28_29, $t26_27);
        $t30_31 = ($t29_30 === 93);
        if ($t30_31) {
          $block = 7; break;
        }
        else {
          $block = 8; break;
        }
        break;
      }
      case 7: {
        $t31_32 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t32_33 = $t31_32.$get();
        $t33_34 = ($t32_33 + 1);
        $t34_35 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t34_35.$set($t33_34);
        return $t17_18;
        break;
      }
      case 8: {
        $t35_36 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t36_37 = $t35_36.$get();
        $t37_38 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t38_39 = $t37_38.$get();
        $rt.runtime.boundsCheck($t36_37, $rt.builtin.byteLen($t38_39));
        $t39_40 = $rt.builtin.stringByteAt($t38_39, $t36_37);
        $t40_41 = ($t39_40 !== 34);
        if ($t40_41) {
          $block = 9; break;
        }
        else {
          $block = 10; break;
        }
        break;
      }
      case 9: {
        return $t17_18;
        break;
      }
      case 10: {
        $t41_42 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t42_43 = $t41_42.$get();
        $t43_44 = ($t42_43 + 1);
        $t44_45 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t44_45.$set($t43_44);
        $t45_46 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t46_47 = $t45_46.$get();
        $block = 13; break;
        break;
      }
      case 11: {
        $t47_48 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t48_49 = $t47_48.$get();
        $t49_50 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t50_51 = $t49_50.$get();
        $rt.runtime.boundsCheck($t48_49, $rt.builtin.byteLen($t50_51));
        $t51_52 = $rt.builtin.stringByteAt($t50_51, $t48_49);
        $t52_53 = ($t51_52 === 92);
        if ($t52_53) {
          $block = 15; break;
        }
        else {
          $block = 16; break;
        }
        break;
      }
      case 12: {
        $t53_54 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t54_55 = $t53_54.$get();
        $t55_56 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t56_57 = $t55_56.$get();
        $t57_58 = $rt.builtin.len($t56_57);
        $t58_59 = ($t54_55 < $t57_58);
        if ($t58_59) {
          $block = 17; break;
        }
        else {
          $t17_18 = $t17_18;
          $block = 4; break;
        }
        break;
      }
      case 13: {
        $t59_60 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t60_61 = $t59_60.$get();
        $t61_62 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t62_63 = $t61_62.$get();
        $t63_64 = $rt.builtin.len($t62_63);
        $t64_65 = ($t60_61 < $t63_64);
        if ($t64_65) {
          $block = 14; break;
        }
        else {
          $block = 12; break;
        }
        break;
      }
      case 14: {
        $t65_66 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t66_67 = $t65_66.$get();
        $t67_68 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t68_69 = $t67_68.$get();
        $rt.runtime.boundsCheck($t66_67, $rt.builtin.byteLen($t68_69));
        $t69_70 = $rt.builtin.stringByteAt($t68_69, $t66_67);
        $t70_71 = ($t69_70 !== 34);
        if ($t70_71) {
          $block = 11; break;
        }
        else {
          $block = 12; break;
        }
        break;
      }
      case 15: {
        $t71_72 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t72_73 = $t71_72.$get();
        $t73_74 = ($t72_73 + 1);
        $t74_75 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t74_75.$set($t73_74);
        $block = 16; break;
        break;
      }
      case 16: {
        $t75_76 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t76_77 = $t75_76.$get();
        $t77_78 = ($t76_77 + 1);
        $t78_79 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t78_79.$set($t77_78);
        $block = 13; break;
        break;
      }
      case 17: {
        $t79_80 = { $get() { return w.$get().s; }, $set(v) { const obj = w.$get(); obj.s = v; w.$set(obj); } };
        $t80_81 = $t79_80.$get();
        $t81_82 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t82_83 = $t81_82.$get();
        $t83_84 = $rt.builtin.stringSlice($t80_81, $t46_47, $t82_83);
        $t84_85 = { $value: $rt.builtin.makeSlice(1, 1, ''), $get() { return this.$value; }, $set(v) { this.$value = v; } };
        $t85_86 = $t84_85.$get().addr(0);
        $t85_86.$set($t83_84);
        $t86_87 = $rt.builtin.sliceSlice($t84_85.$get(), undefined, undefined, undefined);
        $t87_88 = $rt.builtin.appendSlice($t17_18, $t86_87);
        $t88_89 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t89_90 = $t88_89.$get();
        $t90_91 = ($t89_90 + 1);
        $t91_92 = { $get() { return w.$get().i; }, $set(v) { const obj = w.$get(); obj.i = v; w.$set(obj); } };
        $t91_92.$set($t90_91);
        $t17_18 = $t87_88;
        $block = 4; break;
        break;
      }
    }
  }
}

$rt.types.getType('sw-marmot.mw')?.methods?.set('strs', mw$strs);
